-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity streamToData is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    IN1024OUT8192_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN1024OUT8192_TVALID : IN STD_LOGIC;
    IN1024OUT8192_TREADY : OUT STD_LOGIC;
    IN1024OUT8192_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN1024OUT8192_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN1024OUT8192_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN2048OUT8192_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN2048OUT8192_TVALID : IN STD_LOGIC;
    IN2048OUT8192_TREADY : OUT STD_LOGIC;
    IN2048OUT8192_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN2048OUT8192_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN2048OUT8192_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN4096OUT8192_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN4096OUT8192_TVALID : IN STD_LOGIC;
    IN4096OUT8192_TREADY : OUT STD_LOGIC;
    IN4096OUT8192_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN4096OUT8192_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN4096OUT8192_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN8192OUT65536_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN8192OUT65536_TVALID : IN STD_LOGIC;
    IN8192OUT65536_TREADY : OUT STD_LOGIC;
    IN8192OUT65536_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN8192OUT65536_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN8192OUT65536_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN16384OUT65536_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN16384OUT65536_TVALID : IN STD_LOGIC;
    IN16384OUT65536_TREADY : OUT STD_LOGIC;
    IN16384OUT65536_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN16384OUT65536_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN16384OUT65536_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN32768OUT65536_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN32768OUT65536_TVALID : IN STD_LOGIC;
    IN32768OUT65536_TREADY : OUT STD_LOGIC;
    IN32768OUT65536_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN32768OUT65536_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN32768OUT65536_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN65536OUT262144_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN65536OUT262144_TVALID : IN STD_LOGIC;
    IN65536OUT262144_TREADY : OUT STD_LOGIC;
    IN65536OUT262144_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN65536OUT262144_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN65536OUT262144_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN131072OUT262144_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN131072OUT262144_TVALID : IN STD_LOGIC;
    IN131072OUT262144_TREADY : OUT STD_LOGIC;
    IN131072OUT262144_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN131072OUT262144_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN131072OUT262144_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    IN262144OUT262144_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    IN262144OUT262144_TVALID : IN STD_LOGIC;
    IN262144OUT262144_TREADY : OUT STD_LOGIC;
    IN262144OUT262144_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    IN262144OUT262144_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    IN262144OUT262144_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    DacData : OUT STD_LOGIC_VECTOR (23 downto 0);
    DacData_ap_vld : OUT STD_LOGIC;
    interp : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of streamToData is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "streamToData_streamToData,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=29.802000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.571100,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1,HLS_SYN_LUT=225,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv23_780000 : STD_LOGIC_VECTOR (22 downto 0) := "11110000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv21_17FFFF : STD_LOGIC_VECTOR (20 downto 0) := "101111111111111111111";
    constant ap_const_lv21_180000 : STD_LOGIC_VECTOR (20 downto 0) := "110000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal IN1024OUT8192_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal IN2048OUT8192_TDATA_blk_n : STD_LOGIC;
    signal IN4096OUT8192_TDATA_blk_n : STD_LOGIC;
    signal IN8192OUT65536_TDATA_blk_n : STD_LOGIC;
    signal IN16384OUT65536_TDATA_blk_n : STD_LOGIC;
    signal IN32768OUT65536_TDATA_blk_n : STD_LOGIC;
    signal IN65536OUT262144_TDATA_blk_n : STD_LOGIC;
    signal IN131072OUT262144_TDATA_blk_n : STD_LOGIC;
    signal IN262144OUT262144_TDATA_blk_n : STD_LOGIC;
    signal ap_phi_mux_phi_ln30_phi_fu_284_p18 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_predicate_op88_read_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal tmp_fu_357_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_data_fu_349_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln23_fu_353_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal icmp_ln66_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln69_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln69_fu_387_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal or_ln_fu_379_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal DacCounts_fu_401_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN1024OUT8192_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN1024OUT8192_TVALID_int_regslice : STD_LOGIC;
    signal IN1024OUT8192_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN1024OUT8192_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN1024OUT8192_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN1024OUT8192_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN1024OUT8192_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN1024OUT8192_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN1024OUT8192_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN1024OUT8192_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN2048OUT8192_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN2048OUT8192_TVALID_int_regslice : STD_LOGIC;
    signal IN2048OUT8192_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN2048OUT8192_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN2048OUT8192_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN2048OUT8192_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN2048OUT8192_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN2048OUT8192_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN2048OUT8192_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN2048OUT8192_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN4096OUT8192_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN4096OUT8192_TVALID_int_regslice : STD_LOGIC;
    signal IN4096OUT8192_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN4096OUT8192_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN4096OUT8192_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN4096OUT8192_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN4096OUT8192_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN4096OUT8192_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN4096OUT8192_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN4096OUT8192_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN8192OUT65536_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN8192OUT65536_TVALID_int_regslice : STD_LOGIC;
    signal IN8192OUT65536_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN8192OUT65536_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN8192OUT65536_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN8192OUT65536_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN8192OUT65536_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN8192OUT65536_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN8192OUT65536_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN8192OUT65536_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN16384OUT65536_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN16384OUT65536_TVALID_int_regslice : STD_LOGIC;
    signal IN16384OUT65536_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN16384OUT65536_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN16384OUT65536_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN16384OUT65536_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN16384OUT65536_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN16384OUT65536_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN16384OUT65536_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN16384OUT65536_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN32768OUT65536_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN32768OUT65536_TVALID_int_regslice : STD_LOGIC;
    signal IN32768OUT65536_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN32768OUT65536_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN32768OUT65536_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN32768OUT65536_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN32768OUT65536_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN32768OUT65536_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN32768OUT65536_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN32768OUT65536_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN65536OUT262144_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN65536OUT262144_TVALID_int_regslice : STD_LOGIC;
    signal IN65536OUT262144_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN65536OUT262144_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN65536OUT262144_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN65536OUT262144_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN65536OUT262144_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN65536OUT262144_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN65536OUT262144_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN65536OUT262144_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN131072OUT262144_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN131072OUT262144_TVALID_int_regslice : STD_LOGIC;
    signal IN131072OUT262144_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN131072OUT262144_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN131072OUT262144_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN131072OUT262144_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN131072OUT262144_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN131072OUT262144_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN131072OUT262144_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN131072OUT262144_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_data_V_U_apdone_blk : STD_LOGIC;
    signal IN262144OUT262144_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal IN262144OUT262144_TVALID_int_regslice : STD_LOGIC;
    signal IN262144OUT262144_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN262144OUT262144_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN262144OUT262144_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal IN262144OUT262144_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN262144OUT262144_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_last_V_U_apdone_blk : STD_LOGIC;
    signal IN262144OUT262144_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN262144OUT262144_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN262144OUT262144_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_condition_122 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component streamToData_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_IN1024OUT8192_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN1024OUT8192_TDATA,
        vld_in => IN1024OUT8192_TVALID,
        ack_in => regslice_both_IN1024OUT8192_V_data_V_U_ack_in,
        data_out => IN1024OUT8192_TDATA_int_regslice,
        vld_out => IN1024OUT8192_TVALID_int_regslice,
        ack_out => IN1024OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN1024OUT8192_V_data_V_U_apdone_blk);

    regslice_both_IN1024OUT8192_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN1024OUT8192_TKEEP,
        vld_in => IN1024OUT8192_TVALID,
        ack_in => regslice_both_IN1024OUT8192_V_keep_V_U_ack_in,
        data_out => IN1024OUT8192_TKEEP_int_regslice,
        vld_out => regslice_both_IN1024OUT8192_V_keep_V_U_vld_out,
        ack_out => IN1024OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN1024OUT8192_V_keep_V_U_apdone_blk);

    regslice_both_IN1024OUT8192_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN1024OUT8192_TSTRB,
        vld_in => IN1024OUT8192_TVALID,
        ack_in => regslice_both_IN1024OUT8192_V_strb_V_U_ack_in,
        data_out => IN1024OUT8192_TSTRB_int_regslice,
        vld_out => regslice_both_IN1024OUT8192_V_strb_V_U_vld_out,
        ack_out => IN1024OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN1024OUT8192_V_strb_V_U_apdone_blk);

    regslice_both_IN1024OUT8192_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN1024OUT8192_TLAST,
        vld_in => IN1024OUT8192_TVALID,
        ack_in => regslice_both_IN1024OUT8192_V_last_V_U_ack_in,
        data_out => IN1024OUT8192_TLAST_int_regslice,
        vld_out => regslice_both_IN1024OUT8192_V_last_V_U_vld_out,
        ack_out => IN1024OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN1024OUT8192_V_last_V_U_apdone_blk);

    regslice_both_IN2048OUT8192_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN2048OUT8192_TDATA,
        vld_in => IN2048OUT8192_TVALID,
        ack_in => regslice_both_IN2048OUT8192_V_data_V_U_ack_in,
        data_out => IN2048OUT8192_TDATA_int_regslice,
        vld_out => IN2048OUT8192_TVALID_int_regslice,
        ack_out => IN2048OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN2048OUT8192_V_data_V_U_apdone_blk);

    regslice_both_IN2048OUT8192_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN2048OUT8192_TKEEP,
        vld_in => IN2048OUT8192_TVALID,
        ack_in => regslice_both_IN2048OUT8192_V_keep_V_U_ack_in,
        data_out => IN2048OUT8192_TKEEP_int_regslice,
        vld_out => regslice_both_IN2048OUT8192_V_keep_V_U_vld_out,
        ack_out => IN2048OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN2048OUT8192_V_keep_V_U_apdone_blk);

    regslice_both_IN2048OUT8192_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN2048OUT8192_TSTRB,
        vld_in => IN2048OUT8192_TVALID,
        ack_in => regslice_both_IN2048OUT8192_V_strb_V_U_ack_in,
        data_out => IN2048OUT8192_TSTRB_int_regslice,
        vld_out => regslice_both_IN2048OUT8192_V_strb_V_U_vld_out,
        ack_out => IN2048OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN2048OUT8192_V_strb_V_U_apdone_blk);

    regslice_both_IN2048OUT8192_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN2048OUT8192_TLAST,
        vld_in => IN2048OUT8192_TVALID,
        ack_in => regslice_both_IN2048OUT8192_V_last_V_U_ack_in,
        data_out => IN2048OUT8192_TLAST_int_regslice,
        vld_out => regslice_both_IN2048OUT8192_V_last_V_U_vld_out,
        ack_out => IN2048OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN2048OUT8192_V_last_V_U_apdone_blk);

    regslice_both_IN4096OUT8192_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN4096OUT8192_TDATA,
        vld_in => IN4096OUT8192_TVALID,
        ack_in => regslice_both_IN4096OUT8192_V_data_V_U_ack_in,
        data_out => IN4096OUT8192_TDATA_int_regslice,
        vld_out => IN4096OUT8192_TVALID_int_regslice,
        ack_out => IN4096OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN4096OUT8192_V_data_V_U_apdone_blk);

    regslice_both_IN4096OUT8192_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN4096OUT8192_TKEEP,
        vld_in => IN4096OUT8192_TVALID,
        ack_in => regslice_both_IN4096OUT8192_V_keep_V_U_ack_in,
        data_out => IN4096OUT8192_TKEEP_int_regslice,
        vld_out => regslice_both_IN4096OUT8192_V_keep_V_U_vld_out,
        ack_out => IN4096OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN4096OUT8192_V_keep_V_U_apdone_blk);

    regslice_both_IN4096OUT8192_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN4096OUT8192_TSTRB,
        vld_in => IN4096OUT8192_TVALID,
        ack_in => regslice_both_IN4096OUT8192_V_strb_V_U_ack_in,
        data_out => IN4096OUT8192_TSTRB_int_regslice,
        vld_out => regslice_both_IN4096OUT8192_V_strb_V_U_vld_out,
        ack_out => IN4096OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN4096OUT8192_V_strb_V_U_apdone_blk);

    regslice_both_IN4096OUT8192_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN4096OUT8192_TLAST,
        vld_in => IN4096OUT8192_TVALID,
        ack_in => regslice_both_IN4096OUT8192_V_last_V_U_ack_in,
        data_out => IN4096OUT8192_TLAST_int_regslice,
        vld_out => regslice_both_IN4096OUT8192_V_last_V_U_vld_out,
        ack_out => IN4096OUT8192_TREADY_int_regslice,
        apdone_blk => regslice_both_IN4096OUT8192_V_last_V_U_apdone_blk);

    regslice_both_IN8192OUT65536_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN8192OUT65536_TDATA,
        vld_in => IN8192OUT65536_TVALID,
        ack_in => regslice_both_IN8192OUT65536_V_data_V_U_ack_in,
        data_out => IN8192OUT65536_TDATA_int_regslice,
        vld_out => IN8192OUT65536_TVALID_int_regslice,
        ack_out => IN8192OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN8192OUT65536_V_data_V_U_apdone_blk);

    regslice_both_IN8192OUT65536_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN8192OUT65536_TKEEP,
        vld_in => IN8192OUT65536_TVALID,
        ack_in => regslice_both_IN8192OUT65536_V_keep_V_U_ack_in,
        data_out => IN8192OUT65536_TKEEP_int_regslice,
        vld_out => regslice_both_IN8192OUT65536_V_keep_V_U_vld_out,
        ack_out => IN8192OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN8192OUT65536_V_keep_V_U_apdone_blk);

    regslice_both_IN8192OUT65536_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN8192OUT65536_TSTRB,
        vld_in => IN8192OUT65536_TVALID,
        ack_in => regslice_both_IN8192OUT65536_V_strb_V_U_ack_in,
        data_out => IN8192OUT65536_TSTRB_int_regslice,
        vld_out => regslice_both_IN8192OUT65536_V_strb_V_U_vld_out,
        ack_out => IN8192OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN8192OUT65536_V_strb_V_U_apdone_blk);

    regslice_both_IN8192OUT65536_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN8192OUT65536_TLAST,
        vld_in => IN8192OUT65536_TVALID,
        ack_in => regslice_both_IN8192OUT65536_V_last_V_U_ack_in,
        data_out => IN8192OUT65536_TLAST_int_regslice,
        vld_out => regslice_both_IN8192OUT65536_V_last_V_U_vld_out,
        ack_out => IN8192OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN8192OUT65536_V_last_V_U_apdone_blk);

    regslice_both_IN16384OUT65536_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN16384OUT65536_TDATA,
        vld_in => IN16384OUT65536_TVALID,
        ack_in => regslice_both_IN16384OUT65536_V_data_V_U_ack_in,
        data_out => IN16384OUT65536_TDATA_int_regslice,
        vld_out => IN16384OUT65536_TVALID_int_regslice,
        ack_out => IN16384OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN16384OUT65536_V_data_V_U_apdone_blk);

    regslice_both_IN16384OUT65536_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN16384OUT65536_TKEEP,
        vld_in => IN16384OUT65536_TVALID,
        ack_in => regslice_both_IN16384OUT65536_V_keep_V_U_ack_in,
        data_out => IN16384OUT65536_TKEEP_int_regslice,
        vld_out => regslice_both_IN16384OUT65536_V_keep_V_U_vld_out,
        ack_out => IN16384OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN16384OUT65536_V_keep_V_U_apdone_blk);

    regslice_both_IN16384OUT65536_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN16384OUT65536_TSTRB,
        vld_in => IN16384OUT65536_TVALID,
        ack_in => regslice_both_IN16384OUT65536_V_strb_V_U_ack_in,
        data_out => IN16384OUT65536_TSTRB_int_regslice,
        vld_out => regslice_both_IN16384OUT65536_V_strb_V_U_vld_out,
        ack_out => IN16384OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN16384OUT65536_V_strb_V_U_apdone_blk);

    regslice_both_IN16384OUT65536_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN16384OUT65536_TLAST,
        vld_in => IN16384OUT65536_TVALID,
        ack_in => regslice_both_IN16384OUT65536_V_last_V_U_ack_in,
        data_out => IN16384OUT65536_TLAST_int_regslice,
        vld_out => regslice_both_IN16384OUT65536_V_last_V_U_vld_out,
        ack_out => IN16384OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN16384OUT65536_V_last_V_U_apdone_blk);

    regslice_both_IN32768OUT65536_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN32768OUT65536_TDATA,
        vld_in => IN32768OUT65536_TVALID,
        ack_in => regslice_both_IN32768OUT65536_V_data_V_U_ack_in,
        data_out => IN32768OUT65536_TDATA_int_regslice,
        vld_out => IN32768OUT65536_TVALID_int_regslice,
        ack_out => IN32768OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN32768OUT65536_V_data_V_U_apdone_blk);

    regslice_both_IN32768OUT65536_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN32768OUT65536_TKEEP,
        vld_in => IN32768OUT65536_TVALID,
        ack_in => regslice_both_IN32768OUT65536_V_keep_V_U_ack_in,
        data_out => IN32768OUT65536_TKEEP_int_regslice,
        vld_out => regslice_both_IN32768OUT65536_V_keep_V_U_vld_out,
        ack_out => IN32768OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN32768OUT65536_V_keep_V_U_apdone_blk);

    regslice_both_IN32768OUT65536_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN32768OUT65536_TSTRB,
        vld_in => IN32768OUT65536_TVALID,
        ack_in => regslice_both_IN32768OUT65536_V_strb_V_U_ack_in,
        data_out => IN32768OUT65536_TSTRB_int_regslice,
        vld_out => regslice_both_IN32768OUT65536_V_strb_V_U_vld_out,
        ack_out => IN32768OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN32768OUT65536_V_strb_V_U_apdone_blk);

    regslice_both_IN32768OUT65536_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN32768OUT65536_TLAST,
        vld_in => IN32768OUT65536_TVALID,
        ack_in => regslice_both_IN32768OUT65536_V_last_V_U_ack_in,
        data_out => IN32768OUT65536_TLAST_int_regslice,
        vld_out => regslice_both_IN32768OUT65536_V_last_V_U_vld_out,
        ack_out => IN32768OUT65536_TREADY_int_regslice,
        apdone_blk => regslice_both_IN32768OUT65536_V_last_V_U_apdone_blk);

    regslice_both_IN65536OUT262144_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN65536OUT262144_TDATA,
        vld_in => IN65536OUT262144_TVALID,
        ack_in => regslice_both_IN65536OUT262144_V_data_V_U_ack_in,
        data_out => IN65536OUT262144_TDATA_int_regslice,
        vld_out => IN65536OUT262144_TVALID_int_regslice,
        ack_out => IN65536OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN65536OUT262144_V_data_V_U_apdone_blk);

    regslice_both_IN65536OUT262144_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN65536OUT262144_TKEEP,
        vld_in => IN65536OUT262144_TVALID,
        ack_in => regslice_both_IN65536OUT262144_V_keep_V_U_ack_in,
        data_out => IN65536OUT262144_TKEEP_int_regslice,
        vld_out => regslice_both_IN65536OUT262144_V_keep_V_U_vld_out,
        ack_out => IN65536OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN65536OUT262144_V_keep_V_U_apdone_blk);

    regslice_both_IN65536OUT262144_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN65536OUT262144_TSTRB,
        vld_in => IN65536OUT262144_TVALID,
        ack_in => regslice_both_IN65536OUT262144_V_strb_V_U_ack_in,
        data_out => IN65536OUT262144_TSTRB_int_regslice,
        vld_out => regslice_both_IN65536OUT262144_V_strb_V_U_vld_out,
        ack_out => IN65536OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN65536OUT262144_V_strb_V_U_apdone_blk);

    regslice_both_IN65536OUT262144_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN65536OUT262144_TLAST,
        vld_in => IN65536OUT262144_TVALID,
        ack_in => regslice_both_IN65536OUT262144_V_last_V_U_ack_in,
        data_out => IN65536OUT262144_TLAST_int_regslice,
        vld_out => regslice_both_IN65536OUT262144_V_last_V_U_vld_out,
        ack_out => IN65536OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN65536OUT262144_V_last_V_U_apdone_blk);

    regslice_both_IN131072OUT262144_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN131072OUT262144_TDATA,
        vld_in => IN131072OUT262144_TVALID,
        ack_in => regslice_both_IN131072OUT262144_V_data_V_U_ack_in,
        data_out => IN131072OUT262144_TDATA_int_regslice,
        vld_out => IN131072OUT262144_TVALID_int_regslice,
        ack_out => IN131072OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN131072OUT262144_V_data_V_U_apdone_blk);

    regslice_both_IN131072OUT262144_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN131072OUT262144_TKEEP,
        vld_in => IN131072OUT262144_TVALID,
        ack_in => regslice_both_IN131072OUT262144_V_keep_V_U_ack_in,
        data_out => IN131072OUT262144_TKEEP_int_regslice,
        vld_out => regslice_both_IN131072OUT262144_V_keep_V_U_vld_out,
        ack_out => IN131072OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN131072OUT262144_V_keep_V_U_apdone_blk);

    regslice_both_IN131072OUT262144_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN131072OUT262144_TSTRB,
        vld_in => IN131072OUT262144_TVALID,
        ack_in => regslice_both_IN131072OUT262144_V_strb_V_U_ack_in,
        data_out => IN131072OUT262144_TSTRB_int_regslice,
        vld_out => regslice_both_IN131072OUT262144_V_strb_V_U_vld_out,
        ack_out => IN131072OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN131072OUT262144_V_strb_V_U_apdone_blk);

    regslice_both_IN131072OUT262144_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN131072OUT262144_TLAST,
        vld_in => IN131072OUT262144_TVALID,
        ack_in => regslice_both_IN131072OUT262144_V_last_V_U_ack_in,
        data_out => IN131072OUT262144_TLAST_int_regslice,
        vld_out => regslice_both_IN131072OUT262144_V_last_V_U_vld_out,
        ack_out => IN131072OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN131072OUT262144_V_last_V_U_apdone_blk);

    regslice_both_IN262144OUT262144_V_data_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN262144OUT262144_TDATA,
        vld_in => IN262144OUT262144_TVALID,
        ack_in => regslice_both_IN262144OUT262144_V_data_V_U_ack_in,
        data_out => IN262144OUT262144_TDATA_int_regslice,
        vld_out => IN262144OUT262144_TVALID_int_regslice,
        ack_out => IN262144OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN262144OUT262144_V_data_V_U_apdone_blk);

    regslice_both_IN262144OUT262144_V_keep_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN262144OUT262144_TKEEP,
        vld_in => IN262144OUT262144_TVALID,
        ack_in => regslice_both_IN262144OUT262144_V_keep_V_U_ack_in,
        data_out => IN262144OUT262144_TKEEP_int_regslice,
        vld_out => regslice_both_IN262144OUT262144_V_keep_V_U_vld_out,
        ack_out => IN262144OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN262144OUT262144_V_keep_V_U_apdone_blk);

    regslice_both_IN262144OUT262144_V_strb_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN262144OUT262144_TSTRB,
        vld_in => IN262144OUT262144_TVALID,
        ack_in => regslice_both_IN262144OUT262144_V_strb_V_U_ack_in,
        data_out => IN262144OUT262144_TSTRB_int_regslice,
        vld_out => regslice_both_IN262144OUT262144_V_strb_V_U_vld_out,
        ack_out => IN262144OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN262144OUT262144_V_strb_V_U_apdone_blk);

    regslice_both_IN262144OUT262144_V_last_V_U : component streamToData_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN262144OUT262144_TLAST,
        vld_in => IN262144OUT262144_TVALID,
        ack_in => regslice_both_IN262144OUT262144_V_last_V_U_ack_in,
        data_out => IN262144OUT262144_TLAST_int_regslice,
        vld_out => regslice_both_IN262144OUT262144_V_last_V_U_vld_out,
        ack_out => IN262144OUT262144_TREADY_int_regslice,
        apdone_blk => regslice_both_IN262144OUT262144_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    DacCounts_fu_401_p3 <= 
        select_ln69_fu_387_p3 when (or_ln69_fu_395_p2(0) = '1') else 
        or_ln_fu_379_p3;
    DacData <= std_logic_vector(IEEE.numeric_std.resize(unsigned(DacCounts_fu_401_p3),24));

    DacData_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            DacData_ap_vld <= ap_const_logic_1;
        else 
            DacData_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    IN1024OUT8192_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN1024OUT8192_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN1024OUT8192_TDATA_blk_n <= IN1024OUT8192_TVALID_int_regslice;
        else 
            IN1024OUT8192_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN1024OUT8192_TREADY <= regslice_both_IN1024OUT8192_V_data_V_U_ack_in;

    IN1024OUT8192_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN1024OUT8192_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN1024OUT8192_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN131072OUT262144_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN131072OUT262144_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN131072OUT262144_TDATA_blk_n <= IN131072OUT262144_TVALID_int_regslice;
        else 
            IN131072OUT262144_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN131072OUT262144_TREADY <= regslice_both_IN131072OUT262144_V_data_V_U_ack_in;

    IN131072OUT262144_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN131072OUT262144_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN131072OUT262144_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN16384OUT65536_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN16384OUT65536_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_4) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN16384OUT65536_TDATA_blk_n <= IN16384OUT65536_TVALID_int_regslice;
        else 
            IN16384OUT65536_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN16384OUT65536_TREADY <= regslice_both_IN16384OUT65536_V_data_V_U_ack_in;

    IN16384OUT65536_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN16384OUT65536_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN16384OUT65536_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN2048OUT8192_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN2048OUT8192_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN2048OUT8192_TDATA_blk_n <= IN2048OUT8192_TVALID_int_regslice;
        else 
            IN2048OUT8192_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN2048OUT8192_TREADY <= regslice_both_IN2048OUT8192_V_data_V_U_ack_in;

    IN2048OUT8192_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN2048OUT8192_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN2048OUT8192_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN262144OUT262144_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN262144OUT262144_TVALID_int_regslice)
    begin
        if ((not((interp = ap_const_lv4_5)) and not((interp = ap_const_lv4_4)) and not((interp = ap_const_lv4_3)) and not((interp = ap_const_lv4_2)) and not((interp = ap_const_lv4_1)) and not((interp = ap_const_lv4_0)) and not((interp = ap_const_lv4_7)) and not((interp = ap_const_lv4_6)) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN262144OUT262144_TDATA_blk_n <= IN262144OUT262144_TVALID_int_regslice;
        else 
            IN262144OUT262144_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN262144OUT262144_TREADY <= regslice_both_IN262144OUT262144_V_data_V_U_ack_in;

    IN262144OUT262144_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_predicate_op88_read_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1) and (ap_predicate_op88_read_state1 = ap_const_boolean_1))) then 
            IN262144OUT262144_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN262144OUT262144_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN32768OUT65536_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN32768OUT65536_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN32768OUT65536_TDATA_blk_n <= IN32768OUT65536_TVALID_int_regslice;
        else 
            IN32768OUT65536_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN32768OUT65536_TREADY <= regslice_both_IN32768OUT65536_V_data_V_U_ack_in;

    IN32768OUT65536_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN32768OUT65536_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN32768OUT65536_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN4096OUT8192_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN4096OUT8192_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN4096OUT8192_TDATA_blk_n <= IN4096OUT8192_TVALID_int_regslice;
        else 
            IN4096OUT8192_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN4096OUT8192_TREADY <= regslice_both_IN4096OUT8192_V_data_V_U_ack_in;

    IN4096OUT8192_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN4096OUT8192_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN4096OUT8192_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN65536OUT262144_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN65536OUT262144_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN65536OUT262144_TDATA_blk_n <= IN65536OUT262144_TVALID_int_regslice;
        else 
            IN65536OUT262144_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN65536OUT262144_TREADY <= regslice_both_IN65536OUT262144_V_data_V_U_ack_in;

    IN65536OUT262144_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN65536OUT262144_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN65536OUT262144_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    IN8192OUT65536_TDATA_blk_n_assign_proc : process(interp, ap_CS_fsm_state1, IN8192OUT65536_TVALID_int_regslice)
    begin
        if (((interp = ap_const_lv4_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IN8192OUT65536_TDATA_blk_n <= IN8192OUT65536_TVALID_int_regslice;
        else 
            IN8192OUT65536_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IN8192OUT65536_TREADY <= regslice_both_IN8192OUT65536_V_data_V_U_ack_in;

    IN8192OUT65536_TREADY_int_regslice_assign_proc : process(interp, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((interp = ap_const_lv4_3) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            IN8192OUT65536_TREADY_int_regslice <= ap_const_logic_1;
        else 
            IN8192OUT65536_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(interp, ap_predicate_op88_read_state1, IN1024OUT8192_TVALID_int_regslice, IN2048OUT8192_TVALID_int_regslice, IN4096OUT8192_TVALID_int_regslice, IN8192OUT65536_TVALID_int_regslice, IN16384OUT65536_TVALID_int_regslice, IN32768OUT65536_TVALID_int_regslice, IN65536OUT262144_TVALID_int_regslice, IN131072OUT262144_TVALID_int_regslice, IN262144OUT262144_TVALID_int_regslice)
    begin
                ap_block_state1 <= (((interp = ap_const_lv4_5) and (ap_const_logic_0 = IN32768OUT65536_TVALID_int_regslice)) or ((interp = ap_const_lv4_4) and (ap_const_logic_0 = IN16384OUT65536_TVALID_int_regslice)) or ((interp = ap_const_lv4_3) and (ap_const_logic_0 = IN8192OUT65536_TVALID_int_regslice)) or ((interp = ap_const_lv4_2) and (ap_const_logic_0 = IN4096OUT8192_TVALID_int_regslice)) or ((interp = ap_const_lv4_1) and (ap_const_logic_0 = IN2048OUT8192_TVALID_int_regslice)) or ((interp = ap_const_lv4_0) and (ap_const_logic_0 = IN1024OUT8192_TVALID_int_regslice)) or ((ap_const_logic_0 = IN262144OUT262144_TVALID_int_regslice) and (ap_predicate_op88_read_state1 = ap_const_boolean_1)) or ((interp = ap_const_lv4_7) and (ap_const_logic_0 = IN131072OUT262144_TVALID_int_regslice)) or ((interp = ap_const_lv4_6) and (ap_const_logic_0 = IN65536OUT262144_TVALID_int_regslice)));
    end process;


    ap_condition_122_assign_proc : process(interp)
    begin
                ap_condition_122 <= (not((interp = ap_const_lv4_5)) and not((interp = ap_const_lv4_4)) and not((interp = ap_const_lv4_3)) and not((interp = ap_const_lv4_2)) and not((interp = ap_const_lv4_1)) and not((interp = ap_const_lv4_0)) and not((interp = ap_const_lv4_7)) and not((interp = ap_const_lv4_6)));
    end process;


    ap_phi_mux_phi_ln30_phi_fu_284_p18_assign_proc : process(interp, ap_CS_fsm_state1, IN1024OUT8192_TDATA_int_regslice, IN2048OUT8192_TDATA_int_regslice, IN4096OUT8192_TDATA_int_regslice, IN8192OUT65536_TDATA_int_regslice, IN16384OUT65536_TDATA_int_regslice, IN32768OUT65536_TDATA_int_regslice, IN65536OUT262144_TDATA_int_regslice, IN131072OUT262144_TDATA_int_regslice, IN262144OUT262144_TDATA_int_regslice, ap_condition_122)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((interp = ap_const_lv4_0)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN1024OUT8192_TDATA_int_regslice;
            elsif ((interp = ap_const_lv4_1)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN2048OUT8192_TDATA_int_regslice;
            elsif ((interp = ap_const_lv4_2)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN4096OUT8192_TDATA_int_regslice;
            elsif ((interp = ap_const_lv4_3)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN8192OUT65536_TDATA_int_regslice;
            elsif ((interp = ap_const_lv4_4)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN16384OUT65536_TDATA_int_regslice;
            elsif ((interp = ap_const_lv4_5)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN32768OUT65536_TDATA_int_regslice;
            elsif ((interp = ap_const_lv4_6)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN65536OUT262144_TDATA_int_regslice;
            elsif ((interp = ap_const_lv4_7)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN131072OUT262144_TDATA_int_regslice;
            elsif ((ap_const_boolean_1 = ap_condition_122)) then 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= IN262144OUT262144_TDATA_int_regslice;
            else 
                ap_phi_mux_phi_ln30_phi_fu_284_p18 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_phi_ln30_phi_fu_284_p18 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_predicate_op88_read_state1_assign_proc : process(interp)
    begin
                ap_predicate_op88_read_state1 <= (not((interp = ap_const_lv4_5)) and not((interp = ap_const_lv4_4)) and not((interp = ap_const_lv4_3)) and not((interp = ap_const_lv4_2)) and not((interp = ap_const_lv4_1)) and not((interp = ap_const_lv4_0)) and not((interp = ap_const_lv4_7)) and not((interp = ap_const_lv4_6)));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    icmp_ln66_fu_367_p2 <= "1" when (signed(tmp_fu_357_p4) > signed(ap_const_lv4_0)) else "0";
    icmp_ln67_fu_373_p2 <= "1" when (signed(tmp_data_fu_349_p1) < signed(ap_const_lv23_780000)) else "0";
    or_ln69_fu_395_p2 <= (icmp_ln67_fu_373_p2 or icmp_ln66_fu_367_p2);
    or_ln_fu_379_p3 <= (ap_const_lv1_1 & trunc_ln23_fu_353_p1);
    select_ln69_fu_387_p3 <= 
        ap_const_lv21_17FFFF when (icmp_ln66_fu_367_p2(0) = '1') else 
        ap_const_lv21_180000;
    tmp_data_fu_349_p1 <= ap_phi_mux_phi_ln30_phi_fu_284_p18(23 - 1 downto 0);
    tmp_fu_357_p4 <= ap_phi_mux_phi_ln30_phi_fu_284_p18(22 downto 19);
    trunc_ln23_fu_353_p1 <= ap_phi_mux_phi_ln30_phi_fu_284_p18(20 - 1 downto 0);
end behav;
