// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ADCCountsToFloat_ADCCountsToFloat,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=29.802000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=20.403000,HLS_SYN_LAT=10,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1406,HLS_SYN_LUT=1893,HLS_VERSION=2023_2}" *)

module ADCCountsToFloat (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r,
        usr_gpio_o,
        usr_gpio_o_ap_vld,
        chanValid,
        ap_return,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] input_r;
output  [2:0] usr_gpio_o;
output   usr_gpio_o_ap_vld;
input  [0:0] chanValid;
output  [31:0] ap_return;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] usr_gpio_o;
reg usr_gpio_o_ap_vld;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] cal_step_address0;
reg    cal_step_ce0;
wire   [31:0] cal_step_q0;
wire   [2:0] cal_offset_address0;
reg    cal_offset_ce0;
wire   [31:0] cal_offset_q0;
wire   [31:0] iCurrentRange;
reg   [31:0] iCurrentRange_0_data_reg;
reg    iCurrentRange_0_vld_reg;
reg    iCurrentRange_0_ack_out;
reg   [31:0] iOverloadCount_1_data_reg;
reg    iOverloadCount_1_vld_reg;
reg    iOverloadCount_1_vld_in;
reg    iOverloadCount_1_ack_in;
reg   [31:0] OLValid_1_data_reg;
reg   [31:0] OLValid_1_data_in;
reg    OLValid_1_vld_reg;
reg    OLValid_1_vld_in;
reg    OLValid_1_ack_in;
wire   [31:0] reset;
wire   [31:0] pointOffset;
reg   [31:0] pointOffset_0_data_reg;
reg    pointOffset_0_vld_reg;
reg    pointOffset_0_ack_out;
reg   [31:0] gainChanged_1_data_reg;
reg    gainChanged_1_vld_reg;
reg    gainChanged_1_vld_in;
reg    gainChanged_1_ack_in;
reg   [31:0] status_1_data_reg;
reg    status_1_vld_reg;
reg    status_1_vld_in;
reg    status_1_ack_in;
reg   [2:0] iCurrentGain;
reg   [0:0] doOnce;
reg   [31:0] iCountdownGainChange;
reg   [31:0] iCurrentGainChanges;
reg   [31:0] iCurrentOverloads;
reg   [31:0] retVal;
reg   [31:0] grp_load_fu_354_p1;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_2_fu_602_p3;
wire   [31:0] grp_fu_341_p1;
reg   [31:0] reg_371;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state12;
wire  signed [31:0] sext_ln45_fu_443_p1;
wire    ap_CS_fsm_state2;
wire   [2:0] thisRange_fu_471_p1;
reg   [2:0] thisRange_reg_707;
wire    ap_CS_fsm_state3;
wire   [0:0] chanValid_assign_load_load_fu_599_p1;
reg   [0:0] tmp_2_reg_724;
wire   [31:0] grp_fu_337_p2;
reg   [31:0] mul1_reg_728;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [31:0] mul_reg_738;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg   [0:0] ap_phi_mux_doOnce_flag_1_phi_fu_262_p4;
wire   [0:0] icmp_ln67_fu_523_p2;
wire   [0:0] or_ln56_fu_511_p2;
wire   [0:0] xor_ln56_fu_503_p2;
reg   [0:0] ap_phi_mux_doOnce_new_1_phi_fu_272_p4;
wire   [31:0] add_ln69_fu_535_p2;
reg   [31:0] ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4;
reg   [0:0] ap_phi_mux_doOnce_flag_2_phi_fu_292_p4;
reg   [0:0] ap_phi_mux_doOnce_new_2_phi_fu_302_p4;
reg   [31:0] iCurrentGainChanges_loc_1_reg_310;
reg   [31:0] iCurrentOverloads_loc_0_reg_322;
wire   [0:0] tmp_1_fu_554_p3;
wire   [31:0] add_ln79_fu_573_p2;
wire   [63:0] zext_ln52_fu_425_p1;
wire   [63:0] zext_ln53_fu_457_p1;
wire   [31:0] select_ln56_fu_495_p3;
wire   [31:0] grp_fu_333_p2;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state16;
reg   [31:0] fADCOffset_fu_140;
wire   [31:0] bitcast_ln53_fu_462_p1;
reg   [31:0] fADCStepVal_fu_144;
wire   [31:0] bitcast_ln52_fu_448_p1;
reg   [31:0] input_assign_fu_148;
reg   [31:0] ap_sig_allocacmp_vInput_1;
reg   [0:0] chanValid_assign_fu_152;
reg   [31:0] vInput_fu_156;
wire   [31:0] zext_ln134_fu_614_p1;
wire   [31:0] vInput_3_fu_623_p2;
wire   [31:0] zext_ln86_fu_590_p1;
reg   [31:0] ap_sig_allocacmp_vInput_load_5;
reg   [31:0] ap_sig_allocacmp_vInput_load_6;
reg   [31:0] ap_sig_allocacmp_vInput_load;
reg   [31:0] vStatus_fu_160;
wire   [31:0] vStatus_1_fu_412_p3;
reg   [31:0] grp_fu_333_p0;
wire   [7:0] tmp_fu_402_p4;
wire   [7:0] trunc_ln_fu_433_p4;
wire   [0:0] icmp_ln56_fu_475_p2;
wire   [31:0] add_ln59_fu_489_p2;
wire   [23:0] vInput_2_fu_586_p1;
wire   [23:0] vInput_4_fu_610_p1;
reg    ap_block_state16;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 iCurrentRange_0_data_reg = 32'd0;
#0 iCurrentRange_0_vld_reg = 1'b0;
#0 iOverloadCount_1_data_reg = 32'd0;
#0 iOverloadCount_1_vld_reg = 1'b0;
#0 OLValid_1_data_reg = 32'd0;
#0 OLValid_1_vld_reg = 1'b0;
#0 pointOffset_0_data_reg = 32'd0;
#0 pointOffset_0_vld_reg = 1'b0;
#0 gainChanged_1_data_reg = 32'd0;
#0 gainChanged_1_vld_reg = 1'b0;
#0 status_1_data_reg = 32'd0;
#0 status_1_vld_reg = 1'b0;
#0 iCurrentGain = 3'd0;
#0 doOnce = 1'd1;
#0 iCountdownGainChange = 32'd0;
#0 iCurrentGainChanges = 32'd0;
#0 iCurrentOverloads = 32'd0;
#0 retVal = 32'd0;
#0 fADCOffset_fu_140 = 32'd0;
#0 fADCStepVal_fu_144 = 32'd0;
#0 input_assign_fu_148 = 32'd0;
#0 chanValid_assign_fu_152 = 1'd0;
#0 vInput_fu_156 = 32'd0;
#0 vStatus_fu_160 = 32'd0;
end

ADCCountsToFloat_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .iCurrentRange(iCurrentRange),
    .reset(reset),
    .cal_step_address0(cal_step_address0),
    .cal_step_ce0(cal_step_ce0),
    .cal_step_q0(cal_step_q0),
    .cal_offset_address0(cal_offset_address0),
    .cal_offset_ce0(cal_offset_ce0),
    .cal_offset_q0(cal_offset_q0),
    .iOverloadCount(iOverloadCount_1_data_reg),
    .iOverloadCount_ap_vld(iOverloadCount_1_vld_reg),
    .OLValid(OLValid_1_data_reg),
    .OLValid_ap_vld(OLValid_1_vld_reg),
    .pointOffset(pointOffset),
    .gainChanged(gainChanged_1_data_reg),
    .gainChanged_ap_vld(gainChanged_1_vld_reg),
    .status(status_1_data_reg),
    .status_ap_vld(status_1_vld_reg)
);

ADCCountsToFloat_fsub_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_3_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_333_p0),
    .din1(fADCOffset_fu_140),
    .ce(1'b1),
    .dout(grp_fu_333_p2)
);

ADCCountsToFloat_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(reg_371),
    .din1(fADCStepVal_fu_144),
    .ce(1'b1),
    .dout(grp_fu_337_p2)
);

ADCCountsToFloat_sitofp_32ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_2_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_load_fu_354_p1),
    .ce(1'b1),
    .dout(grp_fu_341_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == OLValid_1_vld_reg) & (1'b1 == OLValid_1_vld_in))) begin
        OLValid_1_vld_reg <= 1'b1;
    end else if (((1'b0 == OLValid_1_vld_in) & (1'b1 == 1'b1) & (1'b1 == OLValid_1_vld_reg))) begin
        OLValid_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (gainChanged_1_vld_in == 1'b1) & (gainChanged_1_vld_reg == 1'b0))) begin
        gainChanged_1_vld_reg <= 1'b1;
    end else if (((1'b1 == 1'b1) & (gainChanged_1_vld_in == 1'b0) & (gainChanged_1_vld_reg == 1'b1))) begin
        gainChanged_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln67_fu_523_p2 == 1'd0)) begin
            iCurrentGainChanges_loc_1_reg_310 <= ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4;
        end else if ((icmp_ln67_fu_523_p2 == 1'd1)) begin
            iCurrentGainChanges_loc_1_reg_310 <= iCurrentGainChanges;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((tmp_1_fu_554_p3 == 1'd1)) begin
            iCurrentOverloads_loc_0_reg_322 <= add_ln79_fu_573_p2;
        end else if ((tmp_1_fu_554_p3 == 1'd0)) begin
            iCurrentOverloads_loc_0_reg_322 <= iCurrentOverloads;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (iOverloadCount_1_vld_in == 1'b1) & (iOverloadCount_1_vld_reg == 1'b0))) begin
        iOverloadCount_1_vld_reg <= 1'b1;
    end else if (((1'b1 == 1'b1) & (iOverloadCount_1_vld_in == 1'b0) & (iOverloadCount_1_vld_reg == 1'b1))) begin
        iOverloadCount_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (status_1_vld_in == 1'b1) & (status_1_vld_reg == 1'b0))) begin
        status_1_vld_reg <= 1'b1;
    end else if (((1'b1 == 1'b1) & (status_1_vld_in == 1'b0) & (status_1_vld_reg == 1'b1))) begin
        status_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        vInput_fu_156 <= ap_sig_allocacmp_vInput_1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        vInput_fu_156 <= zext_ln86_fu_590_p1;
    end else if (((tmp_2_fu_602_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        vInput_fu_156 <= vInput_3_fu_623_p2;
    end else if (((tmp_2_fu_602_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        vInput_fu_156 <= zext_ln134_fu_614_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (1'b1 == OLValid_1_vld_in) & (1'b1 == OLValid_1_vld_reg)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == OLValid_1_vld_reg) & (1'b1 == OLValid_1_vld_in)))) begin
        OLValid_1_data_reg <= OLValid_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        chanValid_assign_fu_152 <= chanValid;
        input_assign_fu_148 <= input_r;
        vStatus_fu_160[31 : 24] <= vStatus_1_fu_412_p3[31 : 24];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        doOnce <= ap_phi_mux_doOnce_new_2_phi_fu_302_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fADCOffset_fu_140 <= bitcast_ln53_fu_462_p1;
        iCountdownGainChange <= select_ln56_fu_495_p3;
        thisRange_reg_707 <= thisRange_fu_471_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fADCStepVal_fu_144 <= bitcast_ln52_fu_448_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (gainChanged_1_vld_in == 1'b1) & (gainChanged_1_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (gainChanged_1_vld_in == 1'b1) & (gainChanged_1_vld_reg == 1'b0)))) begin
        gainChanged_1_data_reg <= iCurrentGainChanges_loc_1_reg_310;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln67_fu_523_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        iCurrentGain <= thisRange_fu_471_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln56_fu_511_p2 == 1'd1) & (icmp_ln67_fu_523_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        iCurrentGainChanges <= add_ln69_fu_535_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_554_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        iCurrentOverloads <= add_ln79_fu_573_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (iCurrentRange_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (iCurrentRange_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (iCurrentRange_0_vld_reg == 1'b0)))) begin
        iCurrentRange_0_data_reg <= iCurrentRange;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (iOverloadCount_1_vld_in == 1'b1) & (iOverloadCount_1_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (iOverloadCount_1_vld_in == 1'b1) & (iOverloadCount_1_vld_reg == 1'b0)))) begin
        iOverloadCount_1_data_reg <= iCurrentOverloads_loc_0_reg_322;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mul1_reg_728 <= grp_fu_337_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        mul_reg_738 <= grp_fu_337_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (pointOffset_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (pointOffset_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (pointOffset_0_vld_reg == 1'b0)))) begin
        pointOffset_0_data_reg <= pointOffset;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_371 <= grp_fu_341_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_2_reg_724 == 1'd1) & (1'b1 == ap_CS_fsm_state10)) | ((tmp_2_reg_724 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        retVal <= grp_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (status_1_vld_in == 1'b1) & (status_1_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (status_1_vld_in == 1'b1) & (status_1_vld_reg == 1'b0)))) begin
        status_1_data_reg <= sext_ln45_fu_443_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_2_reg_724 <= vInput_fu_156[32'd23];
    end
end

always @ (*) begin
    if (((1'b0 == OLValid_1_vld_reg) | ((1'b1 == 1'b1) & (1'b1 == OLValid_1_vld_reg)))) begin
        OLValid_1_ack_in = 1'b1;
    end else begin
        OLValid_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((chanValid_assign_load_load_fu_599_p1 == 1'd1)) begin
            OLValid_1_data_in = 32'd1;
        end else if ((chanValid_assign_load_load_fu_599_p1 == 1'd0)) begin
            OLValid_1_data_in = 32'd0;
        end else begin
            OLValid_1_data_in = 'bx;
        end
    end else begin
        OLValid_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((((chanValid_assign_load_load_fu_599_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((chanValid_assign_load_load_fu_599_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        OLValid_1_vld_in = 1'b1;
    end else begin
        OLValid_1_vld_in = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state16)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state16) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_523_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((or_ln56_fu_511_p2 == 1'd0)) begin
            ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 = xor_ln56_fu_503_p2;
        end else if ((or_ln56_fu_511_p2 == 1'd1)) begin
            ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 = 1'd1;
        end else begin
            ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln67_fu_523_p2 == 1'd0)) begin
            ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 = ap_phi_mux_doOnce_flag_1_phi_fu_262_p4;
        end else if ((icmp_ln67_fu_523_p2 == 1'd1)) begin
            ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 = xor_ln56_fu_503_p2;
        end else begin
            ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_523_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((or_ln56_fu_511_p2 == 1'd0)) begin
            ap_phi_mux_doOnce_new_1_phi_fu_272_p4 = 1'd1;
        end else if ((or_ln56_fu_511_p2 == 1'd1)) begin
            ap_phi_mux_doOnce_new_1_phi_fu_272_p4 = 1'd0;
        end else begin
            ap_phi_mux_doOnce_new_1_phi_fu_272_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_doOnce_new_1_phi_fu_272_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln67_fu_523_p2 == 1'd0)) begin
            ap_phi_mux_doOnce_new_2_phi_fu_302_p4 = ap_phi_mux_doOnce_new_1_phi_fu_272_p4;
        end else if ((icmp_ln67_fu_523_p2 == 1'd1)) begin
            ap_phi_mux_doOnce_new_2_phi_fu_302_p4 = 1'd1;
        end else begin
            ap_phi_mux_doOnce_new_2_phi_fu_302_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_doOnce_new_2_phi_fu_302_p4 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_523_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((or_ln56_fu_511_p2 == 1'd0)) begin
            ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 = iCurrentGainChanges;
        end else if ((or_ln56_fu_511_p2 == 1'd1)) begin
            ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 = add_ln69_fu_535_p2;
        end else begin
            ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state16) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ap_sig_allocacmp_vInput_1 = input_r;
    end else begin
        ap_sig_allocacmp_vInput_1 = input_assign_fu_148;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ap_sig_allocacmp_vInput_load = ap_sig_allocacmp_vInput_1;
    end else begin
        ap_sig_allocacmp_vInput_load = vInput_fu_156;
    end
end

always @ (*) begin
    if (((tmp_2_fu_602_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_sig_allocacmp_vInput_load_5 = zext_ln134_fu_614_p1;
    end else begin
        ap_sig_allocacmp_vInput_load_5 = vInput_fu_156;
    end
end

always @ (*) begin
    if (((tmp_2_fu_602_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_sig_allocacmp_vInput_load_6 = vInput_3_fu_623_p2;
    end else begin
        ap_sig_allocacmp_vInput_load_6 = vInput_fu_156;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cal_offset_ce0 = 1'b1;
    end else begin
        cal_offset_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        cal_step_ce0 = 1'b1;
    end else begin
        cal_step_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((gainChanged_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (gainChanged_1_vld_reg == 1'b1)))) begin
        gainChanged_1_ack_in = 1'b1;
    end else begin
        gainChanged_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gainChanged_1_vld_in = 1'b1;
    end else begin
        gainChanged_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_333_p0 = mul_reg_738;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_333_p0 = mul1_reg_728;
    end else begin
        grp_fu_333_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((tmp_2_fu_602_p3 == 1'd1)) begin
            grp_load_fu_354_p1 = ap_sig_allocacmp_vInput_load_6;
        end else if ((tmp_2_fu_602_p3 == 1'd0)) begin
            grp_load_fu_354_p1 = ap_sig_allocacmp_vInput_load_5;
        end else begin
            grp_load_fu_354_p1 = 'bx;
        end
    end else begin
        grp_load_fu_354_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state16) & (1'b1 == ap_CS_fsm_state16)))) begin
        iCurrentRange_0_ack_out = 1'b1;
    end else begin
        iCurrentRange_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((iOverloadCount_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (iOverloadCount_1_vld_reg == 1'b1)))) begin
        iOverloadCount_1_ack_in = 1'b1;
    end else begin
        iOverloadCount_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        iOverloadCount_1_vld_in = 1'b1;
    end else begin
        iOverloadCount_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state16) & (1'b1 == ap_CS_fsm_state16)))) begin
        pointOffset_0_ack_out = 1'b1;
    end else begin
        pointOffset_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((status_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (status_1_vld_reg == 1'b1)))) begin
        status_1_ack_in = 1'b1;
    end else begin
        status_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        status_1_vld_in = 1'b1;
    end else begin
        status_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((thisRange_reg_707 == 3'd7)) begin
            usr_gpio_o = 3'd7;
        end else if ((thisRange_reg_707 == 3'd0)) begin
            usr_gpio_o = 3'd0;
        end else if ((thisRange_reg_707 == 3'd1)) begin
            usr_gpio_o = 3'd1;
        end else if ((thisRange_reg_707 == 3'd2)) begin
            usr_gpio_o = 3'd4;
        end else if ((thisRange_reg_707 == 3'd3)) begin
            usr_gpio_o = 3'd2;
        end else if ((thisRange_reg_707 == 3'd4)) begin
            usr_gpio_o = 3'd5;
        end else if ((thisRange_reg_707 == 3'd5)) begin
            usr_gpio_o = 3'd3;
        end else if ((thisRange_reg_707 == 3'd6)) begin
            usr_gpio_o = 3'd6;
        end else begin
            usr_gpio_o = 'bx;
        end
    end else begin
        usr_gpio_o = 'bx;
    end
end

always @ (*) begin
    if ((((thisRange_reg_707 == 3'd7) & (1'b1 == ap_CS_fsm_state4)) | ((thisRange_reg_707 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((thisRange_reg_707 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((thisRange_reg_707 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((thisRange_reg_707 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((thisRange_reg_707 == 3'd4) & (1'b1 == ap_CS_fsm_state4)) | ((thisRange_reg_707 == 3'd5) & (1'b1 == ap_CS_fsm_state4)) | ((thisRange_reg_707 == 3'd6) & (1'b1 == ap_CS_fsm_state4)))) begin
        usr_gpio_o_ap_vld = 1'b1;
    end else begin
        usr_gpio_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((tmp_2_fu_602_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b0 == ap_block_state16) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_fu_489_p2 = (iCountdownGainChange + 32'd1);

assign add_ln69_fu_535_p2 = (iCurrentGainChanges + 32'd1);

assign add_ln79_fu_573_p2 = (iCurrentOverloads + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state16 = ((iOverloadCount_1_ack_in == 1'b0) | (1'b0 == OLValid_1_ack_in) | (status_1_ack_in == 1'b0) | (gainChanged_1_ack_in == 1'b0));
end

assign ap_return = retVal;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln52_fu_448_p1 = cal_step_q0;

assign bitcast_ln53_fu_462_p1 = cal_offset_q0;

assign cal_offset_address0 = zext_ln53_fu_457_p1;

assign cal_step_address0 = zext_ln52_fu_425_p1;

assign chanValid_assign_load_load_fu_599_p1 = chanValid_assign_fu_152;

assign icmp_ln56_fu_475_p2 = ((thisRange_fu_471_p1 == iCurrentGain) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_523_p2 = (($signed(select_ln56_fu_495_p3) < $signed(pointOffset_0_data_reg)) ? 1'b1 : 1'b0);

assign or_ln56_fu_511_p2 = (xor_ln56_fu_503_p2 | doOnce);

assign select_ln56_fu_495_p3 = ((icmp_ln56_fu_475_p2[0:0] == 1'b1) ? 32'd0 : add_ln59_fu_489_p2);

assign sext_ln45_fu_443_p1 = $signed(trunc_ln_fu_433_p4);

assign thisRange_fu_471_p1 = iCurrentRange_0_data_reg[2:0];

assign tmp_1_fu_554_p3 = vInput_fu_156[32'd27];

assign tmp_2_fu_602_p3 = vInput_fu_156[32'd23];

assign tmp_fu_402_p4 = {{ap_sig_allocacmp_vInput_load[31:24]}};

assign trunc_ln_fu_433_p4 = {{vStatus_fu_160[31:24]}};

assign vInput_2_fu_586_p1 = vInput_fu_156[23:0];

assign vInput_3_fu_623_p2 = (vInput_fu_156 | 32'd4278190080);

assign vInput_4_fu_610_p1 = vInput_fu_156[23:0];

assign vStatus_1_fu_412_p3 = {{tmp_fu_402_p4}, {24'd0}};

assign xor_ln56_fu_503_p2 = (icmp_ln56_fu_475_p2 ^ 1'd1);

assign zext_ln134_fu_614_p1 = vInput_4_fu_610_p1;

assign zext_ln52_fu_425_p1 = iCurrentGain;

assign zext_ln53_fu_457_p1 = iCurrentGain;

assign zext_ln86_fu_590_p1 = vInput_2_fu_586_p1;

always @ (posedge ap_clk) begin
    vStatus_fu_160[23:0] <= 24'b000000000000000000000000;
end

endmodule //ADCCountsToFloat
