-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tacho is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    en : IN STD_LOGIC_VECTOR (0 downto 0);
    trig : IN STD_LOGIC_VECTOR (0 downto 0);
    avg : IN STD_LOGIC_VECTOR (7 downto 0);
    out_data : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of tacho is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "tacho_tacho,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.205200,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=512,HLS_SYN_LUT=834,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_3E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111101000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_F4241 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000011110100001001000001";
    constant ap_const_lv32_FA0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000111110100000";
    constant ap_const_lv32_BB8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000101110111000";
    constant ap_const_lv32_320 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100100000";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal en_0_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal en_0_vld_reg : STD_LOGIC := '0';
    signal en_0_ack_out : STD_LOGIC;
    signal trig_0_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal trig_0_vld_reg : STD_LOGIC := '0';
    signal trig_0_ack_out : STD_LOGIC;
    signal avg_0_data_reg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal avg_0_vld_reg : STD_LOGIC := '0';
    signal avg_0_ack_out : STD_LOGIC;
    signal out_data_1_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_data_1_data_in : STD_LOGIC_VECTOR (31 downto 0);
    signal out_data_1_vld_reg : STD_LOGIC := '0';
    signal out_data_1_vld_in : STD_LOGIC;
    signal out_data_1_ack_in : STD_LOGIC;
    signal pre_trig : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal NextState : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal error : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    signal counter1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal trig_cnt : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal counter2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_486_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal NextState_load_load_fu_525_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal t_trig_fu_513_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_fu_88_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_trig_reg_652 : STD_LOGIC_VECTOR (0 downto 0);
    signal NextState_load_reg_658 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln65_fu_546_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_reg_671 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln73_fu_552_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln73_reg_675 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln57_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln57_fu_571_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln62_fu_579_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln88_fu_587_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln88_reg_697 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln92_reg_706 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_NextState_flag_4_phi_fu_105_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal NextState_flag_4_reg_101 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_phi_mux_error_loc_2_phi_fu_119_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal error_loc_2_reg_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_counter1_new_2_phi_fu_130_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter1_new_2_reg_127 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_trig_cnt_flag_2_phi_fu_144_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal trig_cnt_flag_2_reg_139 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_trig_cnt_new_2_phi_fu_159_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal trig_cnt_new_2_reg_155 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_NextState_flag_7_phi_fu_172_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal NextState_flag_7_reg_168 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_error_loc_5_phi_fu_186_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal error_loc_5_reg_183 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_trig_cnt_flag_4_phi_fu_199_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal trig_cnt_flag_4_reg_194 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_trig_cnt_new_4_phi_fu_214_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal trig_cnt_new_4_reg_210 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_counter2_new_3_phi_fu_226_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter2_new_3_reg_223 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_NextState_flag_9_phi_fu_238_p12 : STD_LOGIC_VECTOR (0 downto 0);
    signal NextState_flag_9_reg_235 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_NextState_new_9_phi_fu_260_p12 : STD_LOGIC_VECTOR (1 downto 0);
    signal NextState_new_9_reg_256 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_error_flag_7_phi_fu_283_p12 : STD_LOGIC_VECTOR (0 downto 0);
    signal error_flag_7_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_error_new_7_phi_fu_307_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal error_new_7_reg_303 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln81_fu_594_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln104_fu_602_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_error_loc_7_phi_fu_327_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal error_loc_7_reg_323 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_counter1_flag_7_phi_fu_348_p12 : STD_LOGIC_VECTOR (0 downto 0);
    signal counter1_flag_7_reg_344 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_counter1_new_7_phi_fu_372_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter1_new_7_reg_367 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_trig_cnt_flag_5_phi_fu_396_p12 : STD_LOGIC_VECTOR (0 downto 0);
    signal trig_cnt_flag_5_reg_392 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_trig_cnt_new_5_phi_fu_419_p12 : STD_LOGIC_VECTOR (7 downto 0);
    signal trig_cnt_new_5_reg_415 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_counter2_flag_4_phi_fu_442_p12 : STD_LOGIC_VECTOR (0 downto 0);
    signal counter2_flag_4_reg_438 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_counter2_new_4_phi_fu_466_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter2_new_4_reg_462 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln32_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln57_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_condition_387 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    NextState_flag_4_reg_101_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                NextState_flag_4_reg_101 <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (t_trig_fu_513_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (t_trig_fu_513_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)))) then 
                NextState_flag_4_reg_101 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    NextState_flag_7_reg_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                NextState_flag_7_reg_168 <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_0)))) then 
                NextState_flag_7_reg_168 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    NextState_flag_9_reg_235_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                NextState_flag_9_reg_235 <= ap_phi_mux_NextState_flag_7_phi_fu_172_p6;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                NextState_flag_9_reg_235 <= ap_const_lv1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                NextState_flag_9_reg_235 <= ap_phi_mux_NextState_flag_4_phi_fu_105_p6;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1))) then 
                NextState_flag_9_reg_235 <= en_0_data_reg;
            elsif (((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                NextState_flag_9_reg_235 <= or_ln57_fu_565_p2;
            end if; 
        end if;
    end process;

    NextState_new_9_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                NextState_new_9_reg_256 <= ap_const_lv2_2;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                NextState_new_9_reg_256 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                NextState_new_9_reg_256 <= ap_const_lv2_3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1))) then 
                NextState_new_9_reg_256 <= ap_const_lv2_1;
            elsif (((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                NextState_new_9_reg_256 <= select_ln57_fu_571_p3;
            end if; 
        end if;
    end process;

    avg_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    counter1_flag_7_reg_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                counter1_flag_7_reg_344 <= ap_phi_mux_NextState_flag_7_phi_fu_172_p6;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                counter1_flag_7_reg_344 <= ap_const_lv1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1))) then 
                counter1_flag_7_reg_344 <= ap_const_lv1_0;
            elsif (((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                counter1_flag_7_reg_344 <= t_trig_fu_513_p2;
            end if; 
        end if;
    end process;

    counter1_new_2_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                counter1_new_2_reg_127 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (t_trig_fu_513_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (t_trig_fu_513_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)))) then 
                counter1_new_2_reg_127 <= add_ln65_fu_546_p2;
            end if; 
        end if;
    end process;

    counter1_new_7_reg_367_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                counter1_new_7_reg_367 <= ap_phi_mux_counter1_new_2_phi_fu_130_p6;
            elsif ((((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                counter1_new_7_reg_367 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    counter2_flag_4_reg_438_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                counter2_flag_4_reg_438 <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                counter2_flag_4_reg_438 <= ap_phi_mux_NextState_flag_4_phi_fu_105_p6;
            elsif ((((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1)))) then 
                counter2_flag_4_reg_438 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    counter2_new_3_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                counter2_new_3_reg_223 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_0)))) then 
                counter2_new_3_reg_223 <= add_ln88_fu_587_p2;
            end if; 
        end if;
    end process;

    counter2_new_4_reg_462_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                counter2_new_4_reg_462 <= ap_phi_mux_counter2_new_3_phi_fu_226_p6;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                counter2_new_4_reg_462 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    en_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    error_flag_7_reg_279_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_flag_7_reg_279 <= ap_phi_mux_NextState_flag_7_phi_fu_172_p6;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_flag_7_reg_279 <= ap_phi_mux_NextState_flag_4_phi_fu_105_p6;
            elsif ((((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1)))) then 
                error_flag_7_reg_279 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    error_loc_2_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_loc_2_reg_116 <= add_ln73_reg_675;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (t_trig_fu_513_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (t_trig_fu_513_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)))) then 
                error_loc_2_reg_116 <= error;
            end if; 
        end if;
    end process;

    error_loc_5_reg_183_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_loc_5_reg_183 <= add_ln88_reg_697;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_0)))) then 
                error_loc_5_reg_183 <= error;
            end if; 
        end if;
    end process;

    error_loc_7_reg_323_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_loc_7_reg_323 <= add_ln104_fu_602_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_loc_7_reg_323 <= ap_phi_mux_error_loc_5_phi_fu_186_p6;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_loc_7_reg_323 <= add_ln81_fu_594_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_loc_7_reg_323 <= ap_phi_mux_error_loc_2_phi_fu_119_p6;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1))) then 
                error_loc_7_reg_323 <= ap_const_lv32_3E8;
            elsif (((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                error_loc_7_reg_323 <= select_ln62_fu_579_p3;
            end if; 
        end if;
    end process;

    error_new_7_reg_303_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_new_7_reg_303 <= add_ln104_fu_602_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_new_7_reg_303 <= add_ln88_reg_697;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_new_7_reg_303 <= add_ln81_fu_594_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                error_new_7_reg_303 <= ap_phi_mux_error_loc_2_phi_fu_119_p6;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1))) then 
                error_new_7_reg_303 <= ap_const_lv32_3E8;
            elsif (((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                error_new_7_reg_303 <= select_ln62_fu_579_p3;
            end if; 
        end if;
    end process;

    out_data_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    trig_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    trig_cnt_flag_2_reg_139_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (t_trig_fu_513_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)))) then 
                trig_cnt_flag_2_reg_139 <= ap_const_lv1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (t_trig_fu_513_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1))) then 
                trig_cnt_flag_2_reg_139 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    trig_cnt_flag_4_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_1)))) then 
                trig_cnt_flag_4_reg_194 <= ap_const_lv1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_0))) then 
                trig_cnt_flag_4_reg_194 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    trig_cnt_flag_5_reg_392_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                trig_cnt_flag_5_reg_392 <= ap_phi_mux_trig_cnt_flag_4_phi_fu_199_p6;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                trig_cnt_flag_5_reg_392 <= ap_phi_mux_trig_cnt_flag_2_phi_fu_144_p6;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv2_0 = NextState_load_load_fu_525_p1))) then 
                trig_cnt_flag_5_reg_392 <= ap_const_lv1_0;
            elsif (((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                trig_cnt_flag_5_reg_392 <= t_trig_fu_513_p2;
            end if; 
        end if;
    end process;

    trig_cnt_new_2_reg_155_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (t_trig_fu_513_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1))) then 
                trig_cnt_new_2_reg_155 <= grp_fu_486_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                trig_cnt_new_2_reg_155 <= avg_0_data_reg;
            end if; 
        end if;
    end process;

    trig_cnt_new_4_reg_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_1))) then 
                trig_cnt_new_4_reg_210 <= grp_fu_486_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1))) then 
                trig_cnt_new_4_reg_210 <= avg_0_data_reg;
            end if; 
        end if;
    end process;

    trig_cnt_new_5_reg_415_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                trig_cnt_new_5_reg_415 <= ap_phi_mux_trig_cnt_new_4_phi_fu_214_p6;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658) and (out_data_1_ack_in = ap_const_logic_1)))) then 
                trig_cnt_new_5_reg_415 <= ap_phi_mux_trig_cnt_new_2_phi_fu_159_p6;
            elsif (((ap_const_lv2_1 = NextState_load_load_fu_525_p1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                trig_cnt_new_5_reg_415 <= avg_0_data_reg;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_NextState_flag_9_phi_fu_238_p12 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then
                NextState <= ap_phi_mux_NextState_new_9_phi_fu_260_p12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                NextState_load_reg_658 <= NextState;
                add_ln73_reg_675 <= add_ln73_fu_552_p2;
                add_ln88_reg_697 <= add_ln88_fu_587_p2;
                icmp_ln69_reg_671 <= grp_fu_491_p2;
                icmp_ln92_reg_706 <= grp_fu_491_p2;
                pre_trig <= trig_0_data_reg;
                t_trig_reg_652 <= t_trig_fu_513_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (avg_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (avg_0_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (avg_0_vld_reg = ap_const_logic_0)))) then
                avg_0_data_reg <= avg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_counter1_flag_7_phi_fu_348_p12 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then
                counter1 <= ap_phi_mux_counter1_new_7_phi_fu_372_p12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_counter2_flag_4_phi_fu_442_p12 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then
                counter2 <= ap_phi_mux_counter2_new_4_phi_fu_466_p12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (en_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (en_0_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (en_0_vld_reg = ap_const_logic_0)))) then
                en_0_data_reg <= en;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_error_flag_7_phi_fu_283_p12 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then
                error <= ap_phi_mux_error_new_7_phi_fu_307_p12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (out_data_1_vld_in = ap_const_logic_1) and (out_data_1_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (out_data_1_vld_in = ap_const_logic_1) and (out_data_1_vld_reg = ap_const_logic_0)))) then
                out_data_1_data_reg <= out_data_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (trig_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (trig_0_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (trig_0_vld_reg = ap_const_logic_0)))) then
                trig_0_data_reg <= trig;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_trig_cnt_flag_5_phi_fu_396_p12 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then
                trig_cnt <= ap_phi_mux_trig_cnt_new_5_phi_fu_419_p12;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, out_data_1_ack_in, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    NextState_load_load_fu_525_p1 <= NextState;
    add_ln104_fu_602_p2 <= std_logic_vector(unsigned(ap_phi_mux_error_loc_5_phi_fu_186_p6) + unsigned(ap_const_lv32_190));
    add_ln65_fu_546_p2 <= std_logic_vector(unsigned(counter1) + unsigned(ap_const_lv32_1));
    add_ln73_fu_552_p2 <= std_logic_vector(unsigned(counter1) + unsigned(ap_const_lv32_F4241));
    add_ln81_fu_594_p2 <= std_logic_vector(unsigned(ap_phi_mux_error_loc_2_phi_fu_119_p6) + unsigned(ap_const_lv32_320));
    add_ln88_fu_587_p2 <= std_logic_vector(unsigned(counter2) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(out_data_1_ack_in)
    begin
        if ((out_data_1_ack_in = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_387_assign_proc : process(ap_CS_fsm_state2, t_trig_fu_513_p2, grp_fu_491_p2)
    begin
                ap_condition_387 <= ((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_1) and (t_trig_fu_513_p2 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(out_data_1_ack_in, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_NextState_flag_4_phi_fu_105_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, icmp_ln69_reg_671, NextState_flag_4_reg_101, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_NextState_flag_4_phi_fu_105_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_NextState_flag_4_phi_fu_105_p6 <= NextState_flag_4_reg_101;
        end if; 
    end process;


    ap_phi_mux_NextState_flag_7_phi_fu_172_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, icmp_ln92_reg_706, ap_CS_fsm_state3, NextState_flag_7_reg_168)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_NextState_flag_7_phi_fu_172_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_NextState_flag_7_phi_fu_172_p6 <= NextState_flag_7_reg_168;
        end if; 
    end process;


    ap_phi_mux_NextState_flag_9_phi_fu_238_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_phi_mux_NextState_flag_4_phi_fu_105_p6, ap_CS_fsm_state3, ap_phi_mux_NextState_flag_7_phi_fu_172_p6, NextState_flag_9_reg_235)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_NextState_flag_9_phi_fu_238_p12 <= ap_phi_mux_NextState_flag_7_phi_fu_172_p6;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_NextState_flag_9_phi_fu_238_p12 <= ap_const_lv1_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_NextState_flag_9_phi_fu_238_p12 <= ap_phi_mux_NextState_flag_4_phi_fu_105_p6;
        else 
            ap_phi_mux_NextState_flag_9_phi_fu_238_p12 <= NextState_flag_9_reg_235;
        end if; 
    end process;


    ap_phi_mux_NextState_new_9_phi_fu_260_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_CS_fsm_state3, NextState_new_9_reg_256)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_NextState_new_9_phi_fu_260_p12 <= ap_const_lv2_2;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_NextState_new_9_phi_fu_260_p12 <= ap_const_lv2_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_NextState_new_9_phi_fu_260_p12 <= ap_const_lv2_3;
        else 
            ap_phi_mux_NextState_new_9_phi_fu_260_p12 <= NextState_new_9_reg_256;
        end if; 
    end process;


    ap_phi_mux_counter1_flag_7_phi_fu_348_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_CS_fsm_state3, ap_phi_mux_NextState_flag_7_phi_fu_172_p6, counter1_flag_7_reg_344)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_counter1_flag_7_phi_fu_348_p12 <= ap_phi_mux_NextState_flag_7_phi_fu_172_p6;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_counter1_flag_7_phi_fu_348_p12 <= ap_const_lv1_1;
        else 
            ap_phi_mux_counter1_flag_7_phi_fu_348_p12 <= counter1_flag_7_reg_344;
        end if; 
    end process;


    ap_phi_mux_counter1_new_2_phi_fu_130_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, icmp_ln69_reg_671, ap_CS_fsm_state3, counter1_new_2_reg_127)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_counter1_new_2_phi_fu_130_p6 <= ap_const_lv32_0;
        else 
            ap_phi_mux_counter1_new_2_phi_fu_130_p6 <= counter1_new_2_reg_127;
        end if; 
    end process;


    ap_phi_mux_counter1_new_7_phi_fu_372_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_CS_fsm_state3, ap_phi_mux_counter1_new_2_phi_fu_130_p6, counter1_new_7_reg_367)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658)))) then 
            ap_phi_mux_counter1_new_7_phi_fu_372_p12 <= ap_const_lv32_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_counter1_new_7_phi_fu_372_p12 <= ap_phi_mux_counter1_new_2_phi_fu_130_p6;
        else 
            ap_phi_mux_counter1_new_7_phi_fu_372_p12 <= counter1_new_7_reg_367;
        end if; 
    end process;


    ap_phi_mux_counter2_flag_4_phi_fu_442_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_phi_mux_NextState_flag_4_phi_fu_105_p6, ap_CS_fsm_state3, counter2_flag_4_reg_438)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658)))) then 
            ap_phi_mux_counter2_flag_4_phi_fu_442_p12 <= ap_const_lv1_1;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_counter2_flag_4_phi_fu_442_p12 <= ap_phi_mux_NextState_flag_4_phi_fu_105_p6;
        else 
            ap_phi_mux_counter2_flag_4_phi_fu_442_p12 <= counter2_flag_4_reg_438;
        end if; 
    end process;


    ap_phi_mux_counter2_new_3_phi_fu_226_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, icmp_ln92_reg_706, ap_CS_fsm_state3, counter2_new_3_reg_223)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_counter2_new_3_phi_fu_226_p6 <= ap_const_lv32_0;
        else 
            ap_phi_mux_counter2_new_3_phi_fu_226_p6 <= counter2_new_3_reg_223;
        end if; 
    end process;


    ap_phi_mux_counter2_new_4_phi_fu_466_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_CS_fsm_state3, ap_phi_mux_counter2_new_3_phi_fu_226_p6, counter2_new_4_reg_462)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658)))) then 
            ap_phi_mux_counter2_new_4_phi_fu_466_p12 <= ap_phi_mux_counter2_new_3_phi_fu_226_p6;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_counter2_new_4_phi_fu_466_p12 <= ap_const_lv32_0;
        else 
            ap_phi_mux_counter2_new_4_phi_fu_466_p12 <= counter2_new_4_reg_462;
        end if; 
    end process;


    ap_phi_mux_error_flag_7_phi_fu_283_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_phi_mux_NextState_flag_4_phi_fu_105_p6, ap_CS_fsm_state3, ap_phi_mux_NextState_flag_7_phi_fu_172_p6, error_flag_7_reg_279)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_error_flag_7_phi_fu_283_p12 <= ap_phi_mux_NextState_flag_7_phi_fu_172_p6;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_error_flag_7_phi_fu_283_p12 <= ap_const_lv1_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_error_flag_7_phi_fu_283_p12 <= ap_phi_mux_NextState_flag_4_phi_fu_105_p6;
        else 
            ap_phi_mux_error_flag_7_phi_fu_283_p12 <= error_flag_7_reg_279;
        end if; 
    end process;


    ap_phi_mux_error_loc_2_phi_fu_119_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, icmp_ln69_reg_671, add_ln73_reg_675, ap_CS_fsm_state3, error_loc_2_reg_116)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_error_loc_2_phi_fu_119_p6 <= add_ln73_reg_675;
        else 
            ap_phi_mux_error_loc_2_phi_fu_119_p6 <= error_loc_2_reg_116;
        end if; 
    end process;


    ap_phi_mux_error_loc_5_phi_fu_186_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, add_ln88_reg_697, icmp_ln92_reg_706, ap_CS_fsm_state3, error_loc_5_reg_183)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_error_loc_5_phi_fu_186_p6 <= add_ln88_reg_697;
        else 
            ap_phi_mux_error_loc_5_phi_fu_186_p6 <= error_loc_5_reg_183;
        end if; 
    end process;


    ap_phi_mux_error_loc_7_phi_fu_327_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_CS_fsm_state3, ap_phi_mux_error_loc_2_phi_fu_119_p6, ap_phi_mux_error_loc_5_phi_fu_186_p6, add_ln81_fu_594_p2, add_ln104_fu_602_p2, error_loc_7_reg_323)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
                ap_phi_mux_error_loc_7_phi_fu_327_p12 <= add_ln104_fu_602_p2;
            elsif (((grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
                ap_phi_mux_error_loc_7_phi_fu_327_p12 <= ap_phi_mux_error_loc_5_phi_fu_186_p6;
            elsif (((grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
                ap_phi_mux_error_loc_7_phi_fu_327_p12 <= add_ln81_fu_594_p2;
            elsif (((grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
                ap_phi_mux_error_loc_7_phi_fu_327_p12 <= ap_phi_mux_error_loc_2_phi_fu_119_p6;
            else 
                ap_phi_mux_error_loc_7_phi_fu_327_p12 <= error_loc_7_reg_323;
            end if;
        else 
            ap_phi_mux_error_loc_7_phi_fu_327_p12 <= error_loc_7_reg_323;
        end if; 
    end process;


    ap_phi_mux_error_new_7_phi_fu_307_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, add_ln88_reg_697, ap_CS_fsm_state3, ap_phi_mux_error_loc_2_phi_fu_119_p6, error_new_7_reg_303, add_ln81_fu_594_p2, add_ln104_fu_602_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if (((grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
                ap_phi_mux_error_new_7_phi_fu_307_p12 <= add_ln104_fu_602_p2;
            elsif (((grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
                ap_phi_mux_error_new_7_phi_fu_307_p12 <= add_ln88_reg_697;
            elsif (((grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
                ap_phi_mux_error_new_7_phi_fu_307_p12 <= add_ln81_fu_594_p2;
            elsif (((grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
                ap_phi_mux_error_new_7_phi_fu_307_p12 <= ap_phi_mux_error_loc_2_phi_fu_119_p6;
            else 
                ap_phi_mux_error_new_7_phi_fu_307_p12 <= error_new_7_reg_303;
            end if;
        else 
            ap_phi_mux_error_new_7_phi_fu_307_p12 <= error_new_7_reg_303;
        end if; 
    end process;


    ap_phi_mux_trig_cnt_flag_2_phi_fu_144_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, icmp_ln69_reg_671, ap_CS_fsm_state3, trig_cnt_flag_2_reg_139)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_trig_cnt_flag_2_phi_fu_144_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_trig_cnt_flag_2_phi_fu_144_p6 <= trig_cnt_flag_2_reg_139;
        end if; 
    end process;


    ap_phi_mux_trig_cnt_flag_4_phi_fu_199_p6_assign_proc : process(t_trig_reg_652, NextState_load_reg_658, icmp_ln92_reg_706, ap_CS_fsm_state3, trig_cnt_flag_4_reg_194)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_trig_cnt_flag_4_phi_fu_199_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_trig_cnt_flag_4_phi_fu_199_p6 <= trig_cnt_flag_4_reg_194;
        end if; 
    end process;


    ap_phi_mux_trig_cnt_flag_5_phi_fu_396_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_CS_fsm_state3, ap_phi_mux_trig_cnt_flag_2_phi_fu_144_p6, ap_phi_mux_trig_cnt_flag_4_phi_fu_199_p6, trig_cnt_flag_5_reg_392)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658)))) then 
            ap_phi_mux_trig_cnt_flag_5_phi_fu_396_p12 <= ap_phi_mux_trig_cnt_flag_4_phi_fu_199_p6;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_trig_cnt_flag_5_phi_fu_396_p12 <= ap_phi_mux_trig_cnt_flag_2_phi_fu_144_p6;
        else 
            ap_phi_mux_trig_cnt_flag_5_phi_fu_396_p12 <= trig_cnt_flag_5_reg_392;
        end if; 
    end process;


    ap_phi_mux_trig_cnt_new_2_phi_fu_159_p6_assign_proc : process(avg_0_data_reg, t_trig_reg_652, NextState_load_reg_658, icmp_ln69_reg_671, ap_CS_fsm_state3, trig_cnt_new_2_reg_155)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln69_reg_671 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658))) then 
            ap_phi_mux_trig_cnt_new_2_phi_fu_159_p6 <= avg_0_data_reg;
        else 
            ap_phi_mux_trig_cnt_new_2_phi_fu_159_p6 <= trig_cnt_new_2_reg_155;
        end if; 
    end process;


    ap_phi_mux_trig_cnt_new_4_phi_fu_214_p6_assign_proc : process(avg_0_data_reg, t_trig_reg_652, NextState_load_reg_658, icmp_ln92_reg_706, ap_CS_fsm_state3, trig_cnt_new_4_reg_210)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln92_reg_706 = ap_const_lv1_1) and (t_trig_reg_652 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658))) then 
            ap_phi_mux_trig_cnt_new_4_phi_fu_214_p6 <= avg_0_data_reg;
        else 
            ap_phi_mux_trig_cnt_new_4_phi_fu_214_p6 <= trig_cnt_new_4_reg_210;
        end if; 
    end process;


    ap_phi_mux_trig_cnt_new_5_phi_fu_419_p12_assign_proc : process(grp_read_fu_88_p2, NextState_load_reg_658, ap_CS_fsm_state3, ap_phi_mux_trig_cnt_new_2_phi_fu_159_p6, ap_phi_mux_trig_cnt_new_4_phi_fu_214_p6, trig_cnt_new_5_reg_415)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_3 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_reg_658)))) then 
            ap_phi_mux_trig_cnt_new_5_phi_fu_419_p12 <= ap_phi_mux_trig_cnt_new_4_phi_fu_214_p6;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_0) and (ap_const_lv2_2 = NextState_load_reg_658)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_fu_88_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_reg_658)))) then 
            ap_phi_mux_trig_cnt_new_5_phi_fu_419_p12 <= ap_phi_mux_trig_cnt_new_2_phi_fu_159_p6;
        else 
            ap_phi_mux_trig_cnt_new_5_phi_fu_419_p12 <= trig_cnt_new_5_reg_415;
        end if; 
    end process;


    ap_ready_assign_proc : process(out_data_1_ack_in, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_phi_mux_error_loc_7_phi_fu_327_p12;

    avg_0_ack_out_assign_proc : process(out_data_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1)))) then 
            avg_0_ack_out <= ap_const_logic_1;
        else 
            avg_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    en_0_ack_out_assign_proc : process(out_data_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1)))) then 
            en_0_ack_out <= ap_const_logic_1;
        else 
            en_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_486_p2 <= std_logic_vector(unsigned(trig_cnt) + unsigned(ap_const_lv8_FF));
    grp_fu_491_p2 <= "1" when (grp_fu_486_p2 = ap_const_lv8_0) else "0";
    grp_read_fu_88_p2 <= en_0_data_reg;
    or_ln57_fu_565_p2 <= (xor_ln57_fu_559_p2 or t_trig_fu_513_p2);
    out_data <= out_data_1_data_reg;

    out_data_1_ack_in_assign_proc : process(out_data_1_vld_reg)
    begin
        if (((out_data_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (out_data_1_vld_reg = ap_const_logic_1)))) then 
            out_data_1_ack_in <= ap_const_logic_1;
        else 
            out_data_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    out_data_1_data_in_assign_proc : process(NextState_load_load_fu_525_p1, add_ln73_fu_552_p2, add_ln88_fu_587_p2, ap_condition_387)
    begin
        if ((ap_const_boolean_1 = ap_condition_387)) then
            if ((ap_const_lv2_3 = NextState_load_load_fu_525_p1)) then 
                out_data_1_data_in <= add_ln88_fu_587_p2;
            elsif ((ap_const_lv2_2 = NextState_load_load_fu_525_p1)) then 
                out_data_1_data_in <= add_ln73_fu_552_p2;
            else 
                out_data_1_data_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            out_data_1_data_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_data_1_vld_in_assign_proc : process(ap_CS_fsm_state2, NextState_load_load_fu_525_p1, t_trig_fu_513_p2, grp_fu_491_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_1) and (ap_const_lv2_3 = NextState_load_load_fu_525_p1) and (t_trig_fu_513_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fu_491_p2 = ap_const_lv1_1) and (t_trig_fu_513_p2 = ap_const_lv1_1) and (ap_const_lv2_2 = NextState_load_load_fu_525_p1)))) then 
            out_data_1_vld_in <= ap_const_logic_1;
        else 
            out_data_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    select_ln57_fu_571_p3 <= 
        ap_const_lv2_2 when (en_0_data_reg(0) = '1') else 
        ap_const_lv2_0;
    select_ln62_fu_579_p3 <= 
        ap_const_lv32_FA0 when (en_0_data_reg(0) = '1') else 
        ap_const_lv32_BB8;
    t_trig_fu_513_p2 <= (xor_ln32_fu_507_p2 and trig_0_data_reg);

    trig_0_ack_out_assign_proc : process(out_data_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (out_data_1_ack_in = ap_const_logic_1)))) then 
            trig_0_ack_out <= ap_const_logic_1;
        else 
            trig_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln32_fu_507_p2 <= (pre_trig xor ap_const_lv1_1);
    xor_ln57_fu_559_p2 <= (en_0_data_reg xor ap_const_lv1_1);
end behav;
