// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="tacho_quant_tacho_quant,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.413000,HLS_SYN_LAT=15,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=629,HLS_SYN_LUT=1548,HLS_VERSION=2023_2}" *)

module tacho_quant (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        count,
        unit,
        avg,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 50'd1;
parameter    ap_ST_fsm_state2 = 50'd2;
parameter    ap_ST_fsm_state3 = 50'd4;
parameter    ap_ST_fsm_state4 = 50'd8;
parameter    ap_ST_fsm_state5 = 50'd16;
parameter    ap_ST_fsm_state6 = 50'd32;
parameter    ap_ST_fsm_state7 = 50'd64;
parameter    ap_ST_fsm_state8 = 50'd128;
parameter    ap_ST_fsm_state9 = 50'd256;
parameter    ap_ST_fsm_state10 = 50'd512;
parameter    ap_ST_fsm_state11 = 50'd1024;
parameter    ap_ST_fsm_state12 = 50'd2048;
parameter    ap_ST_fsm_state13 = 50'd4096;
parameter    ap_ST_fsm_state14 = 50'd8192;
parameter    ap_ST_fsm_state15 = 50'd16384;
parameter    ap_ST_fsm_state16 = 50'd32768;
parameter    ap_ST_fsm_state17 = 50'd65536;
parameter    ap_ST_fsm_state18 = 50'd131072;
parameter    ap_ST_fsm_state19 = 50'd262144;
parameter    ap_ST_fsm_state20 = 50'd524288;
parameter    ap_ST_fsm_state21 = 50'd1048576;
parameter    ap_ST_fsm_state22 = 50'd2097152;
parameter    ap_ST_fsm_state23 = 50'd4194304;
parameter    ap_ST_fsm_state24 = 50'd8388608;
parameter    ap_ST_fsm_state25 = 50'd16777216;
parameter    ap_ST_fsm_state26 = 50'd33554432;
parameter    ap_ST_fsm_state27 = 50'd67108864;
parameter    ap_ST_fsm_state28 = 50'd134217728;
parameter    ap_ST_fsm_state29 = 50'd268435456;
parameter    ap_ST_fsm_state30 = 50'd536870912;
parameter    ap_ST_fsm_state31 = 50'd1073741824;
parameter    ap_ST_fsm_state32 = 50'd2147483648;
parameter    ap_ST_fsm_state33 = 50'd4294967296;
parameter    ap_ST_fsm_state34 = 50'd8589934592;
parameter    ap_ST_fsm_state35 = 50'd17179869184;
parameter    ap_ST_fsm_state36 = 50'd34359738368;
parameter    ap_ST_fsm_state37 = 50'd68719476736;
parameter    ap_ST_fsm_state38 = 50'd137438953472;
parameter    ap_ST_fsm_state39 = 50'd274877906944;
parameter    ap_ST_fsm_state40 = 50'd549755813888;
parameter    ap_ST_fsm_state41 = 50'd1099511627776;
parameter    ap_ST_fsm_state42 = 50'd2199023255552;
parameter    ap_ST_fsm_state43 = 50'd4398046511104;
parameter    ap_ST_fsm_state44 = 50'd8796093022208;
parameter    ap_ST_fsm_state45 = 50'd17592186044416;
parameter    ap_ST_fsm_state46 = 50'd35184372088832;
parameter    ap_ST_fsm_state47 = 50'd70368744177664;
parameter    ap_ST_fsm_state48 = 50'd140737488355328;
parameter    ap_ST_fsm_state49 = 50'd281474976710656;
parameter    ap_ST_fsm_state50 = 50'd562949953421312;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] count;
input  [3:0] unit;
input  [7:0] avg;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [49:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] out_data_1_data_reg;
reg    out_data_1_vld_reg;
reg    out_data_1_vld_in;
reg    out_data_1_ack_in;
reg   [31:0] prev_count;
reg   [31:0] freq;
reg   [31:0] Tt;
reg   [31:0] r;
reg   [31:0] ir;
wire   [31:0] grp_fu_132_p2;
reg   [31:0] reg_141;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state38;
wire   [0:0] icmp_ln26_fu_152_p2;
wire   [0:0] icmp_ln27_fu_158_p2;
reg   [0:0] icmp_ln27_reg_427;
wire   [31:0] grp_fu_138_p1;
reg   [31:0] conv_reg_441;
wire    ap_CS_fsm_state6;
reg   [7:0] xs_exp_reg_446;
wire    ap_CS_fsm_state42;
wire   [22:0] trunc_ln342_fu_207_p1;
reg   [22:0] trunc_ln342_reg_452;
wire   [0:0] tmp_fu_220_p3;
reg   [0:0] tmp_reg_457;
wire    ap_CS_fsm_state43;
wire   [8:0] select_ln71_fu_237_p3;
reg   [8:0] select_ln71_reg_462;
wire   [0:0] icmp_ln37_fu_310_p2;
reg   [0:0] icmp_ln37_reg_467;
wire    ap_CS_fsm_state44;
wire   [0:0] icmp_ln37_2_fu_320_p2;
reg   [0:0] icmp_ln37_2_reg_472;
wire   [0:0] icmp_ln37_4_fu_330_p2;
reg   [0:0] icmp_ln37_4_reg_477;
wire   [0:0] or_ln37_fu_335_p2;
reg   [0:0] or_ln37_reg_482;
wire   [0:0] or_ln37_2_fu_347_p2;
reg   [0:0] or_ln37_2_reg_487;
wire   [31:0] select_ln37_1_fu_362_p3;
reg   [31:0] select_ln37_1_reg_492;
wire    ap_CS_fsm_state48;
wire   [31:0] select_ln37_4_fu_400_p3;
wire    ap_CS_fsm_state49;
reg   [31:0] freq_loc_0_reg_115;
wire   [31:0] grp_fu_125_p2;
wire   [31:0] val_fu_297_p3;
reg   [31:0] grp_fu_125_p0;
reg   [31:0] grp_fu_125_p1;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state45;
reg   [31:0] grp_fu_132_p0;
reg   [31:0] grp_fu_132_p1;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state23;
wire   [31:0] grp_fu_138_p0;
wire   [31:0] data_fu_193_p1;
wire   [8:0] zext_ln317_fu_211_p1;
wire   [8:0] add_ln317_fu_214_p2;
wire   [7:0] sub_ln71_fu_228_p2;
wire  signed [8:0] sext_ln71_fu_233_p1;
wire   [24:0] mantissa_fu_245_p4;
wire  signed [31:0] sext_ln71_1_fu_258_p1;
wire   [78:0] zext_ln68_fu_254_p1;
wire   [78:0] zext_ln71_fu_261_p1;
wire   [78:0] lshr_ln71_fu_265_p2;
wire   [78:0] shl_ln71_fu_271_p2;
wire   [31:0] tmp_2_fu_277_p4;
wire   [31:0] tmp_3_fu_287_p4;
wire   [0:0] icmp_ln37_3_fu_325_p2;
wire   [0:0] icmp_ln37_1_fu_315_p2;
wire   [0:0] or_ln37_1_fu_341_p2;
wire   [31:0] select_ln37_fu_377_p3;
wire   [31:0] select_ln37_3_fu_390_p3;
wire   [31:0] bitcast_ln37_fu_396_p1;
wire   [31:0] select_ln37_2_fu_384_p3;
wire    ap_CS_fsm_state50;
reg   [49:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
reg    ap_ST_fsm_state50_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 50'd1;
#0 out_data_1_data_reg = 32'd0;
#0 out_data_1_vld_reg = 1'b0;
#0 prev_count = 32'd0;
#0 freq = 32'd0;
#0 Tt = 32'd0;
#0 r = 32'd0;
#0 ir = 32'd0;
end

tacho_quant_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .out_data(out_data_1_data_reg),
    .out_data_ap_vld(out_data_1_vld_reg)
);

tacho_quant_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_125_p0),
    .din1(grp_fu_125_p1),
    .ce(1'b1),
    .dout(grp_fu_125_p2)
);

tacho_quant_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_132_p0),
    .din1(grp_fu_132_p1),
    .ce(1'b1),
    .dout(grp_fu_132_p2)
);

tacho_quant_uitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
uitofp_32ns_32_6_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_138_p0),
    .ce(1'b1),
    .dout(grp_fu_138_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state44) & (icmp_ln27_reg_427 == 1'd0))) begin
        freq_loc_0_reg_115 <= reg_141;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln27_fu_158_p2 == 1'd1) & (icmp_ln26_fu_152_p2 == 1'd0))) begin
        freq_loc_0_reg_115 <= freq;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (out_data_1_vld_in == 1'b1) & (out_data_1_vld_reg == 1'b0))) begin
        out_data_1_vld_reg <= 1'b1;
    end else if (((1'b1 == 1'b1) & (out_data_1_vld_in == 1'b0) & (out_data_1_vld_reg == 1'b1))) begin
        out_data_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        Tt <= grp_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        conv_reg_441 <= grp_fu_138_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        freq <= grp_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln27_reg_427 <= icmp_ln27_fu_158_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        icmp_ln37_2_reg_472 <= icmp_ln37_2_fu_320_p2;
        icmp_ln37_4_reg_477 <= icmp_ln37_4_fu_330_p2;
        icmp_ln37_reg_467 <= icmp_ln37_fu_310_p2;
        or_ln37_2_reg_487 <= or_ln37_2_fu_347_p2;
        or_ln37_reg_482 <= or_ln37_fu_335_p2;
        prev_count <= count;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state44) & (icmp_ln27_reg_427 == 1'd0))) begin
        ir <= val_fu_297_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (out_data_1_vld_in == 1'b1) & (out_data_1_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (out_data_1_vld_in == 1'b1) & (out_data_1_vld_reg == 1'b0)))) begin
        out_data_1_data_reg <= select_ln37_4_fu_400_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        r <= grp_fu_125_p2;
        trunc_ln342_reg_452 <= trunc_ln342_fu_207_p1;
        xs_exp_reg_446 <= {{data_fu_193_p1[30:23]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state22))) begin
        reg_141 <= grp_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        select_ln37_1_reg_492 <= select_ln37_1_fu_362_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        select_ln71_reg_462 <= select_ln71_fu_237_p3;
        tmp_reg_457 <= add_ln317_fu_214_p2[32'd8];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((out_data_1_ack_in == 1'b0)) begin
        ap_ST_fsm_state50_blk = 1'b1;
    end else begin
        ap_ST_fsm_state50_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((out_data_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state50))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((out_data_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state50))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_125_p0 = freq_loc_0_reg_115;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_125_p0 = reg_141;
    end else begin
        grp_fu_125_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_125_p1 = 32'd1148846080;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_125_p1 = 32'd1198153728;
    end else begin
        grp_fu_125_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_132_p0 = 32'd1065353216;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_132_p0 = conv_reg_441;
    end else begin
        grp_fu_132_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_132_p1 = reg_141;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_132_p1 = 32'd1203982336;
    end else begin
        grp_fu_132_p1 = 'bx;
    end
end

always @ (*) begin
    if (((out_data_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (out_data_1_vld_reg == 1'b1)))) begin
        out_data_1_ack_in = 1'b1;
    end else begin
        out_data_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        out_data_1_vld_in = 1'b1;
    end else begin
        out_data_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln27_fu_158_p2 == 1'd1) & (icmp_ln26_fu_152_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln27_fu_158_p2 == 1'd0) & (icmp_ln26_fu_152_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln26_fu_152_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            if (((out_data_1_ack_in == 1'b1) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln317_fu_214_p2 = ($signed(zext_ln317_fu_211_p1) + $signed(9'd385));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln37_fu_396_p1 = select_ln37_3_fu_390_p3;

assign data_fu_193_p1 = grp_fu_125_p2;

assign grp_fu_138_p0 = count << 32'd1;

assign icmp_ln26_fu_152_p2 = ((prev_count == count) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_158_p2 = ((unit == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln37_1_fu_315_p2 = ((unit == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln37_2_fu_320_p2 = ((unit == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln37_3_fu_325_p2 = ((unit == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln37_4_fu_330_p2 = ((unit == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_310_p2 = ((unit == 4'd1) ? 1'b1 : 1'b0);

assign lshr_ln71_fu_265_p2 = zext_ln68_fu_254_p1 >> zext_ln71_fu_261_p1;

assign mantissa_fu_245_p4 = {{{{1'd1}, {trunc_ln342_reg_452}}}, {1'd0}};

assign or_ln37_1_fu_341_p2 = (icmp_ln37_2_fu_320_p2 | icmp_ln37_1_fu_315_p2);

assign or_ln37_2_fu_347_p2 = (or_ln37_fu_335_p2 | or_ln37_1_fu_341_p2);

assign or_ln37_fu_335_p2 = (icmp_ln37_4_fu_330_p2 | icmp_ln37_3_fu_325_p2);

assign select_ln37_1_fu_362_p3 = ((icmp_ln37_2_reg_472[0:0] == 1'b1) ? grp_fu_125_p2 : Tt);

assign select_ln37_2_fu_384_p3 = ((icmp_ln37_reg_467[0:0] == 1'b1) ? ir : count);

assign select_ln37_3_fu_390_p3 = ((or_ln37_reg_482[0:0] == 1'b1) ? select_ln37_fu_377_p3 : select_ln37_1_reg_492);

assign select_ln37_4_fu_400_p3 = ((or_ln37_2_reg_487[0:0] == 1'b1) ? bitcast_ln37_fu_396_p1 : select_ln37_2_fu_384_p3);

assign select_ln37_fu_377_p3 = ((icmp_ln37_4_reg_477[0:0] == 1'b1) ? r : freq_loc_0_reg_115);

assign select_ln71_fu_237_p3 = ((tmp_fu_220_p3[0:0] == 1'b1) ? sext_ln71_fu_233_p1 : add_ln317_fu_214_p2);

assign sext_ln71_1_fu_258_p1 = $signed(select_ln71_reg_462);

assign sext_ln71_fu_233_p1 = $signed(sub_ln71_fu_228_p2);

assign shl_ln71_fu_271_p2 = zext_ln68_fu_254_p1 << zext_ln71_fu_261_p1;

assign sub_ln71_fu_228_p2 = (8'd127 - xs_exp_reg_446);

assign tmp_2_fu_277_p4 = {{lshr_ln71_fu_265_p2[55:24]}};

assign tmp_3_fu_287_p4 = {{shl_ln71_fu_271_p2[55:24]}};

assign tmp_fu_220_p3 = add_ln317_fu_214_p2[32'd8];

assign trunc_ln342_fu_207_p1 = data_fu_193_p1[22:0];

assign val_fu_297_p3 = ((tmp_reg_457[0:0] == 1'b1) ? tmp_2_fu_277_p4 : tmp_3_fu_287_p4);

assign zext_ln317_fu_211_p1 = xs_exp_reg_446;

assign zext_ln68_fu_254_p1 = mantissa_fu_245_p4;

assign zext_ln71_fu_261_p1 = $unsigned(sext_ln71_1_fu_258_p1);

endmodule //tacho_quant
