-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ADCCountsToFloat is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r : IN STD_LOGIC_VECTOR (31 downto 0);
    usr_gpio_o : OUT STD_LOGIC_VECTOR (2 downto 0);
    usr_gpio_o_ap_vld : OUT STD_LOGIC;
    chanValid : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of ADCCountsToFloat is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ADCCountsToFloat_ADCCountsToFloat,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=29.802000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=20.403000,HLS_SYN_LAT=10,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1406,HLS_SYN_LUT=1893,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_FF000000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal cal_step_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal cal_step_ce0 : STD_LOGIC;
    signal cal_step_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cal_offset_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal cal_offset_ce0 : STD_LOGIC;
    signal cal_offset_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal iCurrentRange : STD_LOGIC_VECTOR (31 downto 0);
    signal iCurrentRange_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal iCurrentRange_0_vld_reg : STD_LOGIC := '0';
    signal iCurrentRange_0_ack_out : STD_LOGIC;
    signal iOverloadCount_1_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal iOverloadCount_1_vld_reg : STD_LOGIC := '0';
    signal iOverloadCount_1_vld_in : STD_LOGIC;
    signal iOverloadCount_1_ack_in : STD_LOGIC;
    signal OLValid_1_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal OLValid_1_data_in : STD_LOGIC_VECTOR (31 downto 0);
    signal OLValid_1_vld_reg : STD_LOGIC := '0';
    signal OLValid_1_vld_in : STD_LOGIC;
    signal OLValid_1_ack_in : STD_LOGIC;
    signal reset : STD_LOGIC_VECTOR (31 downto 0);
    signal pointOffset : STD_LOGIC_VECTOR (31 downto 0);
    signal pointOffset_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pointOffset_0_vld_reg : STD_LOGIC := '0';
    signal pointOffset_0_ack_out : STD_LOGIC;
    signal gainChanged_1_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal gainChanged_1_vld_reg : STD_LOGIC := '0';
    signal gainChanged_1_vld_in : STD_LOGIC;
    signal gainChanged_1_ack_in : STD_LOGIC;
    signal status_1_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal status_1_vld_reg : STD_LOGIC := '0';
    signal status_1_vld_in : STD_LOGIC;
    signal status_1_ack_in : STD_LOGIC;
    signal iCurrentGain : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal doOnce : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal iCountdownGainChange : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal iCurrentGainChanges : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal iCurrentOverloads : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal retVal : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_load_fu_354_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_2_fu_602_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_341_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_371 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal sext_ln45_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal thisRange_fu_471_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal thisRange_reg_707 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal chanValid_assign_load_load_fu_599_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_724 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_337_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul1_reg_728 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal mul_reg_738 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln56_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln56_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_doOnce_new_1_phi_fu_272_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln69_fu_535_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_doOnce_new_2_phi_fu_302_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal iCurrentGainChanges_loc_1_reg_310 : STD_LOGIC_VECTOR (31 downto 0);
    signal iCurrentOverloads_loc_0_reg_322 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_554_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln79_fu_573_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln52_fu_425_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln53_fu_457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln56_fu_495_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_333_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal fADCOffset_fu_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bitcast_ln53_fu_462_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal fADCStepVal_fu_144 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bitcast_ln52_fu_448_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_assign_fu_148 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_vInput_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal chanValid_assign_fu_152 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal vInput_fu_156 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal zext_ln134_fu_614_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal vInput_3_fu_623_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln86_fu_590_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_vInput_load_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_vInput_load_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_vInput_load : STD_LOGIC_VECTOR (31 downto 0);
    signal vStatus_fu_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal vStatus_1_fu_412_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_333_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_402_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_fu_433_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln56_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_fu_489_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal vInput_2_fu_586_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal vInput_4_fu_610_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state16 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ADCCountsToFloat_fsub_32ns_32ns_32_3_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ADCCountsToFloat_fmul_32ns_32ns_32_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ADCCountsToFloat_sitofp_32ns_32_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ADCCountsToFloat_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        iCurrentRange : OUT STD_LOGIC_VECTOR (31 downto 0);
        reset : OUT STD_LOGIC_VECTOR (31 downto 0);
        cal_step_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        cal_step_ce0 : IN STD_LOGIC;
        cal_step_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        cal_offset_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        cal_offset_ce0 : IN STD_LOGIC;
        cal_offset_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        iOverloadCount : IN STD_LOGIC_VECTOR (31 downto 0);
        iOverloadCount_ap_vld : IN STD_LOGIC;
        OLValid : IN STD_LOGIC_VECTOR (31 downto 0);
        OLValid_ap_vld : IN STD_LOGIC;
        pointOffset : OUT STD_LOGIC_VECTOR (31 downto 0);
        gainChanged : IN STD_LOGIC_VECTOR (31 downto 0);
        gainChanged_ap_vld : IN STD_LOGIC;
        status : IN STD_LOGIC_VECTOR (31 downto 0);
        status_ap_vld : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component ADCCountsToFloat_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        iCurrentRange => iCurrentRange,
        reset => reset,
        cal_step_address0 => cal_step_address0,
        cal_step_ce0 => cal_step_ce0,
        cal_step_q0 => cal_step_q0,
        cal_offset_address0 => cal_offset_address0,
        cal_offset_ce0 => cal_offset_ce0,
        cal_offset_q0 => cal_offset_q0,
        iOverloadCount => iOverloadCount_1_data_reg,
        iOverloadCount_ap_vld => iOverloadCount_1_vld_reg,
        OLValid => OLValid_1_data_reg,
        OLValid_ap_vld => OLValid_1_vld_reg,
        pointOffset => pointOffset,
        gainChanged => gainChanged_1_data_reg,
        gainChanged_ap_vld => gainChanged_1_vld_reg,
        status => status_1_data_reg,
        status_ap_vld => status_1_vld_reg);

    fsub_32ns_32ns_32_3_full_dsp_1_U1 : component ADCCountsToFloat_fsub_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_333_p0,
        din1 => fADCOffset_fu_140,
        ce => ap_const_logic_1,
        dout => grp_fu_333_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U2 : component ADCCountsToFloat_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => reg_371,
        din1 => fADCStepVal_fu_144,
        ce => ap_const_logic_1,
        dout => grp_fu_337_p2);

    sitofp_32ns_32_2_no_dsp_1_U3 : component ADCCountsToFloat_sitofp_32ns_32_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_load_fu_354_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_341_p1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    OLValid_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_0 = OLValid_1_vld_reg) and (ap_const_logic_1 = OLValid_1_vld_in))) then 
                OLValid_1_vld_reg <= ap_const_logic_1;
            elsif (((ap_const_logic_0 = OLValid_1_vld_in) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = OLValid_1_vld_reg))) then 
                OLValid_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;

    gainChanged_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (gainChanged_1_vld_in = ap_const_logic_1) and (gainChanged_1_vld_reg = ap_const_logic_0))) then 
                gainChanged_1_vld_reg <= ap_const_logic_1;
            elsif (((ap_const_logic_1 = ap_const_logic_1) and (gainChanged_1_vld_in = ap_const_logic_0) and (gainChanged_1_vld_reg = ap_const_logic_1))) then 
                gainChanged_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;

    iCurrentGainChanges_loc_1_reg_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((icmp_ln67_fu_523_p2 = ap_const_lv1_0)) then 
                    iCurrentGainChanges_loc_1_reg_310 <= ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4;
                elsif ((icmp_ln67_fu_523_p2 = ap_const_lv1_1)) then 
                    iCurrentGainChanges_loc_1_reg_310 <= iCurrentGainChanges;
                end if;
            end if; 
        end if;
    end process;

    iCurrentOverloads_loc_0_reg_322_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((tmp_1_fu_554_p3 = ap_const_lv1_1)) then 
                    iCurrentOverloads_loc_0_reg_322 <= add_ln79_fu_573_p2;
                elsif ((tmp_1_fu_554_p3 = ap_const_lv1_0)) then 
                    iCurrentOverloads_loc_0_reg_322 <= iCurrentOverloads;
                end if;
            end if; 
        end if;
    end process;

    iCurrentRange_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    iOverloadCount_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (iOverloadCount_1_vld_in = ap_const_logic_1) and (iOverloadCount_1_vld_reg = ap_const_logic_0))) then 
                iOverloadCount_1_vld_reg <= ap_const_logic_1;
            elsif (((ap_const_logic_1 = ap_const_logic_1) and (iOverloadCount_1_vld_in = ap_const_logic_0) and (iOverloadCount_1_vld_reg = ap_const_logic_1))) then 
                iOverloadCount_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;

    pointOffset_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    status_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (status_1_vld_in = ap_const_logic_1) and (status_1_vld_reg = ap_const_logic_0))) then 
                status_1_vld_reg <= ap_const_logic_1;
            elsif (((ap_const_logic_1 = ap_const_logic_1) and (status_1_vld_in = ap_const_logic_0) and (status_1_vld_reg = ap_const_logic_1))) then 
                status_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;

    vInput_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vInput_fu_156 <= ap_sig_allocacmp_vInput_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                vInput_fu_156 <= zext_ln86_fu_590_p1;
            elsif (((tmp_2_fu_602_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vInput_fu_156 <= vInput_3_fu_623_p2;
            elsif (((tmp_2_fu_602_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vInput_fu_156 <= zext_ln134_fu_614_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = OLValid_1_vld_in) and (ap_const_logic_1 = OLValid_1_vld_reg)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_0 = OLValid_1_vld_reg) and (ap_const_logic_1 = OLValid_1_vld_in)))) then
                OLValid_1_data_reg <= OLValid_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                chanValid_assign_fu_152 <= chanValid;
                input_assign_fu_148 <= input_r;
                    vStatus_fu_160(31 downto 24) <= vStatus_1_fu_412_p3(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                doOnce <= ap_phi_mux_doOnce_new_2_phi_fu_302_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                fADCOffset_fu_140 <= bitcast_ln53_fu_462_p1;
                iCountdownGainChange <= select_ln56_fu_495_p3;
                thisRange_reg_707 <= thisRange_fu_471_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                fADCStepVal_fu_144 <= bitcast_ln52_fu_448_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (gainChanged_1_vld_in = ap_const_logic_1) and (gainChanged_1_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (gainChanged_1_vld_in = ap_const_logic_1) and (gainChanged_1_vld_reg = ap_const_logic_0)))) then
                gainChanged_1_data_reg <= iCurrentGainChanges_loc_1_reg_310;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln67_fu_523_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                iCurrentGain <= thisRange_fu_471_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln56_fu_511_p2 = ap_const_lv1_1) and (icmp_ln67_fu_523_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                iCurrentGainChanges <= add_ln69_fu_535_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_fu_554_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                iCurrentOverloads <= add_ln79_fu_573_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (iCurrentRange_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (iCurrentRange_0_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (iCurrentRange_0_vld_reg = ap_const_logic_0)))) then
                iCurrentRange_0_data_reg <= iCurrentRange;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (iOverloadCount_1_vld_in = ap_const_logic_1) and (iOverloadCount_1_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (iOverloadCount_1_vld_in = ap_const_logic_1) and (iOverloadCount_1_vld_reg = ap_const_logic_0)))) then
                iOverloadCount_1_data_reg <= iCurrentOverloads_loc_0_reg_322;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                mul1_reg_728 <= grp_fu_337_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                mul_reg_738 <= grp_fu_337_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (pointOffset_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (pointOffset_0_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (pointOffset_0_vld_reg = ap_const_logic_0)))) then
                pointOffset_0_data_reg <= pointOffset;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_371 <= grp_fu_341_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_2_reg_724 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((tmp_2_reg_724 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then
                retVal <= grp_fu_333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (status_1_vld_in = ap_const_logic_1) and (status_1_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (status_1_vld_in = ap_const_logic_1) and (status_1_vld_reg = ap_const_logic_0)))) then
                status_1_data_reg <= sext_ln45_fu_443_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_2_reg_724 <= vInput_fu_156(23 downto 23);
            end if;
        end if;
    end process;
    vStatus_fu_160(23 downto 0) <= "000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, tmp_2_fu_602_p3, ap_CS_fsm_state16, ap_block_state16)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((tmp_2_fu_602_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state16 => 
                if (((ap_const_boolean_0 = ap_block_state16) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;

    OLValid_1_ack_in_assign_proc : process(OLValid_1_vld_reg)
    begin
        if (((ap_const_logic_0 = OLValid_1_vld_reg) or ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = OLValid_1_vld_reg)))) then 
            OLValid_1_ack_in <= ap_const_logic_1;
        else 
            OLValid_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    OLValid_1_data_in_assign_proc : process(ap_CS_fsm_state3, chanValid_assign_load_load_fu_599_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((chanValid_assign_load_load_fu_599_p1 = ap_const_lv1_1)) then 
                OLValid_1_data_in <= ap_const_lv32_1;
            elsif ((chanValid_assign_load_load_fu_599_p1 = ap_const_lv1_0)) then 
                OLValid_1_data_in <= ap_const_lv32_0;
            else 
                OLValid_1_data_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            OLValid_1_data_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    OLValid_1_vld_in_assign_proc : process(ap_CS_fsm_state3, chanValid_assign_load_load_fu_599_p1)
    begin
        if ((((chanValid_assign_load_load_fu_599_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((chanValid_assign_load_load_fu_599_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            OLValid_1_vld_in <= ap_const_logic_1;
        else 
            OLValid_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    add_ln59_fu_489_p2 <= std_logic_vector(unsigned(iCountdownGainChange) + unsigned(ap_const_lv32_1));
    add_ln69_fu_535_p2 <= std_logic_vector(unsigned(iCurrentGainChanges) + unsigned(ap_const_lv32_1));
    add_ln79_fu_573_p2 <= std_logic_vector(unsigned(iCurrentOverloads) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;

    ap_ST_fsm_state16_blk_assign_proc : process(ap_block_state16)
    begin
        if ((ap_const_boolean_1 = ap_block_state16)) then 
            ap_ST_fsm_state16_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state16_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state16_assign_proc : process(iOverloadCount_1_ack_in, OLValid_1_ack_in, gainChanged_1_ack_in, status_1_ack_in)
    begin
                ap_block_state16 <= ((iOverloadCount_1_ack_in = ap_const_logic_0) or (ap_const_logic_0 = OLValid_1_ack_in) or (status_1_ack_in = ap_const_logic_0) or (gainChanged_1_ack_in = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state16, ap_block_state16)
    begin
        if (((ap_const_boolean_0 = ap_block_state16) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_doOnce_flag_1_phi_fu_262_p4_assign_proc : process(ap_CS_fsm_state3, icmp_ln67_fu_523_p2, or_ln56_fu_511_p2, xor_ln56_fu_503_p2)
    begin
        if (((icmp_ln67_fu_523_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
            if ((or_ln56_fu_511_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 <= xor_ln56_fu_503_p2;
            elsif ((or_ln56_fu_511_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 <= "X";
            end if;
        else 
            ap_phi_mux_doOnce_flag_1_phi_fu_262_p4 <= "X";
        end if; 
    end process;


    ap_phi_mux_doOnce_flag_2_phi_fu_292_p4_assign_proc : process(ap_CS_fsm_state3, ap_phi_mux_doOnce_flag_1_phi_fu_262_p4, icmp_ln67_fu_523_p2, xor_ln56_fu_503_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((icmp_ln67_fu_523_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 <= ap_phi_mux_doOnce_flag_1_phi_fu_262_p4;
            elsif ((icmp_ln67_fu_523_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 <= xor_ln56_fu_503_p2;
            else 
                ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 <= "X";
            end if;
        else 
            ap_phi_mux_doOnce_flag_2_phi_fu_292_p4 <= "X";
        end if; 
    end process;


    ap_phi_mux_doOnce_new_1_phi_fu_272_p4_assign_proc : process(ap_CS_fsm_state3, icmp_ln67_fu_523_p2, or_ln56_fu_511_p2)
    begin
        if (((icmp_ln67_fu_523_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
            if ((or_ln56_fu_511_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_doOnce_new_1_phi_fu_272_p4 <= ap_const_lv1_1;
            elsif ((or_ln56_fu_511_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_doOnce_new_1_phi_fu_272_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_doOnce_new_1_phi_fu_272_p4 <= "X";
            end if;
        else 
            ap_phi_mux_doOnce_new_1_phi_fu_272_p4 <= "X";
        end if; 
    end process;


    ap_phi_mux_doOnce_new_2_phi_fu_302_p4_assign_proc : process(ap_CS_fsm_state3, icmp_ln67_fu_523_p2, ap_phi_mux_doOnce_new_1_phi_fu_272_p4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((icmp_ln67_fu_523_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_doOnce_new_2_phi_fu_302_p4 <= ap_phi_mux_doOnce_new_1_phi_fu_272_p4;
            elsif ((icmp_ln67_fu_523_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_doOnce_new_2_phi_fu_302_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_doOnce_new_2_phi_fu_302_p4 <= "X";
            end if;
        else 
            ap_phi_mux_doOnce_new_2_phi_fu_302_p4 <= "X";
        end if; 
    end process;


    ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4_assign_proc : process(iCurrentGainChanges, ap_CS_fsm_state3, icmp_ln67_fu_523_p2, or_ln56_fu_511_p2, add_ln69_fu_535_p2)
    begin
        if (((icmp_ln67_fu_523_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
            if ((or_ln56_fu_511_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 <= iCurrentGainChanges;
            elsif ((or_ln56_fu_511_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 <= add_ln69_fu_535_p2;
            else 
                ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_iCurrentGainChanges_loc_0_phi_fu_283_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state16, ap_block_state16)
    begin
        if (((ap_const_boolean_0 = ap_block_state16) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= retVal;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_vInput_1_assign_proc : process(ap_CS_fsm_state1, input_r, input_assign_fu_148)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            ap_sig_allocacmp_vInput_1 <= input_r;
        else 
            ap_sig_allocacmp_vInput_1 <= input_assign_fu_148;
        end if; 
    end process;


    ap_sig_allocacmp_vInput_load_assign_proc : process(ap_CS_fsm_state1, ap_sig_allocacmp_vInput_1, vInput_fu_156)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            ap_sig_allocacmp_vInput_load <= ap_sig_allocacmp_vInput_1;
        else 
            ap_sig_allocacmp_vInput_load <= vInput_fu_156;
        end if; 
    end process;


    ap_sig_allocacmp_vInput_load_5_assign_proc : process(ap_CS_fsm_state4, tmp_2_fu_602_p3, vInput_fu_156, zext_ln134_fu_614_p1)
    begin
        if (((tmp_2_fu_602_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_sig_allocacmp_vInput_load_5 <= zext_ln134_fu_614_p1;
        else 
            ap_sig_allocacmp_vInput_load_5 <= vInput_fu_156;
        end if; 
    end process;


    ap_sig_allocacmp_vInput_load_6_assign_proc : process(ap_CS_fsm_state4, tmp_2_fu_602_p3, vInput_fu_156, vInput_3_fu_623_p2)
    begin
        if (((tmp_2_fu_602_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_sig_allocacmp_vInput_load_6 <= vInput_3_fu_623_p2;
        else 
            ap_sig_allocacmp_vInput_load_6 <= vInput_fu_156;
        end if; 
    end process;

    bitcast_ln52_fu_448_p1 <= cal_step_q0;
    bitcast_ln53_fu_462_p1 <= cal_offset_q0;
    cal_offset_address0 <= zext_ln53_fu_457_p1(3 - 1 downto 0);

    cal_offset_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            cal_offset_ce0 <= ap_const_logic_1;
        else 
            cal_offset_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    cal_step_address0 <= zext_ln52_fu_425_p1(3 - 1 downto 0);

    cal_step_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cal_step_ce0 <= ap_const_logic_1;
        else 
            cal_step_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    chanValid_assign_load_load_fu_599_p1 <= chanValid_assign_fu_152;

    gainChanged_1_ack_in_assign_proc : process(gainChanged_1_vld_reg)
    begin
        if (((gainChanged_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (gainChanged_1_vld_reg = ap_const_logic_1)))) then 
            gainChanged_1_ack_in <= ap_const_logic_1;
        else 
            gainChanged_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    gainChanged_1_vld_in_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            gainChanged_1_vld_in <= ap_const_logic_1;
        else 
            gainChanged_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_333_p0_assign_proc : process(mul1_reg_728, ap_CS_fsm_state8, mul_reg_738, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_333_p0 <= mul_reg_738;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_333_p0 <= mul1_reg_728;
        else 
            grp_fu_333_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_load_fu_354_p1_assign_proc : process(ap_CS_fsm_state4, tmp_2_fu_602_p3, ap_sig_allocacmp_vInput_load_5, ap_sig_allocacmp_vInput_load_6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((tmp_2_fu_602_p3 = ap_const_lv1_1)) then 
                grp_load_fu_354_p1 <= ap_sig_allocacmp_vInput_load_6;
            elsif ((tmp_2_fu_602_p3 = ap_const_lv1_0)) then 
                grp_load_fu_354_p1 <= ap_sig_allocacmp_vInput_load_5;
            else 
                grp_load_fu_354_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_load_fu_354_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    iCurrentRange_0_ack_out_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state16, ap_block_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_boolean_0 = ap_block_state16) and (ap_const_logic_1 = ap_CS_fsm_state16)))) then 
            iCurrentRange_0_ack_out <= ap_const_logic_1;
        else 
            iCurrentRange_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    iOverloadCount_1_ack_in_assign_proc : process(iOverloadCount_1_vld_reg)
    begin
        if (((iOverloadCount_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (iOverloadCount_1_vld_reg = ap_const_logic_1)))) then 
            iOverloadCount_1_ack_in <= ap_const_logic_1;
        else 
            iOverloadCount_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    iOverloadCount_1_vld_in_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            iOverloadCount_1_vld_in <= ap_const_logic_1;
        else 
            iOverloadCount_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln56_fu_475_p2 <= "1" when (thisRange_fu_471_p1 = iCurrentGain) else "0";
    icmp_ln67_fu_523_p2 <= "1" when (signed(select_ln56_fu_495_p3) < signed(pointOffset_0_data_reg)) else "0";
    or_ln56_fu_511_p2 <= (xor_ln56_fu_503_p2 or doOnce);

    pointOffset_0_ack_out_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state16, ap_block_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_boolean_0 = ap_block_state16) and (ap_const_logic_1 = ap_CS_fsm_state16)))) then 
            pointOffset_0_ack_out <= ap_const_logic_1;
        else 
            pointOffset_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    select_ln56_fu_495_p3 <= 
        ap_const_lv32_0 when (icmp_ln56_fu_475_p2(0) = '1') else 
        add_ln59_fu_489_p2;
        sext_ln45_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_433_p4),32));


    status_1_ack_in_assign_proc : process(status_1_vld_reg)
    begin
        if (((status_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (status_1_vld_reg = ap_const_logic_1)))) then 
            status_1_ack_in <= ap_const_logic_1;
        else 
            status_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    status_1_vld_in_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            status_1_vld_in <= ap_const_logic_1;
        else 
            status_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    thisRange_fu_471_p1 <= iCurrentRange_0_data_reg(3 - 1 downto 0);
    tmp_1_fu_554_p3 <= vInput_fu_156(27 downto 27);
    tmp_2_fu_602_p3 <= vInput_fu_156(23 downto 23);
    tmp_fu_402_p4 <= ap_sig_allocacmp_vInput_load(31 downto 24);
    trunc_ln_fu_433_p4 <= vStatus_fu_160(31 downto 24);

    usr_gpio_o_assign_proc : process(ap_CS_fsm_state4, thisRange_reg_707)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((thisRange_reg_707 = ap_const_lv3_7)) then 
                usr_gpio_o <= ap_const_lv3_7;
            elsif ((thisRange_reg_707 = ap_const_lv3_0)) then 
                usr_gpio_o <= ap_const_lv3_0;
            elsif ((thisRange_reg_707 = ap_const_lv3_1)) then 
                usr_gpio_o <= ap_const_lv3_1;
            elsif ((thisRange_reg_707 = ap_const_lv3_2)) then 
                usr_gpio_o <= ap_const_lv3_4;
            elsif ((thisRange_reg_707 = ap_const_lv3_3)) then 
                usr_gpio_o <= ap_const_lv3_2;
            elsif ((thisRange_reg_707 = ap_const_lv3_4)) then 
                usr_gpio_o <= ap_const_lv3_5;
            elsif ((thisRange_reg_707 = ap_const_lv3_5)) then 
                usr_gpio_o <= ap_const_lv3_3;
            elsif ((thisRange_reg_707 = ap_const_lv3_6)) then 
                usr_gpio_o <= ap_const_lv3_6;
            else 
                usr_gpio_o <= "XXX";
            end if;
        else 
            usr_gpio_o <= "XXX";
        end if; 
    end process;


    usr_gpio_o_ap_vld_assign_proc : process(ap_CS_fsm_state4, thisRange_reg_707)
    begin
        if ((((thisRange_reg_707 = ap_const_lv3_7) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((thisRange_reg_707 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((thisRange_reg_707 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((thisRange_reg_707 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((thisRange_reg_707 = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((thisRange_reg_707 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((thisRange_reg_707 = ap_const_lv3_5) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((thisRange_reg_707 = ap_const_lv3_6) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            usr_gpio_o_ap_vld <= ap_const_logic_1;
        else 
            usr_gpio_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    vInput_2_fu_586_p1 <= vInput_fu_156(24 - 1 downto 0);
    vInput_3_fu_623_p2 <= (vInput_fu_156 or ap_const_lv32_FF000000);
    vInput_4_fu_610_p1 <= vInput_fu_156(24 - 1 downto 0);
    vStatus_1_fu_412_p3 <= (tmp_fu_402_p4 & ap_const_lv24_0);
    xor_ln56_fu_503_p2 <= (icmp_ln56_fu_475_p2 xor ap_const_lv1_1);
    zext_ln134_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vInput_4_fu_610_p1),32));
    zext_ln52_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iCurrentGain),64));
    zext_ln53_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iCurrentGain),64));
    zext_ln86_fu_590_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vInput_2_fu_586_p1),32));
end behav;
