// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="DriveScale_DriveScale,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=29.802000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=26.930000,HLS_SYN_LAT=20,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1559,HLS_SYN_LUT=4891,HLS_VERSION=2023_2}" *)

module DriveScale (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r,
        IN1024OUT8192_TDATA,
        IN1024OUT8192_TVALID,
        IN1024OUT8192_TREADY,
        IN1024OUT8192_TKEEP,
        IN1024OUT8192_TSTRB,
        IN1024OUT8192_TLAST,
        IN2048OUT8192_TDATA,
        IN2048OUT8192_TVALID,
        IN2048OUT8192_TREADY,
        IN2048OUT8192_TKEEP,
        IN2048OUT8192_TSTRB,
        IN2048OUT8192_TLAST,
        IN4096OUT8192_TDATA,
        IN4096OUT8192_TVALID,
        IN4096OUT8192_TREADY,
        IN4096OUT8192_TKEEP,
        IN4096OUT8192_TSTRB,
        IN4096OUT8192_TLAST,
        IN8192OUT65536_TDATA,
        IN8192OUT65536_TVALID,
        IN8192OUT65536_TREADY,
        IN8192OUT65536_TKEEP,
        IN8192OUT65536_TSTRB,
        IN8192OUT65536_TLAST,
        IN16384OUT65536_TDATA,
        IN16384OUT65536_TVALID,
        IN16384OUT65536_TREADY,
        IN16384OUT65536_TKEEP,
        IN16384OUT65536_TSTRB,
        IN16384OUT65536_TLAST,
        IN32768OUT65536_TDATA,
        IN32768OUT65536_TVALID,
        IN32768OUT65536_TREADY,
        IN32768OUT65536_TKEEP,
        IN32768OUT65536_TSTRB,
        IN32768OUT65536_TLAST,
        IN65536OUT262144_TDATA,
        IN65536OUT262144_TVALID,
        IN65536OUT262144_TREADY,
        IN65536OUT262144_TKEEP,
        IN65536OUT262144_TSTRB,
        IN65536OUT262144_TLAST,
        IN131072OUT262144_TDATA,
        IN131072OUT262144_TVALID,
        IN131072OUT262144_TREADY,
        IN131072OUT262144_TKEEP,
        IN131072OUT262144_TSTRB,
        IN131072OUT262144_TLAST,
        IN262144OUT262144_TDATA,
        IN262144OUT262144_TVALID,
        IN262144OUT262144_TREADY,
        IN262144OUT262144_TKEEP,
        IN262144OUT262144_TSTRB,
        IN262144OUT262144_TLAST,
        interp,
        loopback,
        loopback_ap_vld,
        ap_return,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] input_r;
output  [23:0] IN1024OUT8192_TDATA;
output   IN1024OUT8192_TVALID;
input   IN1024OUT8192_TREADY;
output  [2:0] IN1024OUT8192_TKEEP;
output  [2:0] IN1024OUT8192_TSTRB;
output  [0:0] IN1024OUT8192_TLAST;
output  [23:0] IN2048OUT8192_TDATA;
output   IN2048OUT8192_TVALID;
input   IN2048OUT8192_TREADY;
output  [2:0] IN2048OUT8192_TKEEP;
output  [2:0] IN2048OUT8192_TSTRB;
output  [0:0] IN2048OUT8192_TLAST;
output  [23:0] IN4096OUT8192_TDATA;
output   IN4096OUT8192_TVALID;
input   IN4096OUT8192_TREADY;
output  [2:0] IN4096OUT8192_TKEEP;
output  [2:0] IN4096OUT8192_TSTRB;
output  [0:0] IN4096OUT8192_TLAST;
output  [23:0] IN8192OUT65536_TDATA;
output   IN8192OUT65536_TVALID;
input   IN8192OUT65536_TREADY;
output  [2:0] IN8192OUT65536_TKEEP;
output  [2:0] IN8192OUT65536_TSTRB;
output  [0:0] IN8192OUT65536_TLAST;
output  [23:0] IN16384OUT65536_TDATA;
output   IN16384OUT65536_TVALID;
input   IN16384OUT65536_TREADY;
output  [2:0] IN16384OUT65536_TKEEP;
output  [2:0] IN16384OUT65536_TSTRB;
output  [0:0] IN16384OUT65536_TLAST;
output  [23:0] IN32768OUT65536_TDATA;
output   IN32768OUT65536_TVALID;
input   IN32768OUT65536_TREADY;
output  [2:0] IN32768OUT65536_TKEEP;
output  [2:0] IN32768OUT65536_TSTRB;
output  [0:0] IN32768OUT65536_TLAST;
output  [23:0] IN65536OUT262144_TDATA;
output   IN65536OUT262144_TVALID;
input   IN65536OUT262144_TREADY;
output  [2:0] IN65536OUT262144_TKEEP;
output  [2:0] IN65536OUT262144_TSTRB;
output  [0:0] IN65536OUT262144_TLAST;
output  [23:0] IN131072OUT262144_TDATA;
output   IN131072OUT262144_TVALID;
input   IN131072OUT262144_TREADY;
output  [2:0] IN131072OUT262144_TKEEP;
output  [2:0] IN131072OUT262144_TSTRB;
output  [0:0] IN131072OUT262144_TLAST;
output  [23:0] IN262144OUT262144_TDATA;
output   IN262144OUT262144_TVALID;
input   IN262144OUT262144_TREADY;
output  [2:0] IN262144OUT262144_TKEEP;
output  [2:0] IN262144OUT262144_TSTRB;
output  [0:0] IN262144OUT262144_TLAST;
output  [3:0] interp;
output  [31:0] loopback;
output   loopback_ap_vld;
output  [31:0] ap_return;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg loopback_ap_vld;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] ScaleValue;
reg   [31:0] ScaleValue_0_data_reg;
reg    ScaleValue_0_vld_reg;
reg    ScaleValue_0_ack_out;
wire   [31:0] ZeroCross;
reg   [31:0] ZeroCross_0_data_reg;
reg    ZeroCross_0_vld_reg;
reg    ZeroCross_0_ack_out;
reg   [1:0] calibratedStep_address0;
reg    calibratedStep_ce0;
wire   [31:0] calibratedStep_q0;
wire   [1:0] calibratedOffset_address0;
reg    calibratedOffset_ce0;
wire   [31:0] calibratedOffset_q0;
wire   [31:0] samp_index;
reg   [31:0] samp_index_0_data_reg;
reg    samp_index_0_vld_reg;
reg    samp_index_0_ack_out;
wire   [31:0] iCurrentFilter;
reg   [31:0] iCurrentFilter_0_data_reg;
reg    iCurrentFilter_0_vld_reg;
reg    iCurrentFilter_0_ack_out;
wire   [31:0] fClipValue;
reg   [31:0] fClipValue_0_data_reg;
reg    fClipValue_0_vld_reg;
reg    fClipValue_0_ack_out;
reg   [31:0] fDACScaleFactor;
reg    IN1024OUT8192_TDATA_blk_n;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg   [31:0] index_reg_1320;
reg    IN2048OUT8192_TDATA_blk_n;
reg    IN4096OUT8192_TDATA_blk_n;
reg    IN8192OUT65536_TDATA_blk_n;
reg    IN16384OUT65536_TDATA_blk_n;
reg    IN32768OUT65536_TDATA_blk_n;
reg    IN65536OUT262144_TDATA_blk_n;
reg    IN131072OUT262144_TDATA_blk_n;
reg    IN262144OUT262144_TDATA_blk_n;
reg   [31:0] grp_load_fu_576_p1;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state18;
wire   [31:0] grp_fu_549_p2;
reg   [31:0] reg_593;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state19;
wire   [31:0] grp_fu_555_p2;
reg   [31:0] reg_598;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln51_fu_603_p2;
reg   [0:0] icmp_ln51_reg_1245;
wire   [31:0] bitcast_ln52_fu_609_p1;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [0:0] and_ln55_fu_655_p2;
reg   [0:0] and_ln55_reg_1259;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [31:0] bitcast_ln82_fu_690_p1;
wire   [31:0] bitcast_ln79_fu_695_p1;
wire    ap_CS_fsm_state9;
wire   [31:0] grp_fu_559_p2;
reg   [31:0] dc_1_reg_1286;
wire   [63:0] conv7_fu_563_p1;
reg   [63:0] conv7_reg_1291;
wire    ap_CS_fsm_state15;
wire   [63:0] grp_fu_571_p2;
reg   [63:0] dc_reg_1296;
wire   [23:0] DacCounts_fu_1192_p1;
reg   [31:0] empty_reg_537;
wire   [63:0] zext_ln55_fu_613_p1;
wire   [63:0] zext_ln56_fu_661_p1;
wire   [63:0] zext_ln79_fu_680_p1;
wire   [31:0] bitcast_ln56_fu_666_p1;
reg   [31:0] temp_fu_266;
reg   [31:0] ap_sig_allocacmp_temp_load_1;
reg   [31:0] offsetCounts_fu_270;
wire   [31:0] result_8_fu_1119_p3;
reg   [31:0] ap_sig_allocacmp_offsetCounts_load;
reg   [31:0] calibratedCounts_fu_274;
wire   [31:0] calibratedCounts_2_fu_1135_p2;
wire   [31:0] calibratedCounts_4_fu_1176_p2;
wire   [31:0] result_fu_972_p3;
reg   [31:0] ap_sig_allocacmp_calibratedCounts_load_1;
reg   [31:0] ap_sig_allocacmp_calibratedCounts_load_2;
wire   [0:0] icmp_ln83_fu_1152_p2;
wire   [0:0] icmp_ln84_fu_1167_p2;
reg   [31:0] clipCounts_fu_278;
wire   [31:0] result_9_fu_830_p3;
reg    ap_predicate_op292_write_state20;
reg    ap_block_state20;
reg    ap_block_state20_io;
reg    ap_predicate_op309_write_state21;
wire    regslice_both_IN1024OUT8192_V_data_V_U_apdone_blk;
wire    regslice_both_IN2048OUT8192_V_data_V_U_apdone_blk;
wire    regslice_both_IN4096OUT8192_V_data_V_U_apdone_blk;
wire    regslice_both_IN8192OUT65536_V_data_V_U_apdone_blk;
wire    regslice_both_IN16384OUT65536_V_data_V_U_apdone_blk;
wire    regslice_both_IN32768OUT65536_V_data_V_U_apdone_blk;
wire    regslice_both_IN65536OUT262144_V_data_V_U_apdone_blk;
wire    regslice_both_IN131072OUT262144_V_data_V_U_apdone_blk;
wire    regslice_both_IN262144OUT262144_V_data_V_U_apdone_blk;
reg    ap_block_state21;
reg   [31:0] grp_fu_549_p0;
reg   [31:0] grp_fu_549_p1;
reg   [31:0] grp_fu_555_p0;
wire   [31:0] tmp_2_fu_566_p0;
wire    ap_CS_fsm_state16;
wire   [7:0] tmp_1_fu_623_p4;
wire   [22:0] trunc_ln55_fu_633_p1;
wire   [0:0] icmp_ln55_1_fu_643_p2;
wire   [0:0] icmp_ln55_fu_637_p2;
wire   [0:0] or_ln55_fu_649_p2;
wire   [0:0] tmp_2_fu_566_p2;
wire   [31:0] data_2_fu_700_p1;
wire   [22:0] trunc_ln342_1_fu_722_p1;
wire   [24:0] mantissa_2_fu_726_p4;
wire   [7:0] xs_exp_2_fu_712_p4;
wire   [8:0] zext_ln317_1_fu_740_p1;
wire   [8:0] add_ln317_1_fu_744_p2;
wire   [7:0] sub_ln18_2_fu_758_p2;
wire   [0:0] tmp_12_fu_750_p3;
wire  signed [8:0] sext_ln18_4_fu_764_p1;
wire   [8:0] select_ln18_4_fu_768_p3;
wire  signed [31:0] sext_ln18_5_fu_776_p1;
wire   [78:0] zext_ln15_2_fu_736_p1;
wire   [78:0] zext_ln18_2_fu_780_p1;
wire   [78:0] lshr_ln18_2_fu_784_p2;
wire   [78:0] shl_ln18_2_fu_790_p2;
wire   [31:0] tmp_8_fu_796_p4;
wire   [31:0] tmp_9_fu_806_p4;
wire   [31:0] val_2_fu_816_p3;
wire   [0:0] xs_sign_2_fu_704_p3;
wire   [31:0] result_6_fu_824_p2;
wire   [31:0] data_1_fu_843_p1;
wire   [22:0] trunc_ln342_fu_864_p1;
wire   [24:0] mantissa_1_fu_868_p4;
wire   [7:0] xs_exp_1_fu_854_p4;
wire   [8:0] zext_ln317_fu_882_p1;
wire   [8:0] add_ln317_fu_886_p2;
wire   [7:0] sub_ln18_1_fu_900_p2;
wire   [0:0] tmp_10_fu_892_p3;
wire  signed [8:0] sext_ln18_2_fu_906_p1;
wire   [8:0] select_ln18_2_fu_910_p3;
wire  signed [31:0] sext_ln18_3_fu_918_p1;
wire   [78:0] zext_ln15_1_fu_878_p1;
wire   [78:0] zext_ln18_1_fu_922_p1;
wire   [78:0] lshr_ln18_1_fu_926_p2;
wire   [78:0] shl_ln18_1_fu_932_p2;
wire   [31:0] tmp_6_fu_938_p4;
wire   [31:0] tmp_7_fu_948_p4;
wire   [31:0] val_1_fu_958_p3;
wire   [0:0] xs_sign_1_fu_846_p3;
wire   [31:0] result_3_fu_966_p2;
wire   [63:0] data_fu_990_p1;
wire   [51:0] trunc_ln505_fu_1011_p1;
wire   [53:0] mantissa_fu_1015_p4;
wire   [10:0] xs_exp_fu_1001_p4;
wire   [11:0] zext_ln486_fu_1029_p1;
wire   [11:0] add_ln486_fu_1033_p2;
wire   [10:0] sub_ln18_fu_1047_p2;
wire   [0:0] tmp_fu_1039_p3;
wire  signed [11:0] sext_ln18_fu_1053_p1;
wire   [11:0] select_ln18_fu_1057_p3;
wire  signed [31:0] sext_ln18_1_fu_1065_p1;
wire   [136:0] zext_ln15_fu_1025_p1;
wire   [136:0] zext_ln18_fu_1069_p1;
wire   [136:0] lshr_ln18_fu_1073_p2;
wire   [136:0] shl_ln18_fu_1079_p2;
wire   [31:0] tmp_3_fu_1085_p4;
wire   [31:0] tmp_4_fu_1095_p4;
wire   [31:0] val_fu_1105_p3;
wire   [0:0] xs_sign_fu_993_p3;
wire   [31:0] result_2_fu_1113_p2;
wire   [31:0] sub_ln84_fu_1161_p2;
reg    ap_block_state21_io;
reg   [20:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    IN1024OUT8192_TVALID_int_regslice;
wire    IN1024OUT8192_TREADY_int_regslice;
wire    regslice_both_IN1024OUT8192_V_data_V_U_vld_out;
wire    regslice_both_IN1024OUT8192_V_keep_V_U_apdone_blk;
wire   [2:0] IN1024OUT8192_TKEEP_int_regslice;
wire    regslice_both_IN1024OUT8192_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN1024OUT8192_V_keep_V_U_vld_out;
wire    regslice_both_IN1024OUT8192_V_strb_V_U_apdone_blk;
wire   [2:0] IN1024OUT8192_TSTRB_int_regslice;
wire    regslice_both_IN1024OUT8192_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN1024OUT8192_V_strb_V_U_vld_out;
wire    regslice_both_IN1024OUT8192_V_last_V_U_apdone_blk;
wire   [0:0] IN1024OUT8192_TLAST_int_regslice;
wire    regslice_both_IN1024OUT8192_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN1024OUT8192_V_last_V_U_vld_out;
reg    IN2048OUT8192_TVALID_int_regslice;
wire    IN2048OUT8192_TREADY_int_regslice;
wire    regslice_both_IN2048OUT8192_V_data_V_U_vld_out;
wire    regslice_both_IN2048OUT8192_V_keep_V_U_apdone_blk;
wire   [2:0] IN2048OUT8192_TKEEP_int_regslice;
wire    regslice_both_IN2048OUT8192_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN2048OUT8192_V_keep_V_U_vld_out;
wire    regslice_both_IN2048OUT8192_V_strb_V_U_apdone_blk;
wire   [2:0] IN2048OUT8192_TSTRB_int_regslice;
wire    regslice_both_IN2048OUT8192_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN2048OUT8192_V_strb_V_U_vld_out;
wire    regslice_both_IN2048OUT8192_V_last_V_U_apdone_blk;
wire   [0:0] IN2048OUT8192_TLAST_int_regslice;
wire    regslice_both_IN2048OUT8192_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN2048OUT8192_V_last_V_U_vld_out;
reg    IN4096OUT8192_TVALID_int_regslice;
wire    IN4096OUT8192_TREADY_int_regslice;
wire    regslice_both_IN4096OUT8192_V_data_V_U_vld_out;
wire    regslice_both_IN4096OUT8192_V_keep_V_U_apdone_blk;
wire   [2:0] IN4096OUT8192_TKEEP_int_regslice;
wire    regslice_both_IN4096OUT8192_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN4096OUT8192_V_keep_V_U_vld_out;
wire    regslice_both_IN4096OUT8192_V_strb_V_U_apdone_blk;
wire   [2:0] IN4096OUT8192_TSTRB_int_regslice;
wire    regslice_both_IN4096OUT8192_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN4096OUT8192_V_strb_V_U_vld_out;
wire    regslice_both_IN4096OUT8192_V_last_V_U_apdone_blk;
wire   [0:0] IN4096OUT8192_TLAST_int_regslice;
wire    regslice_both_IN4096OUT8192_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN4096OUT8192_V_last_V_U_vld_out;
reg    IN8192OUT65536_TVALID_int_regslice;
wire    IN8192OUT65536_TREADY_int_regslice;
wire    regslice_both_IN8192OUT65536_V_data_V_U_vld_out;
wire    regslice_both_IN8192OUT65536_V_keep_V_U_apdone_blk;
wire   [2:0] IN8192OUT65536_TKEEP_int_regslice;
wire    regslice_both_IN8192OUT65536_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN8192OUT65536_V_keep_V_U_vld_out;
wire    regslice_both_IN8192OUT65536_V_strb_V_U_apdone_blk;
wire   [2:0] IN8192OUT65536_TSTRB_int_regslice;
wire    regslice_both_IN8192OUT65536_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN8192OUT65536_V_strb_V_U_vld_out;
wire    regslice_both_IN8192OUT65536_V_last_V_U_apdone_blk;
wire   [0:0] IN8192OUT65536_TLAST_int_regslice;
wire    regslice_both_IN8192OUT65536_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN8192OUT65536_V_last_V_U_vld_out;
reg    IN16384OUT65536_TVALID_int_regslice;
wire    IN16384OUT65536_TREADY_int_regslice;
wire    regslice_both_IN16384OUT65536_V_data_V_U_vld_out;
wire    regslice_both_IN16384OUT65536_V_keep_V_U_apdone_blk;
wire   [2:0] IN16384OUT65536_TKEEP_int_regslice;
wire    regslice_both_IN16384OUT65536_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN16384OUT65536_V_keep_V_U_vld_out;
wire    regslice_both_IN16384OUT65536_V_strb_V_U_apdone_blk;
wire   [2:0] IN16384OUT65536_TSTRB_int_regslice;
wire    regslice_both_IN16384OUT65536_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN16384OUT65536_V_strb_V_U_vld_out;
wire    regslice_both_IN16384OUT65536_V_last_V_U_apdone_blk;
wire   [0:0] IN16384OUT65536_TLAST_int_regslice;
wire    regslice_both_IN16384OUT65536_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN16384OUT65536_V_last_V_U_vld_out;
reg    IN32768OUT65536_TVALID_int_regslice;
wire    IN32768OUT65536_TREADY_int_regslice;
wire    regslice_both_IN32768OUT65536_V_data_V_U_vld_out;
wire    regslice_both_IN32768OUT65536_V_keep_V_U_apdone_blk;
wire   [2:0] IN32768OUT65536_TKEEP_int_regslice;
wire    regslice_both_IN32768OUT65536_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN32768OUT65536_V_keep_V_U_vld_out;
wire    regslice_both_IN32768OUT65536_V_strb_V_U_apdone_blk;
wire   [2:0] IN32768OUT65536_TSTRB_int_regslice;
wire    regslice_both_IN32768OUT65536_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN32768OUT65536_V_strb_V_U_vld_out;
wire    regslice_both_IN32768OUT65536_V_last_V_U_apdone_blk;
wire   [0:0] IN32768OUT65536_TLAST_int_regslice;
wire    regslice_both_IN32768OUT65536_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN32768OUT65536_V_last_V_U_vld_out;
reg    IN65536OUT262144_TVALID_int_regslice;
wire    IN65536OUT262144_TREADY_int_regslice;
wire    regslice_both_IN65536OUT262144_V_data_V_U_vld_out;
wire    regslice_both_IN65536OUT262144_V_keep_V_U_apdone_blk;
wire   [2:0] IN65536OUT262144_TKEEP_int_regslice;
wire    regslice_both_IN65536OUT262144_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN65536OUT262144_V_keep_V_U_vld_out;
wire    regslice_both_IN65536OUT262144_V_strb_V_U_apdone_blk;
wire   [2:0] IN65536OUT262144_TSTRB_int_regslice;
wire    regslice_both_IN65536OUT262144_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN65536OUT262144_V_strb_V_U_vld_out;
wire    regslice_both_IN65536OUT262144_V_last_V_U_apdone_blk;
wire   [0:0] IN65536OUT262144_TLAST_int_regslice;
wire    regslice_both_IN65536OUT262144_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN65536OUT262144_V_last_V_U_vld_out;
reg    IN131072OUT262144_TVALID_int_regslice;
wire    IN131072OUT262144_TREADY_int_regslice;
wire    regslice_both_IN131072OUT262144_V_data_V_U_vld_out;
wire    regslice_both_IN131072OUT262144_V_keep_V_U_apdone_blk;
wire   [2:0] IN131072OUT262144_TKEEP_int_regslice;
wire    regslice_both_IN131072OUT262144_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN131072OUT262144_V_keep_V_U_vld_out;
wire    regslice_both_IN131072OUT262144_V_strb_V_U_apdone_blk;
wire   [2:0] IN131072OUT262144_TSTRB_int_regslice;
wire    regslice_both_IN131072OUT262144_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN131072OUT262144_V_strb_V_U_vld_out;
wire    regslice_both_IN131072OUT262144_V_last_V_U_apdone_blk;
wire   [0:0] IN131072OUT262144_TLAST_int_regslice;
wire    regslice_both_IN131072OUT262144_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN131072OUT262144_V_last_V_U_vld_out;
reg    IN262144OUT262144_TVALID_int_regslice;
wire    IN262144OUT262144_TREADY_int_regslice;
wire    regslice_both_IN262144OUT262144_V_data_V_U_vld_out;
wire    regslice_both_IN262144OUT262144_V_keep_V_U_apdone_blk;
wire   [2:0] IN262144OUT262144_TKEEP_int_regslice;
wire    regslice_both_IN262144OUT262144_V_keep_V_U_ack_in_dummy;
wire    regslice_both_IN262144OUT262144_V_keep_V_U_vld_out;
wire    regslice_both_IN262144OUT262144_V_strb_V_U_apdone_blk;
wire   [2:0] IN262144OUT262144_TSTRB_int_regslice;
wire    regslice_both_IN262144OUT262144_V_strb_V_U_ack_in_dummy;
wire    regslice_both_IN262144OUT262144_V_strb_V_U_vld_out;
wire    regslice_both_IN262144OUT262144_V_last_V_U_apdone_blk;
wire   [0:0] IN262144OUT262144_TLAST_int_regslice;
wire    regslice_both_IN262144OUT262144_V_last_V_U_ack_in_dummy;
wire    regslice_both_IN262144OUT262144_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 21'd1;
#0 ScaleValue_0_data_reg = 32'd0;
#0 ScaleValue_0_vld_reg = 1'b0;
#0 ZeroCross_0_data_reg = 32'd0;
#0 ZeroCross_0_vld_reg = 1'b0;
#0 samp_index_0_data_reg = 32'd0;
#0 samp_index_0_vld_reg = 1'b0;
#0 iCurrentFilter_0_data_reg = 32'd0;
#0 iCurrentFilter_0_vld_reg = 1'b0;
#0 fClipValue_0_data_reg = 32'd0;
#0 fClipValue_0_vld_reg = 1'b0;
#0 fDACScaleFactor = 32'd935329816;
#0 temp_fu_266 = 32'd0;
#0 offsetCounts_fu_270 = 32'd0;
#0 calibratedCounts_fu_274 = 32'd0;
#0 clipCounts_fu_278 = 32'd0;
end

DriveScale_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ScaleValue(ScaleValue),
    .ZeroCross(ZeroCross),
    .calibratedStep_address0(calibratedStep_address0),
    .calibratedStep_ce0(calibratedStep_ce0),
    .calibratedStep_q0(calibratedStep_q0),
    .calibratedOffset_address0(calibratedOffset_address0),
    .calibratedOffset_ce0(calibratedOffset_ce0),
    .calibratedOffset_q0(calibratedOffset_q0),
    .samp_index(samp_index),
    .iCurrentFilter(iCurrentFilter),
    .fClipValue(fClipValue)
);

DriveScale_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_549_p0),
    .din1(grp_fu_549_p1),
    .ce(1'b1),
    .dout(grp_fu_549_p2)
);

DriveScale_fdiv_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_6_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_555_p0),
    .din1(fDACScaleFactor),
    .ce(1'b1),
    .dout(grp_fu_555_p2)
);

DriveScale_fdiv_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_6_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(reg_593),
    .din1(fDACScaleFactor),
    .ce(1'b1),
    .dout(grp_fu_559_p2)
);

DriveScale_fpext_32ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_1_no_dsp_1_U4(
    .din0(reg_598),
    .dout(conv7_fu_563_p1)
);

DriveScale_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U5(
    .din0(tmp_2_fu_566_p0),
    .din1(32'd0),
    .opcode(5'd1),
    .dout(tmp_2_fu_566_p2)
);

DriveScale_dadd_64ns_64ns_64_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_3_full_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(conv7_reg_1291),
    .din1(64'd4602678819172646912),
    .ce(1'b1),
    .dout(grp_fu_571_p2)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN1024OUT8192_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN1024OUT8192_TVALID_int_regslice),
    .ack_in(IN1024OUT8192_TREADY_int_regslice),
    .data_out(IN1024OUT8192_TDATA),
    .vld_out(regslice_both_IN1024OUT8192_V_data_V_U_vld_out),
    .ack_out(IN1024OUT8192_TREADY),
    .apdone_blk(regslice_both_IN1024OUT8192_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN1024OUT8192_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN1024OUT8192_TKEEP_int_regslice),
    .vld_in(IN1024OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN1024OUT8192_V_keep_V_U_ack_in_dummy),
    .data_out(IN1024OUT8192_TKEEP),
    .vld_out(regslice_both_IN1024OUT8192_V_keep_V_U_vld_out),
    .ack_out(IN1024OUT8192_TREADY),
    .apdone_blk(regslice_both_IN1024OUT8192_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN1024OUT8192_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN1024OUT8192_TSTRB_int_regslice),
    .vld_in(IN1024OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN1024OUT8192_V_strb_V_U_ack_in_dummy),
    .data_out(IN1024OUT8192_TSTRB),
    .vld_out(regslice_both_IN1024OUT8192_V_strb_V_U_vld_out),
    .ack_out(IN1024OUT8192_TREADY),
    .apdone_blk(regslice_both_IN1024OUT8192_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN1024OUT8192_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN1024OUT8192_TLAST_int_regslice),
    .vld_in(IN1024OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN1024OUT8192_V_last_V_U_ack_in_dummy),
    .data_out(IN1024OUT8192_TLAST),
    .vld_out(regslice_both_IN1024OUT8192_V_last_V_U_vld_out),
    .ack_out(IN1024OUT8192_TREADY),
    .apdone_blk(regslice_both_IN1024OUT8192_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN2048OUT8192_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN2048OUT8192_TVALID_int_regslice),
    .ack_in(IN2048OUT8192_TREADY_int_regslice),
    .data_out(IN2048OUT8192_TDATA),
    .vld_out(regslice_both_IN2048OUT8192_V_data_V_U_vld_out),
    .ack_out(IN2048OUT8192_TREADY),
    .apdone_blk(regslice_both_IN2048OUT8192_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN2048OUT8192_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN2048OUT8192_TKEEP_int_regslice),
    .vld_in(IN2048OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN2048OUT8192_V_keep_V_U_ack_in_dummy),
    .data_out(IN2048OUT8192_TKEEP),
    .vld_out(regslice_both_IN2048OUT8192_V_keep_V_U_vld_out),
    .ack_out(IN2048OUT8192_TREADY),
    .apdone_blk(regslice_both_IN2048OUT8192_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN2048OUT8192_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN2048OUT8192_TSTRB_int_regslice),
    .vld_in(IN2048OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN2048OUT8192_V_strb_V_U_ack_in_dummy),
    .data_out(IN2048OUT8192_TSTRB),
    .vld_out(regslice_both_IN2048OUT8192_V_strb_V_U_vld_out),
    .ack_out(IN2048OUT8192_TREADY),
    .apdone_blk(regslice_both_IN2048OUT8192_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN2048OUT8192_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN2048OUT8192_TLAST_int_regslice),
    .vld_in(IN2048OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN2048OUT8192_V_last_V_U_ack_in_dummy),
    .data_out(IN2048OUT8192_TLAST),
    .vld_out(regslice_both_IN2048OUT8192_V_last_V_U_vld_out),
    .ack_out(IN2048OUT8192_TREADY),
    .apdone_blk(regslice_both_IN2048OUT8192_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN4096OUT8192_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN4096OUT8192_TVALID_int_regslice),
    .ack_in(IN4096OUT8192_TREADY_int_regslice),
    .data_out(IN4096OUT8192_TDATA),
    .vld_out(regslice_both_IN4096OUT8192_V_data_V_U_vld_out),
    .ack_out(IN4096OUT8192_TREADY),
    .apdone_blk(regslice_both_IN4096OUT8192_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN4096OUT8192_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN4096OUT8192_TKEEP_int_regslice),
    .vld_in(IN4096OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN4096OUT8192_V_keep_V_U_ack_in_dummy),
    .data_out(IN4096OUT8192_TKEEP),
    .vld_out(regslice_both_IN4096OUT8192_V_keep_V_U_vld_out),
    .ack_out(IN4096OUT8192_TREADY),
    .apdone_blk(regslice_both_IN4096OUT8192_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN4096OUT8192_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN4096OUT8192_TSTRB_int_regslice),
    .vld_in(IN4096OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN4096OUT8192_V_strb_V_U_ack_in_dummy),
    .data_out(IN4096OUT8192_TSTRB),
    .vld_out(regslice_both_IN4096OUT8192_V_strb_V_U_vld_out),
    .ack_out(IN4096OUT8192_TREADY),
    .apdone_blk(regslice_both_IN4096OUT8192_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN4096OUT8192_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN4096OUT8192_TLAST_int_regslice),
    .vld_in(IN4096OUT8192_TVALID_int_regslice),
    .ack_in(regslice_both_IN4096OUT8192_V_last_V_U_ack_in_dummy),
    .data_out(IN4096OUT8192_TLAST),
    .vld_out(regslice_both_IN4096OUT8192_V_last_V_U_vld_out),
    .ack_out(IN4096OUT8192_TREADY),
    .apdone_blk(regslice_both_IN4096OUT8192_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN8192OUT65536_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN8192OUT65536_TVALID_int_regslice),
    .ack_in(IN8192OUT65536_TREADY_int_regslice),
    .data_out(IN8192OUT65536_TDATA),
    .vld_out(regslice_both_IN8192OUT65536_V_data_V_U_vld_out),
    .ack_out(IN8192OUT65536_TREADY),
    .apdone_blk(regslice_both_IN8192OUT65536_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN8192OUT65536_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN8192OUT65536_TKEEP_int_regslice),
    .vld_in(IN8192OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN8192OUT65536_V_keep_V_U_ack_in_dummy),
    .data_out(IN8192OUT65536_TKEEP),
    .vld_out(regslice_both_IN8192OUT65536_V_keep_V_U_vld_out),
    .ack_out(IN8192OUT65536_TREADY),
    .apdone_blk(regslice_both_IN8192OUT65536_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN8192OUT65536_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN8192OUT65536_TSTRB_int_regslice),
    .vld_in(IN8192OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN8192OUT65536_V_strb_V_U_ack_in_dummy),
    .data_out(IN8192OUT65536_TSTRB),
    .vld_out(regslice_both_IN8192OUT65536_V_strb_V_U_vld_out),
    .ack_out(IN8192OUT65536_TREADY),
    .apdone_blk(regslice_both_IN8192OUT65536_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN8192OUT65536_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN8192OUT65536_TLAST_int_regslice),
    .vld_in(IN8192OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN8192OUT65536_V_last_V_U_ack_in_dummy),
    .data_out(IN8192OUT65536_TLAST),
    .vld_out(regslice_both_IN8192OUT65536_V_last_V_U_vld_out),
    .ack_out(IN8192OUT65536_TREADY),
    .apdone_blk(regslice_both_IN8192OUT65536_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN16384OUT65536_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN16384OUT65536_TVALID_int_regslice),
    .ack_in(IN16384OUT65536_TREADY_int_regslice),
    .data_out(IN16384OUT65536_TDATA),
    .vld_out(regslice_both_IN16384OUT65536_V_data_V_U_vld_out),
    .ack_out(IN16384OUT65536_TREADY),
    .apdone_blk(regslice_both_IN16384OUT65536_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN16384OUT65536_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN16384OUT65536_TKEEP_int_regslice),
    .vld_in(IN16384OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN16384OUT65536_V_keep_V_U_ack_in_dummy),
    .data_out(IN16384OUT65536_TKEEP),
    .vld_out(regslice_both_IN16384OUT65536_V_keep_V_U_vld_out),
    .ack_out(IN16384OUT65536_TREADY),
    .apdone_blk(regslice_both_IN16384OUT65536_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN16384OUT65536_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN16384OUT65536_TSTRB_int_regslice),
    .vld_in(IN16384OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN16384OUT65536_V_strb_V_U_ack_in_dummy),
    .data_out(IN16384OUT65536_TSTRB),
    .vld_out(regslice_both_IN16384OUT65536_V_strb_V_U_vld_out),
    .ack_out(IN16384OUT65536_TREADY),
    .apdone_blk(regslice_both_IN16384OUT65536_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN16384OUT65536_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN16384OUT65536_TLAST_int_regslice),
    .vld_in(IN16384OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN16384OUT65536_V_last_V_U_ack_in_dummy),
    .data_out(IN16384OUT65536_TLAST),
    .vld_out(regslice_both_IN16384OUT65536_V_last_V_U_vld_out),
    .ack_out(IN16384OUT65536_TREADY),
    .apdone_blk(regslice_both_IN16384OUT65536_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN32768OUT65536_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN32768OUT65536_TVALID_int_regslice),
    .ack_in(IN32768OUT65536_TREADY_int_regslice),
    .data_out(IN32768OUT65536_TDATA),
    .vld_out(regslice_both_IN32768OUT65536_V_data_V_U_vld_out),
    .ack_out(IN32768OUT65536_TREADY),
    .apdone_blk(regslice_both_IN32768OUT65536_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN32768OUT65536_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN32768OUT65536_TKEEP_int_regslice),
    .vld_in(IN32768OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN32768OUT65536_V_keep_V_U_ack_in_dummy),
    .data_out(IN32768OUT65536_TKEEP),
    .vld_out(regslice_both_IN32768OUT65536_V_keep_V_U_vld_out),
    .ack_out(IN32768OUT65536_TREADY),
    .apdone_blk(regslice_both_IN32768OUT65536_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN32768OUT65536_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN32768OUT65536_TSTRB_int_regslice),
    .vld_in(IN32768OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN32768OUT65536_V_strb_V_U_ack_in_dummy),
    .data_out(IN32768OUT65536_TSTRB),
    .vld_out(regslice_both_IN32768OUT65536_V_strb_V_U_vld_out),
    .ack_out(IN32768OUT65536_TREADY),
    .apdone_blk(regslice_both_IN32768OUT65536_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN32768OUT65536_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN32768OUT65536_TLAST_int_regslice),
    .vld_in(IN32768OUT65536_TVALID_int_regslice),
    .ack_in(regslice_both_IN32768OUT65536_V_last_V_U_ack_in_dummy),
    .data_out(IN32768OUT65536_TLAST),
    .vld_out(regslice_both_IN32768OUT65536_V_last_V_U_vld_out),
    .ack_out(IN32768OUT65536_TREADY),
    .apdone_blk(regslice_both_IN32768OUT65536_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN65536OUT262144_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN65536OUT262144_TVALID_int_regslice),
    .ack_in(IN65536OUT262144_TREADY_int_regslice),
    .data_out(IN65536OUT262144_TDATA),
    .vld_out(regslice_both_IN65536OUT262144_V_data_V_U_vld_out),
    .ack_out(IN65536OUT262144_TREADY),
    .apdone_blk(regslice_both_IN65536OUT262144_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN65536OUT262144_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN65536OUT262144_TKEEP_int_regslice),
    .vld_in(IN65536OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN65536OUT262144_V_keep_V_U_ack_in_dummy),
    .data_out(IN65536OUT262144_TKEEP),
    .vld_out(regslice_both_IN65536OUT262144_V_keep_V_U_vld_out),
    .ack_out(IN65536OUT262144_TREADY),
    .apdone_blk(regslice_both_IN65536OUT262144_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN65536OUT262144_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN65536OUT262144_TSTRB_int_regslice),
    .vld_in(IN65536OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN65536OUT262144_V_strb_V_U_ack_in_dummy),
    .data_out(IN65536OUT262144_TSTRB),
    .vld_out(regslice_both_IN65536OUT262144_V_strb_V_U_vld_out),
    .ack_out(IN65536OUT262144_TREADY),
    .apdone_blk(regslice_both_IN65536OUT262144_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN65536OUT262144_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN65536OUT262144_TLAST_int_regslice),
    .vld_in(IN65536OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN65536OUT262144_V_last_V_U_ack_in_dummy),
    .data_out(IN65536OUT262144_TLAST),
    .vld_out(regslice_both_IN65536OUT262144_V_last_V_U_vld_out),
    .ack_out(IN65536OUT262144_TREADY),
    .apdone_blk(regslice_both_IN65536OUT262144_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN131072OUT262144_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN131072OUT262144_TVALID_int_regslice),
    .ack_in(IN131072OUT262144_TREADY_int_regslice),
    .data_out(IN131072OUT262144_TDATA),
    .vld_out(regslice_both_IN131072OUT262144_V_data_V_U_vld_out),
    .ack_out(IN131072OUT262144_TREADY),
    .apdone_blk(regslice_both_IN131072OUT262144_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN131072OUT262144_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN131072OUT262144_TKEEP_int_regslice),
    .vld_in(IN131072OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN131072OUT262144_V_keep_V_U_ack_in_dummy),
    .data_out(IN131072OUT262144_TKEEP),
    .vld_out(regslice_both_IN131072OUT262144_V_keep_V_U_vld_out),
    .ack_out(IN131072OUT262144_TREADY),
    .apdone_blk(regslice_both_IN131072OUT262144_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN131072OUT262144_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN131072OUT262144_TSTRB_int_regslice),
    .vld_in(IN131072OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN131072OUT262144_V_strb_V_U_ack_in_dummy),
    .data_out(IN131072OUT262144_TSTRB),
    .vld_out(regslice_both_IN131072OUT262144_V_strb_V_U_vld_out),
    .ack_out(IN131072OUT262144_TREADY),
    .apdone_blk(regslice_both_IN131072OUT262144_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN131072OUT262144_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN131072OUT262144_TLAST_int_regslice),
    .vld_in(IN131072OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN131072OUT262144_V_last_V_U_ack_in_dummy),
    .data_out(IN131072OUT262144_TLAST),
    .vld_out(regslice_both_IN131072OUT262144_V_last_V_U_vld_out),
    .ack_out(IN131072OUT262144_TREADY),
    .apdone_blk(regslice_both_IN131072OUT262144_V_last_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 24 ))
regslice_both_IN262144OUT262144_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(DacCounts_fu_1192_p1),
    .vld_in(IN262144OUT262144_TVALID_int_regslice),
    .ack_in(IN262144OUT262144_TREADY_int_regslice),
    .data_out(IN262144OUT262144_TDATA),
    .vld_out(regslice_both_IN262144OUT262144_V_data_V_U_vld_out),
    .ack_out(IN262144OUT262144_TREADY),
    .apdone_blk(regslice_both_IN262144OUT262144_V_data_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN262144OUT262144_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN262144OUT262144_TKEEP_int_regslice),
    .vld_in(IN262144OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN262144OUT262144_V_keep_V_U_ack_in_dummy),
    .data_out(IN262144OUT262144_TKEEP),
    .vld_out(regslice_both_IN262144OUT262144_V_keep_V_U_vld_out),
    .ack_out(IN262144OUT262144_TREADY),
    .apdone_blk(regslice_both_IN262144OUT262144_V_keep_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 3 ))
regslice_both_IN262144OUT262144_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN262144OUT262144_TSTRB_int_regslice),
    .vld_in(IN262144OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN262144OUT262144_V_strb_V_U_ack_in_dummy),
    .data_out(IN262144OUT262144_TSTRB),
    .vld_out(regslice_both_IN262144OUT262144_V_strb_V_U_vld_out),
    .ack_out(IN262144OUT262144_TREADY),
    .apdone_blk(regslice_both_IN262144OUT262144_V_strb_V_U_apdone_blk)
);

DriveScale_regslice_both #(
    .DataWidth( 1 ))
regslice_both_IN262144OUT262144_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(IN262144OUT262144_TLAST_int_regslice),
    .vld_in(IN262144OUT262144_TVALID_int_regslice),
    .ack_in(regslice_both_IN262144OUT262144_V_last_V_U_ack_in_dummy),
    .data_out(IN262144OUT262144_TLAST),
    .vld_out(regslice_both_IN262144OUT262144_V_last_V_U_vld_out),
    .ack_out(IN262144OUT262144_TREADY),
    .apdone_blk(regslice_both_IN262144OUT262144_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        calibratedCounts_fu_274 <= result_fu_972_p3;
    end else if (((icmp_ln83_fu_1152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        calibratedCounts_fu_274 <= clipCounts_fu_278;
    end else if (((icmp_ln84_fu_1167_p2 == 1'd1) & (icmp_ln83_fu_1152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        calibratedCounts_fu_274 <= calibratedCounts_4_fu_1176_p2;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        calibratedCounts_fu_274 <= calibratedCounts_2_fu_1135_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_603_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_537 <= 32'd0;
    end else if (((icmp_ln51_reg_1245 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        empty_reg_537 <= bitcast_ln52_fu_609_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == ScaleValue_0_ack_out) & (1'b1 == 1'b1) & (1'b1 == ScaleValue_0_vld_reg)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == ScaleValue_0_vld_reg) & (1'b1 == 1'b1)))) begin
        ScaleValue_0_data_reg <= ScaleValue;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == ZeroCross_0_ack_out) & (1'b1 == 1'b1) & (1'b1 == ZeroCross_0_vld_reg)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b0 == ZeroCross_0_vld_reg) & (1'b1 == 1'b1)))) begin
        ZeroCross_0_data_reg <= ZeroCross;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln55_reg_1259 <= and_ln55_fu_655_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        clipCounts_fu_278 <= result_9_fu_830_p3;
        dc_1_reg_1286 <= grp_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        conv7_reg_1291 <= conv7_fu_563_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        dc_reg_1296 <= grp_fu_571_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (fClipValue_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (fClipValue_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (fClipValue_0_vld_reg == 1'b0)))) begin
        fClipValue_0_data_reg <= fClipValue;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln55_reg_1259) & (1'b1 == ap_CS_fsm_state7))) begin
        fDACScaleFactor <= bitcast_ln56_fu_666_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (iCurrentFilter_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (iCurrentFilter_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (iCurrentFilter_0_vld_reg == 1'b0)))) begin
        iCurrentFilter_0_data_reg <= iCurrentFilter;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln51_reg_1245 <= icmp_ln51_fu_603_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        index_reg_1320 <= samp_index_0_data_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        offsetCounts_fu_270 <= result_8_fu_1119_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_593 <= grp_fu_549_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        reg_598 <= grp_fu_555_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (samp_index_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (samp_index_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (samp_index_0_vld_reg == 1'b0)))) begin
        samp_index_0_data_reg <= samp_index;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_fu_266 <= input_r;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd0) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd0) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN1024OUT8192_TDATA_blk_n = IN1024OUT8192_TREADY_int_regslice;
    end else begin
        IN1024OUT8192_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        IN1024OUT8192_TVALID_int_regslice = 1'b1;
    end else begin
        IN1024OUT8192_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd7) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd7) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN131072OUT262144_TDATA_blk_n = IN131072OUT262144_TREADY_int_regslice;
    end else begin
        IN131072OUT262144_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd7) & (1'b1 == ap_CS_fsm_state20))) begin
        IN131072OUT262144_TVALID_int_regslice = 1'b1;
    end else begin
        IN131072OUT262144_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd4) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd4) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN16384OUT65536_TDATA_blk_n = IN16384OUT65536_TREADY_int_regslice;
    end else begin
        IN16384OUT65536_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd4) & (1'b1 == ap_CS_fsm_state20))) begin
        IN16384OUT65536_TVALID_int_regslice = 1'b1;
    end else begin
        IN16384OUT65536_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd1) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd1) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN2048OUT8192_TDATA_blk_n = IN2048OUT8192_TREADY_int_regslice;
    end else begin
        IN2048OUT8192_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        IN2048OUT8192_TVALID_int_regslice = 1'b1;
    end else begin
        IN2048OUT8192_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((~(index_reg_1320 == 32'd7) & ~(index_reg_1320 == 32'd6) & ~(index_reg_1320 == 32'd5) & ~(index_reg_1320 == 32'd4) & ~(index_reg_1320 == 32'd3) & ~(index_reg_1320 == 32'd2) & ~(index_reg_1320 == 32'd1) & ~(index_reg_1320 == 32'd0) & (1'b1 == ap_CS_fsm_state21)) | (~(samp_index_0_data_reg == 32'd7) & ~(samp_index_0_data_reg == 32'd6) & ~(samp_index_0_data_reg == 32'd5) & ~(samp_index_0_data_reg == 32'd4) & ~(samp_index_0_data_reg == 32'd3) & ~(samp_index_0_data_reg == 32'd2) & ~(samp_index_0_data_reg == 32'd1) & ~(samp_index_0_data_reg == 32'd0) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN262144OUT262144_TDATA_blk_n = IN262144OUT262144_TREADY_int_regslice;
    end else begin
        IN262144OUT262144_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (ap_predicate_op292_write_state20 == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        IN262144OUT262144_TVALID_int_regslice = 1'b1;
    end else begin
        IN262144OUT262144_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd5) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd5) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN32768OUT65536_TDATA_blk_n = IN32768OUT65536_TREADY_int_regslice;
    end else begin
        IN32768OUT65536_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd5) & (1'b1 == ap_CS_fsm_state20))) begin
        IN32768OUT65536_TVALID_int_regslice = 1'b1;
    end else begin
        IN32768OUT65536_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd2) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd2) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN4096OUT8192_TDATA_blk_n = IN4096OUT8192_TREADY_int_regslice;
    end else begin
        IN4096OUT8192_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd2) & (1'b1 == ap_CS_fsm_state20))) begin
        IN4096OUT8192_TVALID_int_regslice = 1'b1;
    end else begin
        IN4096OUT8192_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd6) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd6) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN65536OUT262144_TDATA_blk_n = IN65536OUT262144_TREADY_int_regslice;
    end else begin
        IN65536OUT262144_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd6) & (1'b1 == ap_CS_fsm_state20))) begin
        IN65536OUT262144_TVALID_int_regslice = 1'b1;
    end else begin
        IN65536OUT262144_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((index_reg_1320 == 32'd3) & (1'b1 == ap_CS_fsm_state21)) | ((samp_index_0_data_reg == 32'd3) & (1'b1 == ap_CS_fsm_state20)))) begin
        IN8192OUT65536_TDATA_blk_n = IN8192OUT65536_TREADY_int_regslice;
    end else begin
        IN8192OUT65536_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (samp_index_0_data_reg == 32'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        IN8192OUT65536_TVALID_int_regslice = 1'b1;
    end else begin
        IN8192OUT65536_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln51_reg_1245 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | (~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21)))) begin
        ScaleValue_0_ack_out = 1'b1;
    end else begin
        ScaleValue_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21)))) begin
        ZeroCross_0_ack_out = 1'b1;
    end else begin
        ZeroCross_0_ack_out = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20))) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io))) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ap_sig_allocacmp_calibratedCounts_load_1 = calibratedCounts_2_fu_1135_p2;
    end else begin
        ap_sig_allocacmp_calibratedCounts_load_1 = calibratedCounts_fu_274;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ap_sig_allocacmp_calibratedCounts_load_2 = calibratedCounts_2_fu_1135_p2;
    end else begin
        ap_sig_allocacmp_calibratedCounts_load_2 = calibratedCounts_fu_274;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ap_sig_allocacmp_offsetCounts_load = result_8_fu_1119_p3;
    end else begin
        ap_sig_allocacmp_offsetCounts_load = offsetCounts_fu_270;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_sig_allocacmp_temp_load_1 = input_r;
    end else begin
        ap_sig_allocacmp_temp_load_1 = temp_fu_266;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        calibratedOffset_ce0 = 1'b1;
    end else begin
        calibratedOffset_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        calibratedStep_address0 = zext_ln56_fu_661_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        calibratedStep_address0 = zext_ln55_fu_613_p1;
    end else begin
        calibratedStep_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4))) begin
        calibratedStep_ce0 = 1'b1;
    end else begin
        calibratedStep_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21)))) begin
        fClipValue_0_ack_out = 1'b1;
    end else begin
        fClipValue_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_549_p0 = grp_load_fu_576_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_549_p0 = empty_reg_537;
    end else begin
        grp_fu_549_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_549_p1 = empty_reg_537;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_549_p1 = grp_load_fu_576_p1;
    end else begin
        grp_fu_549_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_555_p0 = bitcast_ln79_fu_695_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_555_p0 = bitcast_ln82_fu_690_p1;
    end else begin
        grp_fu_555_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_load_fu_576_p1 = temp_fu_266;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_load_fu_576_p1 = ap_sig_allocacmp_temp_load_1;
    end else begin
        grp_load_fu_576_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state8) | (~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21)))) begin
        iCurrentFilter_0_ack_out = 1'b1;
    end else begin
        iCurrentFilter_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        loopback_ap_vld = 1'b1;
    end else begin
        loopback_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (1'b1 == ap_CS_fsm_state20)) | (~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21)))) begin
        samp_index_0_ack_out = 1'b1;
    end else begin
        samp_index_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'd1 == and_ln55_fu_655_p2) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if ((~((1'b1 == ap_block_state20_io) | (1'b1 == ap_block_state20)) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if ((~((1'b1 == ap_block_state21) | (1'b1 == ap_block_state21_io)) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DacCounts_fu_1192_p1 = calibratedCounts_fu_274[23:0];

assign IN1024OUT8192_TKEEP_int_regslice = 'bx;

assign IN1024OUT8192_TLAST_int_regslice = 'bx;

assign IN1024OUT8192_TSTRB_int_regslice = 'bx;

assign IN1024OUT8192_TVALID = regslice_both_IN1024OUT8192_V_data_V_U_vld_out;

assign IN131072OUT262144_TKEEP_int_regslice = 'bx;

assign IN131072OUT262144_TLAST_int_regslice = 'bx;

assign IN131072OUT262144_TSTRB_int_regslice = 'bx;

assign IN131072OUT262144_TVALID = regslice_both_IN131072OUT262144_V_data_V_U_vld_out;

assign IN16384OUT65536_TKEEP_int_regslice = 'bx;

assign IN16384OUT65536_TLAST_int_regslice = 'bx;

assign IN16384OUT65536_TSTRB_int_regslice = 'bx;

assign IN16384OUT65536_TVALID = regslice_both_IN16384OUT65536_V_data_V_U_vld_out;

assign IN2048OUT8192_TKEEP_int_regslice = 'bx;

assign IN2048OUT8192_TLAST_int_regslice = 'bx;

assign IN2048OUT8192_TSTRB_int_regslice = 'bx;

assign IN2048OUT8192_TVALID = regslice_both_IN2048OUT8192_V_data_V_U_vld_out;

assign IN262144OUT262144_TKEEP_int_regslice = 'bx;

assign IN262144OUT262144_TLAST_int_regslice = 'bx;

assign IN262144OUT262144_TSTRB_int_regslice = 'bx;

assign IN262144OUT262144_TVALID = regslice_both_IN262144OUT262144_V_data_V_U_vld_out;

assign IN32768OUT65536_TKEEP_int_regslice = 'bx;

assign IN32768OUT65536_TLAST_int_regslice = 'bx;

assign IN32768OUT65536_TSTRB_int_regslice = 'bx;

assign IN32768OUT65536_TVALID = regslice_both_IN32768OUT65536_V_data_V_U_vld_out;

assign IN4096OUT8192_TKEEP_int_regslice = 'bx;

assign IN4096OUT8192_TLAST_int_regslice = 'bx;

assign IN4096OUT8192_TSTRB_int_regslice = 'bx;

assign IN4096OUT8192_TVALID = regslice_both_IN4096OUT8192_V_data_V_U_vld_out;

assign IN65536OUT262144_TKEEP_int_regslice = 'bx;

assign IN65536OUT262144_TLAST_int_regslice = 'bx;

assign IN65536OUT262144_TSTRB_int_regslice = 'bx;

assign IN65536OUT262144_TVALID = regslice_both_IN65536OUT262144_V_data_V_U_vld_out;

assign IN8192OUT65536_TKEEP_int_regslice = 'bx;

assign IN8192OUT65536_TLAST_int_regslice = 'bx;

assign IN8192OUT65536_TSTRB_int_regslice = 'bx;

assign IN8192OUT65536_TVALID = regslice_both_IN8192OUT65536_V_data_V_U_vld_out;

assign add_ln317_1_fu_744_p2 = ($signed(zext_ln317_1_fu_740_p1) + $signed(9'd385));

assign add_ln317_fu_886_p2 = ($signed(zext_ln317_fu_882_p1) + $signed(9'd385));

assign add_ln486_fu_1033_p2 = ($signed(zext_ln486_fu_1029_p1) + $signed(12'd3073));

assign and_ln55_fu_655_p2 = (tmp_2_fu_566_p2 & or_ln55_fu_649_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state20 = (((ap_predicate_op292_write_state20 == 1'b1) & (1'b0 == IN262144OUT262144_TREADY_int_regslice)) | ((1'b0 == IN131072OUT262144_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd7)) | ((1'b0 == IN65536OUT262144_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd6)) | ((1'b0 == IN32768OUT65536_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd5)) | ((1'b0 == IN16384OUT65536_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd4)) | ((1'b0 == IN8192OUT65536_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd3)) | ((1'b0 == IN4096OUT8192_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd2)) | ((1'b0 == IN2048OUT8192_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd1)) | ((1'b0 == IN1024OUT8192_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd0)));
end

always @ (*) begin
    ap_block_state20_io = (((ap_predicate_op292_write_state20 == 1'b1) & (1'b0 == IN262144OUT262144_TREADY_int_regslice)) | ((1'b0 == IN131072OUT262144_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd7)) | ((1'b0 == IN65536OUT262144_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd6)) | ((1'b0 == IN32768OUT65536_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd5)) | ((1'b0 == IN16384OUT65536_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd4)) | ((1'b0 == IN8192OUT65536_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd3)) | ((1'b0 == IN4096OUT8192_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd2)) | ((1'b0 == IN2048OUT8192_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd1)) | ((1'b0 == IN1024OUT8192_TREADY_int_regslice) & (samp_index_0_data_reg == 32'd0)));
end

always @ (*) begin
    ap_block_state21 = ((regslice_both_IN262144OUT262144_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN131072OUT262144_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN65536OUT262144_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN32768OUT65536_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN16384OUT65536_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN8192OUT65536_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN4096OUT8192_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN2048OUT8192_V_data_V_U_apdone_blk == 1'b1) | (regslice_both_IN1024OUT8192_V_data_V_U_apdone_blk == 1'b1) | ((ap_predicate_op309_write_state21 == 1'b1) & (1'b0 == IN262144OUT262144_TREADY_int_regslice)) | ((1'b0 == IN131072OUT262144_TREADY_int_regslice) & (index_reg_1320 == 32'd7)) | ((1'b0 == IN65536OUT262144_TREADY_int_regslice) & (index_reg_1320 == 32'd6)) | ((1'b0 == IN32768OUT65536_TREADY_int_regslice) & (index_reg_1320 == 32'd5)) | ((1'b0 == IN16384OUT65536_TREADY_int_regslice) & (index_reg_1320 == 32'd4)) | ((1'b0 == IN8192OUT65536_TREADY_int_regslice) 
    & (index_reg_1320 == 32'd3)) | ((1'b0 == IN4096OUT8192_TREADY_int_regslice) & (index_reg_1320 == 32'd2)) | ((1'b0 == IN2048OUT8192_TREADY_int_regslice) & (index_reg_1320 == 32'd1)) | ((1'b0 == IN1024OUT8192_TREADY_int_regslice) & (index_reg_1320 == 32'd0)));
end

always @ (*) begin
    ap_block_state21_io = (((ap_predicate_op309_write_state21 == 1'b1) & (1'b0 == IN262144OUT262144_TREADY_int_regslice)) | ((1'b0 == IN131072OUT262144_TREADY_int_regslice) & (index_reg_1320 == 32'd7)) | ((1'b0 == IN65536OUT262144_TREADY_int_regslice) & (index_reg_1320 == 32'd6)) | ((1'b0 == IN32768OUT65536_TREADY_int_regslice) & (index_reg_1320 == 32'd5)) | ((1'b0 == IN16384OUT65536_TREADY_int_regslice) & (index_reg_1320 == 32'd4)) | ((1'b0 == IN8192OUT65536_TREADY_int_regslice) & (index_reg_1320 == 32'd3)) | ((1'b0 == IN4096OUT8192_TREADY_int_regslice) & (index_reg_1320 == 32'd2)) | ((1'b0 == IN2048OUT8192_TREADY_int_regslice) & (index_reg_1320 == 32'd1)) | ((1'b0 == IN1024OUT8192_TREADY_int_regslice) & (index_reg_1320 == 32'd0)));
end

always @ (*) begin
    ap_predicate_op292_write_state20 = (~(samp_index_0_data_reg == 32'd7) & ~(samp_index_0_data_reg == 32'd6) & ~(samp_index_0_data_reg == 32'd5) & ~(samp_index_0_data_reg == 32'd4) & ~(samp_index_0_data_reg == 32'd3) & ~(samp_index_0_data_reg == 32'd2) & ~(samp_index_0_data_reg == 32'd1) & ~(samp_index_0_data_reg == 32'd0));
end

always @ (*) begin
    ap_predicate_op309_write_state21 = (~(index_reg_1320 == 32'd7) & ~(index_reg_1320 == 32'd6) & ~(index_reg_1320 == 32'd5) & ~(index_reg_1320 == 32'd4) & ~(index_reg_1320 == 32'd3) & ~(index_reg_1320 == 32'd2) & ~(index_reg_1320 == 32'd1) & ~(index_reg_1320 == 32'd0));
end

assign ap_return = reg_593;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln52_fu_609_p1 = ScaleValue_0_data_reg;

assign bitcast_ln56_fu_666_p1 = calibratedStep_q0;

assign bitcast_ln79_fu_695_p1 = calibratedOffset_q0;

assign bitcast_ln82_fu_690_p1 = fClipValue_0_data_reg;

assign calibratedCounts_2_fu_1135_p2 = (calibratedCounts_fu_274 - ap_sig_allocacmp_offsetCounts_load);

assign calibratedCounts_4_fu_1176_p2 = (32'd0 - clipCounts_fu_278);

assign calibratedOffset_address0 = zext_ln79_fu_680_p1;

assign data_1_fu_843_p1 = dc_1_reg_1286;

assign data_2_fu_700_p1 = reg_598;

assign data_fu_990_p1 = dc_reg_1296;

assign icmp_ln51_fu_603_p2 = ((ZeroCross_0_data_reg == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_643_p2 = ((trunc_ln55_fu_633_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_637_p2 = ((tmp_1_fu_623_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_1152_p2 = (($signed(ap_sig_allocacmp_calibratedCounts_load_1) > $signed(clipCounts_fu_278)) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_1167_p2 = (($signed(ap_sig_allocacmp_calibratedCounts_load_2) < $signed(sub_ln84_fu_1161_p2)) ? 1'b1 : 1'b0);

assign interp = index_reg_1320[3:0];

assign loopback = grp_fu_549_p2;

assign lshr_ln18_1_fu_926_p2 = zext_ln15_1_fu_878_p1 >> zext_ln18_1_fu_922_p1;

assign lshr_ln18_2_fu_784_p2 = zext_ln15_2_fu_736_p1 >> zext_ln18_2_fu_780_p1;

assign lshr_ln18_fu_1073_p2 = zext_ln15_fu_1025_p1 >> zext_ln18_fu_1069_p1;

assign mantissa_1_fu_868_p4 = {{{{1'd1}, {trunc_ln342_fu_864_p1}}}, {1'd0}};

assign mantissa_2_fu_726_p4 = {{{{1'd1}, {trunc_ln342_1_fu_722_p1}}}, {1'd0}};

assign mantissa_fu_1015_p4 = {{{{1'd1}, {trunc_ln505_fu_1011_p1}}}, {1'd0}};

assign or_ln55_fu_649_p2 = (icmp_ln55_fu_637_p2 | icmp_ln55_1_fu_643_p2);

assign result_2_fu_1113_p2 = (32'd0 - val_fu_1105_p3);

assign result_3_fu_966_p2 = (32'd0 - val_1_fu_958_p3);

assign result_6_fu_824_p2 = (32'd0 - val_2_fu_816_p3);

assign result_8_fu_1119_p3 = ((xs_sign_fu_993_p3[0:0] == 1'b1) ? result_2_fu_1113_p2 : val_fu_1105_p3);

assign result_9_fu_830_p3 = ((xs_sign_2_fu_704_p3[0:0] == 1'b1) ? result_6_fu_824_p2 : val_2_fu_816_p3);

assign result_fu_972_p3 = ((xs_sign_1_fu_846_p3[0:0] == 1'b1) ? result_3_fu_966_p2 : val_1_fu_958_p3);

assign select_ln18_2_fu_910_p3 = ((tmp_10_fu_892_p3[0:0] == 1'b1) ? sext_ln18_2_fu_906_p1 : add_ln317_fu_886_p2);

assign select_ln18_4_fu_768_p3 = ((tmp_12_fu_750_p3[0:0] == 1'b1) ? sext_ln18_4_fu_764_p1 : add_ln317_1_fu_744_p2);

assign select_ln18_fu_1057_p3 = ((tmp_fu_1039_p3[0:0] == 1'b1) ? sext_ln18_fu_1053_p1 : add_ln486_fu_1033_p2);

assign sext_ln18_1_fu_1065_p1 = $signed(select_ln18_fu_1057_p3);

assign sext_ln18_2_fu_906_p1 = $signed(sub_ln18_1_fu_900_p2);

assign sext_ln18_3_fu_918_p1 = $signed(select_ln18_2_fu_910_p3);

assign sext_ln18_4_fu_764_p1 = $signed(sub_ln18_2_fu_758_p2);

assign sext_ln18_5_fu_776_p1 = $signed(select_ln18_4_fu_768_p3);

assign sext_ln18_fu_1053_p1 = $signed(sub_ln18_fu_1047_p2);

assign shl_ln18_1_fu_932_p2 = zext_ln15_1_fu_878_p1 << zext_ln18_1_fu_922_p1;

assign shl_ln18_2_fu_790_p2 = zext_ln15_2_fu_736_p1 << zext_ln18_2_fu_780_p1;

assign shl_ln18_fu_1079_p2 = zext_ln15_fu_1025_p1 << zext_ln18_fu_1069_p1;

assign sub_ln18_1_fu_900_p2 = (8'd127 - xs_exp_1_fu_854_p4);

assign sub_ln18_2_fu_758_p2 = (8'd127 - xs_exp_2_fu_712_p4);

assign sub_ln18_fu_1047_p2 = (11'd1023 - xs_exp_fu_1001_p4);

assign sub_ln84_fu_1161_p2 = (32'd0 - clipCounts_fu_278);

assign tmp_10_fu_892_p3 = add_ln317_fu_886_p2[32'd8];

assign tmp_12_fu_750_p3 = add_ln317_1_fu_744_p2[32'd8];

assign tmp_1_fu_623_p4 = {{calibratedStep_q0[30:23]}};

assign tmp_2_fu_566_p0 = calibratedStep_q0;

assign tmp_3_fu_1085_p4 = {{lshr_ln18_fu_1073_p2[84:53]}};

assign tmp_4_fu_1095_p4 = {{shl_ln18_fu_1079_p2[84:53]}};

assign tmp_6_fu_938_p4 = {{lshr_ln18_1_fu_926_p2[55:24]}};

assign tmp_7_fu_948_p4 = {{shl_ln18_1_fu_932_p2[55:24]}};

assign tmp_8_fu_796_p4 = {{lshr_ln18_2_fu_784_p2[55:24]}};

assign tmp_9_fu_806_p4 = {{shl_ln18_2_fu_790_p2[55:24]}};

assign tmp_fu_1039_p3 = add_ln486_fu_1033_p2[32'd11];

assign trunc_ln342_1_fu_722_p1 = data_2_fu_700_p1[22:0];

assign trunc_ln342_fu_864_p1 = data_1_fu_843_p1[22:0];

assign trunc_ln505_fu_1011_p1 = data_fu_990_p1[51:0];

assign trunc_ln55_fu_633_p1 = calibratedStep_q0[22:0];

assign val_1_fu_958_p3 = ((tmp_10_fu_892_p3[0:0] == 1'b1) ? tmp_6_fu_938_p4 : tmp_7_fu_948_p4);

assign val_2_fu_816_p3 = ((tmp_12_fu_750_p3[0:0] == 1'b1) ? tmp_8_fu_796_p4 : tmp_9_fu_806_p4);

assign val_fu_1105_p3 = ((tmp_fu_1039_p3[0:0] == 1'b1) ? tmp_3_fu_1085_p4 : tmp_4_fu_1095_p4);

assign xs_exp_1_fu_854_p4 = {{data_1_fu_843_p1[30:23]}};

assign xs_exp_2_fu_712_p4 = {{data_2_fu_700_p1[30:23]}};

assign xs_exp_fu_1001_p4 = {{data_fu_990_p1[62:52]}};

assign xs_sign_1_fu_846_p3 = data_1_fu_843_p1[32'd31];

assign xs_sign_2_fu_704_p3 = data_2_fu_700_p1[32'd31];

assign xs_sign_fu_993_p3 = data_fu_990_p1[32'd63];

assign zext_ln15_1_fu_878_p1 = mantissa_1_fu_868_p4;

assign zext_ln15_2_fu_736_p1 = mantissa_2_fu_726_p4;

assign zext_ln15_fu_1025_p1 = mantissa_fu_1015_p4;

assign zext_ln18_1_fu_922_p1 = $unsigned(sext_ln18_3_fu_918_p1);

assign zext_ln18_2_fu_780_p1 = $unsigned(sext_ln18_5_fu_776_p1);

assign zext_ln18_fu_1069_p1 = $unsigned(sext_ln18_1_fu_1065_p1);

assign zext_ln317_1_fu_740_p1 = xs_exp_2_fu_712_p4;

assign zext_ln317_fu_882_p1 = xs_exp_1_fu_854_p4;

assign zext_ln486_fu_1029_p1 = xs_exp_fu_1001_p4;

assign zext_ln55_fu_613_p1 = iCurrentFilter_0_data_reg;

assign zext_ln56_fu_661_p1 = iCurrentFilter_0_data_reg;

assign zext_ln79_fu_680_p1 = iCurrentFilter_0_data_reg;


reg find_kernel_block = 0;
// synthesis translate_off
`include "DriveScale_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //DriveScale

