-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Synch is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    spiSync : IN STD_LOGIC_VECTOR (0 downto 0);
    bSynch : OUT STD_LOGIC_VECTOR (0 downto 0);
    bSynch_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of Synch is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Synch_Synch,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=30.302999,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.706000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=139,HLS_SYN_LUT=249,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1_2 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0_3 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1_4 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0_5 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bufStart : STD_LOGIC_VECTOR (31 downto 0);
    signal bufStart_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bufStart_0_vld_reg : STD_LOGIC := '0';
    signal bufStart_0_ack_out : STD_LOGIC;
    signal bSpuriousSynch_i : STD_LOGIC_VECTOR (0 downto 0);
    signal bSpuriousSynch_0_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal bSpuriousSynch_0_vld_reg : STD_LOGIC := '0';
    signal bSpuriousSynch_0_ack_out : STD_LOGIC;
    signal bSpuriousSynch_1_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal bSpuriousSynch_1_vld_reg : STD_LOGIC := '0';
    signal bSpuriousSynch_1_vld_in : STD_LOGIC;
    signal bSpuriousSynch_1_ack_in : STD_LOGIC;
    signal bRunningAcq : STD_LOGIC_VECTOR (0 downto 0);
    signal bRunningAcq_0_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal bRunningAcq_0_vld_reg : STD_LOGIC := '0';
    signal bRunningAcq_0_ack_out : STD_LOGIC;
    signal bSpuriousSynchLastIn : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal bCurrentSynch : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal SpiSyncLast : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal bStarted : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal SyncStarted : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal grp_read_fu_82_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bRunningAcq_read_reg_260 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_load_fu_132_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_phi_mux_retval_0_phi_fu_111_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_reg_108 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln51_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln29_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_bCurrentSynch_load : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_fu_117_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_fu_120_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_fu_123_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal SyncStarted_load_load_fu_167_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_SyncStarted_load : STD_LOGIC_VECTOR (0 downto 0);
    signal spiSync_assign_fu_66 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal xor_ln29_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_condition_320 : BOOLEAN;
    signal ap_condition_233 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component Synch_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        bufStart : OUT STD_LOGIC_VECTOR (31 downto 0);
        bSpuriousSynch_o : IN STD_LOGIC_VECTOR (0 downto 0);
        bSpuriousSynch_o_ap_vld : IN STD_LOGIC;
        bSpuriousSynch_i : OUT STD_LOGIC_VECTOR (0 downto 0);
        bRunningAcq : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    control_s_axi_U : component Synch_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        bufStart => bufStart,
        bSpuriousSynch_o => bSpuriousSynch_1_data_reg,
        bSpuriousSynch_o_ap_vld => bSpuriousSynch_1_vld_reg,
        bSpuriousSynch_i => bSpuriousSynch_i,
        bRunningAcq => bRunningAcq);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    SpiSyncLast_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln51_fu_143_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then 
                SpiSyncLast <= ap_const_lv1_0_5;
            elsif (((grp_load_fu_117_p1 = ap_const_lv1_1) and (icmp_ln51_fu_143_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then 
                SpiSyncLast <= ap_const_lv1_1_4;
            elsif (((grp_load_fu_123_p1 = ap_const_lv1_1) and (grp_load_fu_120_p1 = ap_const_lv1_0) and (grp_load_fu_117_p1 = ap_const_lv1_0) and (icmp_ln51_fu_143_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then 
                SpiSyncLast <= ap_const_lv1_0_3;
            elsif (((grp_load_fu_117_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                SpiSyncLast <= ap_const_lv1_1_2;
            elsif (((grp_load_fu_123_p1 = ap_const_lv1_1) and (grp_load_fu_120_p1 = ap_const_lv1_0) and (grp_load_fu_117_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                SpiSyncLast <= ap_const_lv1_0_1;
            end if; 
        end if;
    end process;

    SyncStarted_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then
                if ((icmp_ln51_fu_143_p2 = ap_const_lv1_1)) then 
                    SyncStarted <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_320)) then 
                    SyncStarted <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    bCurrentSynch_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_load_fu_123_p1 = ap_const_lv1_1) and (grp_load_fu_120_p1 = ap_const_lv1_0) and (grp_load_fu_117_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                bCurrentSynch <= ap_const_lv1_1;
            elsif ((((or_ln29_fu_217_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln51_fu_143_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0)))) then 
                bCurrentSynch <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    bRunningAcq_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    bSpuriousSynchLastIn_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln51_fu_143_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then 
                bSpuriousSynchLastIn <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                bSpuriousSynchLastIn <= bSpuriousSynch_0_data_reg;
            end if; 
        end if;
    end process;

    bSpuriousSynch_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    bSpuriousSynch_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (bSpuriousSynch_1_vld_in = ap_const_logic_1) and (bSpuriousSynch_1_vld_reg = ap_const_logic_0))) then 
                bSpuriousSynch_1_vld_reg <= ap_const_logic_1;
            elsif (((ap_const_logic_1 = ap_const_logic_1) and (bSpuriousSynch_1_vld_in = ap_const_logic_0) and (bSpuriousSynch_1_vld_reg = ap_const_logic_1))) then 
                bSpuriousSynch_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;

    bStarted_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then
                if ((icmp_ln51_fu_143_p2 = ap_const_lv1_1)) then 
                    bStarted <= ap_const_lv1_0;
                elsif (((icmp_ln51_fu_143_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = SyncStarted_load_load_fu_167_p1))) then 
                    bStarted <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    bufStart_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (bRunningAcq_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (bRunningAcq_0_vld_reg = ap_const_logic_1)) or (not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_const_logic_1) and (bRunningAcq_0_vld_reg = ap_const_logic_0)))) then
                bRunningAcq_0_data_reg <= bRunningAcq;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bRunningAcq_read_reg_260 <= bRunningAcq_0_data_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (bSpuriousSynch_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (bSpuriousSynch_0_vld_reg = ap_const_logic_1)) or (not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_const_logic_1) and (bSpuriousSynch_0_vld_reg = ap_const_logic_0)))) then
                bSpuriousSynch_0_data_reg <= bSpuriousSynch_i;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_const_logic_1) and (bSpuriousSynch_1_vld_in = ap_const_logic_1) and (bSpuriousSynch_1_vld_reg = ap_const_logic_1)) or (not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (bSpuriousSynch_1_vld_in = ap_const_logic_1) and (bSpuriousSynch_1_vld_reg = ap_const_logic_0)))) then
                bSpuriousSynch_1_data_reg <= grp_load_fu_132_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (bufStart_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (bufStart_0_vld_reg = ap_const_logic_1)) or (not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_const_logic_1) and (bufStart_0_vld_reg = ap_const_logic_0)))) then
                bufStart_0_data_reg <= bufStart;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((bSpuriousSynch_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (bRunningAcq_read_reg_260 = ap_const_lv1_1)))) then
                retval_0_reg_108 <= bStarted;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                spiSync_assign_fu_66 <= spiSync;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, bSpuriousSynch_1_ack_in, grp_read_fu_82_p2, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((bSpuriousSynch_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    SyncStarted_load_load_fu_167_p1 <= ap_sig_allocacmp_SyncStarted_load;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(bSpuriousSynch_1_ack_in)
    begin
        if ((bSpuriousSynch_1_ack_in = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_233_assign_proc : process(grp_load_fu_117_p1, grp_load_fu_120_p1, grp_load_fu_123_p1)
    begin
                ap_condition_233 <= ((grp_load_fu_123_p1 = ap_const_lv1_1) and (grp_load_fu_120_p1 = ap_const_lv1_0) and (grp_load_fu_117_p1 = ap_const_lv1_0));
    end process;


    ap_condition_320_assign_proc : process(icmp_ln51_fu_143_p2, grp_load_fu_117_p1, grp_load_fu_120_p1, grp_load_fu_123_p1)
    begin
                ap_condition_320 <= ((grp_load_fu_123_p1 = ap_const_lv1_1) and (grp_load_fu_120_p1 = ap_const_lv1_0) and (grp_load_fu_117_p1 = ap_const_lv1_0) and (icmp_ln51_fu_143_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(bSpuriousSynch_1_ack_in, ap_CS_fsm_state6)
    begin
        if (((bSpuriousSynch_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_retval_0_phi_fu_111_p4_assign_proc : process(bStarted, bRunningAcq_read_reg_260, retval_0_reg_108, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (bRunningAcq_read_reg_260 = ap_const_lv1_1))) then 
            ap_phi_mux_retval_0_phi_fu_111_p4 <= bStarted;
        else 
            ap_phi_mux_retval_0_phi_fu_111_p4 <= retval_0_reg_108;
        end if; 
    end process;


    ap_ready_assign_proc : process(bSpuriousSynch_1_ack_in, ap_CS_fsm_state6)
    begin
        if (((bSpuriousSynch_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_phi_mux_retval_0_phi_fu_111_p4;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_SyncStarted_load_assign_proc : process(SyncStarted, grp_read_fu_82_p2, ap_CS_fsm_state2, icmp_ln51_fu_143_p2, grp_load_fu_117_p1, grp_load_fu_120_p1, grp_load_fu_123_p1)
    begin
        if (((grp_load_fu_123_p1 = ap_const_lv1_1) and (grp_load_fu_120_p1 = ap_const_lv1_0) and (grp_load_fu_117_p1 = ap_const_lv1_0) and (icmp_ln51_fu_143_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_fu_82_p2 = ap_const_lv1_0))) then 
            ap_sig_allocacmp_SyncStarted_load <= ap_const_lv1_1;
        else 
            ap_sig_allocacmp_SyncStarted_load <= SyncStarted;
        end if; 
    end process;


    ap_sig_allocacmp_bCurrentSynch_load_assign_proc : process(bCurrentSynch, ap_CS_fsm_state4, or_ln29_fu_217_p2, ap_condition_233)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((ap_const_boolean_1 = ap_condition_233)) then 
                ap_sig_allocacmp_bCurrentSynch_load <= ap_const_lv1_1;
            elsif ((or_ln29_fu_217_p2 = ap_const_lv1_0)) then 
                ap_sig_allocacmp_bCurrentSynch_load <= ap_const_lv1_0;
            else 
                ap_sig_allocacmp_bCurrentSynch_load <= bCurrentSynch;
            end if;
        else 
            ap_sig_allocacmp_bCurrentSynch_load <= bCurrentSynch;
        end if; 
    end process;


    bRunningAcq_0_ack_out_assign_proc : process(bSpuriousSynch_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((bSpuriousSynch_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bRunningAcq_0_ack_out <= ap_const_logic_1;
        else 
            bRunningAcq_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    bSpuriousSynch_0_ack_out_assign_proc : process(bSpuriousSynch_1_ack_in, ap_CS_fsm_state6, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((bSpuriousSynch_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bSpuriousSynch_0_ack_out <= ap_const_logic_1;
        else 
            bSpuriousSynch_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    bSpuriousSynch_1_ack_in_assign_proc : process(bSpuriousSynch_1_vld_reg)
    begin
        if (((bSpuriousSynch_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (bSpuriousSynch_1_vld_reg = ap_const_logic_1)))) then 
            bSpuriousSynch_1_ack_in <= ap_const_logic_1;
        else 
            bSpuriousSynch_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    bSpuriousSynch_1_vld_in_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bSpuriousSynch_1_vld_in <= ap_const_logic_1;
        else 
            bSpuriousSynch_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    bSynch <= grp_load_fu_132_p1;

    bSynch_ap_vld_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bSynch_ap_vld <= ap_const_logic_1;
        else 
            bSynch_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    bufStart_0_ack_out_assign_proc : process(bSpuriousSynch_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((bSpuriousSynch_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            bufStart_0_ack_out <= ap_const_logic_1;
        else 
            bufStart_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    grp_load_fu_117_p1 <= spiSync_assign_fu_66;
    grp_load_fu_120_p1 <= spiSync_assign_fu_66;
    grp_load_fu_123_p1 <= SpiSyncLast;

    grp_load_fu_132_p1_assign_proc : process(bCurrentSynch, ap_CS_fsm_state5, ap_CS_fsm_state4, ap_sig_allocacmp_bCurrentSynch_load)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_load_fu_132_p1 <= bCurrentSynch;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_load_fu_132_p1 <= ap_sig_allocacmp_bCurrentSynch_load;
        else 
            grp_load_fu_132_p1 <= "X";
        end if; 
    end process;

    grp_read_fu_82_p2 <= bRunningAcq_0_data_reg;
    icmp_ln51_fu_143_p2 <= "1" when (bufStart_0_data_reg = ap_const_lv32_0) else "0";
    or_ln29_fu_217_p2 <= (xor_ln29_fu_211_p2 or bSpuriousSynch_0_data_reg);
    xor_ln29_fu_211_p2 <= (bSpuriousSynchLastIn xor ap_const_lv1_1);
end behav;
