-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Synch is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    spiSync : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of Synch is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Synch_Synch,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=30.302999,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.706000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=106,HLS_SYN_LUT=182,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_0_2 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bufStart : STD_LOGIC_VECTOR (31 downto 0);
    signal bufStart_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bufStart_0_vld_reg : STD_LOGIC := '0';
    signal bufStart_0_ack_out : STD_LOGIC;
    signal bStarted : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal SyncStarted : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal SpiSyncLast : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln15_fu_67_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal SyncStarted_load_load_fu_101_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_bStarted_load : STD_LOGIC_VECTOR (0 downto 0);
    signal spiSync_assign_load_load_fu_73_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiSync_assign_load_1_load_fu_76_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal SpiSyncLast_load_load_fu_79_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_SyncStarted_load : STD_LOGIC_VECTOR (0 downto 0);
    signal spiSync_assign_fu_46 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_condition_115 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component Synch_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        bufStart : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    control_s_axi_U : component Synch_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        bufStart => bufStart);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    SpiSyncLast_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((icmp_ln15_fu_67_p2 = ap_const_lv1_1)) then 
                    SpiSyncLast <= ap_const_lv1_0_2;
                elsif (((icmp_ln15_fu_67_p2 = ap_const_lv1_0) and (spiSync_assign_load_load_fu_73_p1 = ap_const_lv1_1))) then 
                    SpiSyncLast <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_condition_115)) then 
                    SpiSyncLast <= ap_const_lv1_0_1;
                end if;
            end if; 
        end if;
    end process;

    SyncStarted_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((icmp_ln15_fu_67_p2 = ap_const_lv1_1)) then 
                    SyncStarted <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_115)) then 
                    SyncStarted <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    bStarted_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((icmp_ln15_fu_67_p2 = ap_const_lv1_1)) then 
                    bStarted <= ap_const_lv1_0;
                elsif (((icmp_ln15_fu_67_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = SyncStarted_load_load_fu_101_p1))) then 
                    bStarted <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    bufStart_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (bufStart_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (bufStart_0_vld_reg = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (ap_const_logic_1 = ap_const_logic_1) and (bufStart_0_vld_reg = ap_const_logic_0)))) then
                bufStart_0_data_reg <= bufStart;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                spiSync_assign_fu_46 <= spiSync;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    SpiSyncLast_load_load_fu_79_p1 <= SpiSyncLast;
    SyncStarted_load_load_fu_101_p1 <= ap_sig_allocacmp_SyncStarted_load;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_condition_115_assign_proc : process(icmp_ln15_fu_67_p2, spiSync_assign_load_load_fu_73_p1, spiSync_assign_load_1_load_fu_76_p1, SpiSyncLast_load_load_fu_79_p1)
    begin
                ap_condition_115 <= ((icmp_ln15_fu_67_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = SpiSyncLast_load_load_fu_79_p1) and (spiSync_assign_load_1_load_fu_76_p1 = ap_const_lv1_0) and (spiSync_assign_load_load_fu_73_p1 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_sig_allocacmp_bStarted_load;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_allocacmp_SyncStarted_load_assign_proc : process(SyncStarted, ap_CS_fsm_state2, icmp_ln15_fu_67_p2, spiSync_assign_load_load_fu_73_p1, spiSync_assign_load_1_load_fu_76_p1, SpiSyncLast_load_load_fu_79_p1)
    begin
        if (((icmp_ln15_fu_67_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = SpiSyncLast_load_load_fu_79_p1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (spiSync_assign_load_1_load_fu_76_p1 = ap_const_lv1_0) and (spiSync_assign_load_load_fu_73_p1 = ap_const_lv1_0))) then 
            ap_sig_allocacmp_SyncStarted_load <= ap_const_lv1_1;
        else 
            ap_sig_allocacmp_SyncStarted_load <= SyncStarted;
        end if; 
    end process;


    ap_sig_allocacmp_bStarted_load_assign_proc : process(bStarted, ap_CS_fsm_state2, icmp_ln15_fu_67_p2, SyncStarted_load_load_fu_101_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((icmp_ln15_fu_67_p2 = ap_const_lv1_1)) then 
                ap_sig_allocacmp_bStarted_load <= ap_const_lv1_0;
            elsif (((icmp_ln15_fu_67_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = SyncStarted_load_load_fu_101_p1))) then 
                ap_sig_allocacmp_bStarted_load <= ap_const_lv1_1;
            else 
                ap_sig_allocacmp_bStarted_load <= bStarted;
            end if;
        else 
            ap_sig_allocacmp_bStarted_load <= bStarted;
        end if; 
    end process;


    bufStart_0_ack_out_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bufStart_0_ack_out <= ap_const_logic_1;
        else 
            bufStart_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln15_fu_67_p2 <= "1" when (bufStart_0_data_reg = ap_const_lv32_0) else "0";
    spiSync_assign_load_1_load_fu_76_p1 <= spiSync_assign_fu_46;
    spiSync_assign_load_load_fu_73_p1 <= spiSync_assign_fu_46;
end behav;
