// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FloatsToCounts_FloatsToCounts,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu5p-flva2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.313000,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=40,HLS_SYN_LUT=673,HLS_VERSION=2020_1}" *)

module FloatsToCounts (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r,
        ap_return
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] input_r;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_58_p2;
reg   [31:0] f_reg_208;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [31:0] p_Val2_s_fu_64_p1;
wire   [22:0] p_Repl2_s_fu_85_p1;
wire   [24:0] mantissa_V_fu_89_p4;
wire   [7:0] p_Repl2_1_fu_75_p4;
wire   [8:0] zext_ln340_fu_103_p1;
wire   [8:0] add_ln340_fu_107_p2;
wire   [7:0] sub_ln1311_fu_121_p2;
wire   [0:0] isNeg_fu_113_p3;
wire  signed [8:0] sext_ln1311_fu_127_p1;
wire   [8:0] ush_fu_131_p3;
wire  signed [31:0] sh_prom_i_i_i_cast_cast_cast_fu_139_p1;
wire   [78:0] zext_ln15_fu_99_p1;
wire   [78:0] sh_prom_i_i_i_cast_cast_cast_cast_fu_143_p1;
wire   [78:0] r_V_fu_147_p2;
wire   [0:0] tmp_fu_159_p3;
wire   [78:0] r_V_1_fu_153_p2;
wire   [31:0] zext_ln662_fu_167_p1;
wire   [31:0] tmp_1_fu_171_p4;
wire   [31:0] val_V_fu_181_p3;
wire   [0:0] p_Result_s_fu_67_p3;
wire   [31:0] result_V_1_fu_189_p2;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

FloatsToCounts_fdiv_32ns_32ns_32_7_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_7_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(input_r),
    .din1(32'd948114031),
    .ce(1'b1),
    .dout(grp_fu_58_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        f_reg_208 <= grp_fu_58_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln340_fu_107_p2 = ($signed(9'd385) + $signed(zext_ln340_fu_103_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_return = ((p_Result_s_fu_67_p3[0:0] === 1'b1) ? result_V_1_fu_189_p2 : val_V_fu_181_p3);

assign isNeg_fu_113_p3 = add_ln340_fu_107_p2[32'd8];

assign mantissa_V_fu_89_p4 = {{{{1'd1}, {p_Repl2_s_fu_85_p1}}}, {1'd0}};

assign p_Repl2_1_fu_75_p4 = {{p_Val2_s_fu_64_p1[30:23]}};

assign p_Repl2_s_fu_85_p1 = p_Val2_s_fu_64_p1[22:0];

assign p_Result_s_fu_67_p3 = p_Val2_s_fu_64_p1[32'd31];

assign p_Val2_s_fu_64_p1 = f_reg_208;

assign r_V_1_fu_153_p2 = zext_ln15_fu_99_p1 << sh_prom_i_i_i_cast_cast_cast_cast_fu_143_p1;

assign r_V_fu_147_p2 = zext_ln15_fu_99_p1 >> sh_prom_i_i_i_cast_cast_cast_cast_fu_143_p1;

assign result_V_1_fu_189_p2 = (32'd0 - val_V_fu_181_p3);

assign sext_ln1311_fu_127_p1 = $signed(sub_ln1311_fu_121_p2);

assign sh_prom_i_i_i_cast_cast_cast_cast_fu_143_p1 = $unsigned(sh_prom_i_i_i_cast_cast_cast_fu_139_p1);

assign sh_prom_i_i_i_cast_cast_cast_fu_139_p1 = $signed(ush_fu_131_p3);

assign sub_ln1311_fu_121_p2 = (8'd127 - p_Repl2_1_fu_75_p4);

assign tmp_1_fu_171_p4 = {{r_V_1_fu_153_p2[55:24]}};

assign tmp_fu_159_p3 = r_V_fu_147_p2[32'd24];

assign ush_fu_131_p3 = ((isNeg_fu_113_p3[0:0] === 1'b1) ? sext_ln1311_fu_127_p1 : add_ln340_fu_107_p2);

assign val_V_fu_181_p3 = ((isNeg_fu_113_p3[0:0] === 1'b1) ? zext_ln662_fu_167_p1 : tmp_1_fu_171_p4);

assign zext_ln15_fu_99_p1 = mantissa_V_fu_89_p4;

assign zext_ln340_fu_103_p1 = p_Repl2_1_fu_75_p4;

assign zext_ln662_fu_167_p1 = tmp_fu_159_p3;

endmodule //FloatsToCounts
